// Generated by corpus/d2/candidates/npm.collect.py for npm:memoize-one@6.0.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/memoize-one@6.0.0/package/dist/memoize-one.cjs.js');
globalThis['memoize-one'] = pkg;
