/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/intl.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Intl.SegmenterOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlSegmenterOptions(obj) {
  return [
    obj.localeMatcher,
    obj.granularity
  ];
}
globalThis['closureSelfUseIntlSegmenterOptions'] = closureSelfUseIntlSegmenterOptions;

/**
 * @param {!Intl.Segments} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlSegments(obj) {
  return [
    obj.containing()
  ];
}
globalThis['closureSelfUseIntlSegments'] = closureSelfUseIntlSegments;

/**
 * @param {!Intl.SegmentData} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlSegmentData(obj) {
  return [
    obj.segment,
    obj.index,
    obj.input,
    obj.isWordLike
  ];
}
globalThis['closureSelfUseIntlSegmentData'] = closureSelfUseIntlSegmentData;

/**
 * @param {!Intl.v8BreakIterator} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlV8BreakIterator(obj) {
  return [
    obj.breakType,
    obj.current,
    obj.first,
    obj.adoptText('closure-self'),
    obj.next()
  ];
}
globalThis['closureSelfUseIntlV8BreakIterator'] = closureSelfUseIntlV8BreakIterator;

/**
 * @param {!Intl.Collator} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlCollator(obj) {
  return [
    obj.compare('closure-self', 'closure-self'),
    obj.resolvedOptions()
  ];
}
globalThis['closureSelfUseIntlCollator'] = closureSelfUseIntlCollator;

/**
 * @param {!Intl.NumberFormat} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlNumberFormat(obj) {
  return [
    obj.format,
    obj.formatToParts,
    obj.formatRange,
    obj.formatRangeToParts,
    obj.resolvedOptions()
  ];
}
globalThis['closureSelfUseIntlNumberFormat'] = closureSelfUseIntlNumberFormat;

/**
 * @param {!Intl.DateTimeFormat} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlDateTimeFormat(obj) {
  return [
    obj.formatToParts,
    obj.formatRange,
    obj.formatRangeToParts,
    obj.format(),
    obj.resolvedOptions()
  ];
}
globalThis['closureSelfUseIntlDateTimeFormat'] = closureSelfUseIntlDateTimeFormat;

/**
 * @param {!Intl.PluralRules} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlPluralRules(obj) {
  return [
    obj.resolvedOptions(),
    obj.select(1)
  ];
}
globalThis['closureSelfUseIntlPluralRules'] = closureSelfUseIntlPluralRules;

/**
 * @param {!Intl.RelativeTimeFormat} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlRelativeTimeFormat(obj) {
  return [
    obj.formatToParts,
    obj.format(1, 'closure-self'),
    obj.resolvedOptions()
  ];
}
globalThis['closureSelfUseIntlRelativeTimeFormat'] = closureSelfUseIntlRelativeTimeFormat;

/**
 * @param {!Intl.LocaleOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlLocaleOptions(obj) {
  return [
    obj.baseName,
    obj.caseFirst,
    obj.hourCycle,
    obj.language,
    obj.numeric,
    obj.script
  ];
}
globalThis['closureSelfUseIntlLocaleOptions'] = closureSelfUseIntlLocaleOptions;

/**
 * @param {!Intl.TextInfo} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlTextInfo(obj) {
  return [
    obj.direction
  ];
}
globalThis['closureSelfUseIntlTextInfo'] = closureSelfUseIntlTextInfo;

/**
 * @param {!Intl.Locale} obj
 * @return {!Array<*>}
 */
function closureSelfUseIntlLocale(obj) {
  return [
    obj.baseName,
    obj.collation,
    obj.numeric,
    obj.getCollations,
    obj.getTimeZones,
    obj.minimize,
    obj.getCalendars(),
    obj.toString()
  ];
}
globalThis['closureSelfUseIntlLocale'] = closureSelfUseIntlLocale;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Intl.Segmenter.supportedLocalesOf,
    Intl.Collator.supportedLocalesOf,
    Intl.NumberFormat.supportedLocalesOf,
    Intl.DateTimeFormat.supportedLocalesOf,
    Intl.DisplayNames.supportedLocalesOf,
    Intl.PluralRules.supportedLocalesOf,
    Intl.RelativeTimeFormat.supportedLocalesOf,
    Intl.ListFormat.supportedLocalesOf,
    Intl.supportedValuesOf('closure-self'),
    Intl.getCanonicalLocales()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!Intl.UnicodeBCP47LocaleIdentifier} t0
 * @param {!Intl.LocaleHourCycleKey} t1
 * @param {!Intl.LocaleCollationCaseFirst} t2
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2) {
  return [
    t0,
    t1,
    t2
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
