/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.url.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/url/url.js).
 * Requires goog.url and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_url');

const target = goog.require('goog.url');

goog.exportSymbol('goog.url.resolveUrl', target.resolveUrl);
goog.exportSymbol('goog.url.getSearchParams', target.getSearchParams);
goog.exportSymbol('goog.url.resolveRelativeUrl', target.resolveRelativeUrl);
goog.exportSymbol('goog.url.createUrl', target.createUrl);
