// Generated by corpus/d2/candidates/npm.collect.py for npm:diff@9.0.0 (BSD-3-Clause).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/diff@9.0.0/package/libcjs/index.js');
globalThis['canonicalize'] = pkg.canonicalize;
globalThis['convertChangesToXML'] = pkg.convertChangesToXML;
globalThis['convertChangesToDMP'] = pkg.convertChangesToDMP;
globalThis['reversePatch'] = pkg.reversePatch;
globalThis['parsePatch'] = pkg.parsePatch;
globalThis['applyPatches'] = pkg.applyPatches;
globalThis['applyPatch'] = pkg.applyPatch;
globalThis['OMIT_HEADERS'] = pkg.OMIT_HEADERS;
globalThis['FILE_HEADERS_ONLY'] = pkg.FILE_HEADERS_ONLY;
globalThis['INCLUDE_HEADERS'] = pkg.INCLUDE_HEADERS;
globalThis['formatPatch'] = pkg.formatPatch;
globalThis['createPatch'] = pkg.createPatch;
globalThis['createTwoFilesPatch'] = pkg.createTwoFilesPatch;
globalThis['structuredPatch'] = pkg.structuredPatch;
globalThis['arrayDiff'] = pkg.arrayDiff;
globalThis['diffArrays'] = pkg.diffArrays;
globalThis['jsonDiff'] = pkg.jsonDiff;
globalThis['diffJson'] = pkg.diffJson;
globalThis['cssDiff'] = pkg.cssDiff;
globalThis['diffCss'] = pkg.diffCss;
globalThis['sentenceDiff'] = pkg.sentenceDiff;
globalThis['diffSentences'] = pkg.diffSentences;
globalThis['diffTrimmedLines'] = pkg.diffTrimmedLines;
globalThis['lineDiff'] = pkg.lineDiff;
globalThis['diffLines'] = pkg.diffLines;
globalThis['wordsWithSpaceDiff'] = pkg.wordsWithSpaceDiff;
globalThis['diffWordsWithSpace'] = pkg.diffWordsWithSpace;
globalThis['wordDiff'] = pkg.wordDiff;
globalThis['diffWords'] = pkg.diffWords;
globalThis['characterDiff'] = pkg.characterDiff;
globalThis['diffChars'] = pkg.diffChars;
globalThis['Diff'] = pkg.Diff;
