/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-decimal.js-10.6.0.
 *
 * The library's own tests run uncompiled against the compiled decimal.js@10.6.0, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files, plus randomBytes. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype.abs;
/** @type {?} */
Object.prototype.absoluteValue;
/** @type {?} */
Object.prototype.acos;
/** @type {?} */
Object.prototype.acosh;
/** @type {?} */
Object.prototype.add;
/** @type {?} */
Object.prototype.asin;
/** @type {?} */
Object.prototype.asinh;
/** @type {?} */
Object.prototype.atan;
/** @type {?} */
Object.prototype.atan2;
/** @type {?} */
Object.prototype.atanh;
/** @type {?} */
Object.prototype.cbrt;
/** @type {?} */
Object.prototype.ceil;
/** @type {?} */
Object.prototype.clamp;
/** @type {?} */
Object.prototype.clone;
/** @type {?} */
Object.prototype.cmp;
/** @type {?} */
Object.prototype.comparedTo;
/** @type {?} */
Object.prototype.config;
/** @type {?} */
Object.prototype.cos;
/** @type {?} */
Object.prototype.cosh;
/** @type {?} */
Object.prototype.cosine;
/** @type {?} */
Object.prototype.crypto;
/** @type {?} */
Object.prototype.cubeRoot;
/** @type {?} */
Object.prototype.d;
/** @type {?} */
Object.prototype.decimalPlaces;
/** @type {?} */
Object.prototype.defaults;
/** @type {?} */
Object.prototype.div;
/** @type {?} */
Object.prototype.divToInt;
/** @type {?} */
Object.prototype.dividedBy;
/** @type {?} */
Object.prototype.dividedToIntegerBy;
/** @type {?} */
Object.prototype.dp;
/** @type {?} */
Object.prototype.e;
/** @type {?} */
Object.prototype.eq;
/** @type {?} */
Object.prototype.equals;
/** @type {?} */
Object.prototype.exp;
/** @type {?} */
Object.prototype.floor;
/** @type {?} */
Object.prototype.for;
/** @type {?} */
Object.prototype.greaterThan;
/** @type {?} */
Object.prototype.greaterThanOrEqualTo;
/** @type {?} */
Object.prototype.gt;
/** @type {?} */
Object.prototype.gte;
/** @type {?} */
Object.prototype.hyperbolicCosine;
/** @type {?} */
Object.prototype.hyperbolicSine;
/** @type {?} */
Object.prototype.hyperbolicTangent;
/** @type {?} */
Object.prototype.hypot;
/** @type {?} */
Object.prototype.inverseCosine;
/** @type {?} */
Object.prototype.inverseHyperbolicCosine;
/** @type {?} */
Object.prototype.inverseHyperbolicSine;
/** @type {?} */
Object.prototype.inverseHyperbolicTangent;
/** @type {?} */
Object.prototype.inverseSine;
/** @type {?} */
Object.prototype.inverseTangent;
/** @type {?} */
Object.prototype.isDecimal;
/** @type {?} */
Object.prototype.isFinite;
/** @type {?} */
Object.prototype.isInt;
/** @type {?} */
Object.prototype.isInteger;
/** @type {?} */
Object.prototype.isNaN;
/** @type {?} */
Object.prototype.isNeg;
/** @type {?} */
Object.prototype.isNegative;
/** @type {?} */
Object.prototype.isPos;
/** @type {?} */
Object.prototype.isPositive;
/** @type {?} */
Object.prototype.isZero;
/** @type {?} */
Object.prototype.length;
/** @type {?} */
Object.prototype.lessThan;
/** @type {?} */
Object.prototype.lessThanOrEqualTo;
/** @type {?} */
Object.prototype.ln;
/** @type {?} */
Object.prototype.log;
/** @type {?} */
Object.prototype.log10;
/** @type {?} */
Object.prototype.log2;
/** @type {?} */
Object.prototype.logarithm;
/** @type {?} */
Object.prototype.lt;
/** @type {?} */
Object.prototype.lte;
/** @type {?} */
Object.prototype.max;
/** @type {?} */
Object.prototype.maxE;
/** @type {?} */
Object.prototype.min;
/** @type {?} */
Object.prototype.minE;
/** @type {?} */
Object.prototype.minus;
/** @type {?} */
Object.prototype.mod;
/** @type {?} */
Object.prototype.modulo;
/** @type {?} */
Object.prototype.mul;
/** @type {?} */
Object.prototype.naturalExponential;
/** @type {?} */
Object.prototype.naturalLogarithm;
/** @type {?} */
Object.prototype.neg;
/** @type {?} */
Object.prototype.negated;
/** @type {?} */
Object.prototype.plus;
/** @type {?} */
Object.prototype.pow;
/** @type {?} */
Object.prototype.precision;
/** @type {?} */
Object.prototype.random;
/** @type {?} */
Object.prototype.randomBytes;
/** @type {?} */
Object.prototype.replace;
/** @type {?} */
Object.prototype.round;
/** @type {?} */
Object.prototype.rounding;
/** @type {?} */
Object.prototype.s;
/** @type {?} */
Object.prototype.sd;
/** @type {?} */
Object.prototype.set;
/** @type {?} */
Object.prototype.sign;
/** @type {?} */
Object.prototype.sin;
/** @type {?} */
Object.prototype.sine;
/** @type {?} */
Object.prototype.sinh;
/** @type {?} */
Object.prototype.sqrt;
/** @type {?} */
Object.prototype.squareRoot;
/** @type {?} */
Object.prototype.sub;
/** @type {?} */
Object.prototype.sum;
/** @type {?} */
Object.prototype.tan;
/** @type {?} */
Object.prototype.tangent;
/** @type {?} */
Object.prototype.tanh;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.times;
/** @type {?} */
Object.prototype.toBinary;
/** @type {?} */
Object.prototype.toDP;
/** @type {?} */
Object.prototype.toDecimalPlaces;
/** @type {?} */
Object.prototype.toExpNeg;
/** @type {?} */
Object.prototype.toExpPos;
/** @type {?} */
Object.prototype.toExponential;
/** @type {?} */
Object.prototype.toFixed;
/** @type {?} */
Object.prototype.toFraction;
/** @type {?} */
Object.prototype.toHex;
/** @type {?} */
Object.prototype.toHexadecimal;
/** @type {?} */
Object.prototype.toNearest;
/** @type {?} */
Object.prototype.toNumber;
/** @type {?} */
Object.prototype.toOctal;
/** @type {?} */
Object.prototype.toPower;
/** @type {?} */
Object.prototype.toPrecision;
/** @type {?} */
Object.prototype.toSD;
/** @type {?} */
Object.prototype.toSignificantDigits;
/** @type {?} */
Object.prototype.trunc;
/** @type {?} */
Object.prototype.truncated;
