// Generated by corpus/d2/candidates/npm.collect.py for npm:a11y-dialog@8.1.5 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/a11y-dialog@8.1.5/package/dist/a11y-dialog.cjs');
globalThis['a11y-dialog'] = pkg;
