// Generated by corpus/d2/candidates/npm.collect.py for npm:validator@13.15.35 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/validator@13.15.35/package/index.js');
globalThis['default'] = pkg.default;
globalThis['validator'] = pkg;
