/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/ie_css.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!StyleSheet} obj
 * @return {!Array<*>}
 */
function closureSelfUseStyleSheet(obj) {
  return [
    obj.owningElement,
    obj.imports,
    obj.addRule,
    obj.removeRule,
    obj.getExpression,
    obj.removeExpression
  ];
}
globalThis['closureSelfUseStyleSheet'] = closureSelfUseStyleSheet;

/**
 * @param {!CSSStyleProperties} obj
 * @return {!Array<*>}
 */
function closureSelfUseCSSStyleProperties(obj) {
  return [
    obj.backgroundPositionX,
    obj.styleFloat,
    obj.MsLayoutGrid,
    obj.MsScrollbarArrowColor,
    obj.MsTextKashidaSpace,
    obj.msTransition
  ];
}
globalThis['closureSelfUseCSSStyleProperties'] = closureSelfUseCSSStyleProperties;
