// Generated by corpus/d2/candidates/npm.collect.py for npm:fecha@4.2.3 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  assign as e_assign,
  default as e_default,
  defaultI18n as e_defaultI18n,
  format as e_format,
  parse as e_parse,
  setGlobalDateI18n as e_setGlobalDateI18n,
  setGlobalDateMasks as e_setGlobalDateMasks,
} from '../../../../corpus-cache/d2/npm/fecha@4.2.3/package/lib/fecha.js';
globalThis['assign'] = e_assign;
globalThis['default'] = e_default;
globalThis['defaultI18n'] = e_defaultI18n;
globalThis['format'] = e_format;
globalThis['parse'] = e_parse;
globalThis['setGlobalDateI18n'] = e_setGlobalDateI18n;
globalThis['setGlobalDateMasks'] = e_setGlobalDateMasks;
