// Generated by corpus/d2/candidates/npm.collect.py for npm:flatpickr@4.6.13 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/flatpickr@4.6.13/package/dist/flatpickr.js');
globalThis['flatpickr'] = pkg;
