/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-bytes-3.1.2.
 *
 * The library's own tests run uncompiled against the compiled bytes@3.1.2, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype.b;
/** @type {?} */
Object.prototype.decimalPlaces;
/** @type {?} */
Object.prototype.fixedDecimals;
/** @type {?} */
Object.prototype.format;
/** @type {?} */
Object.prototype.gb;
/** @type {?} */
Object.prototype.kb;
/** @type {?} */
Object.prototype.mb;
/** @type {?} */
Object.prototype.parse;
/** @type {?} */
Object.prototype.pb;
/** @type {?} */
Object.prototype.pow;
/** @type {?} */
Object.prototype.tb;
/** @type {?} */
Object.prototype.thousandsSeparator;
/** @type {?} */
Object.prototype.toLowerCase;
/** @type {?} */
Object.prototype.unit;
/** @type {?} */
Object.prototype.unitSeparator;
