// closure-rs D2 whole-program case whole-program-bytes-3.1.2: runs the own test suite of
// bytes@3.1.2 (visionmedia/bytes.js @ 9ddc13b6c66e) against a compiled output.
//   node corpus/d2/shims/whole-program-bytes-3.1.2/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-bytes-3.1.2/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-bytes-3.1.2",
  "global": "bytes",
  "testDir": "corpus-cache/d2/whole-program/bytes@3.1.2/repo",
  "framework": "mocha",
  "files": [
    "test/byte-format.js",
    "test/byte-parse.js",
    "test/bytes.js"
  ],
  "modules": {
    "..": {
      "path": []
    },
    "../index.js": {
      "path": []
    }
  },
  "expectTests": 30
});
