// Generated by corpus/d2/candidates/npm.collect.py for npm:class-transformer@0.5.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  ClassTransformer as e_ClassTransformer,
  Exclude as e_Exclude,
  Expose as e_Expose,
  Transform as e_Transform,
  TransformInstanceToInstance as e_TransformInstanceToInstance,
  TransformInstanceToPlain as e_TransformInstanceToPlain,
  TransformPlainToInstance as e_TransformPlainToInstance,
  TransformationType as e_TransformationType,
  Type as e_Type,
  classToClassFromExist as e_classToClassFromExist,
  classToPlain as e_classToPlain,
  classToPlainFromExist as e_classToPlainFromExist,
  deserialize as e_deserialize,
  deserializeArray as e_deserializeArray,
  instanceToInstance as e_instanceToInstance,
  instanceToPlain as e_instanceToPlain,
  plainToClass as e_plainToClass,
  plainToClassFromExist as e_plainToClassFromExist,
  plainToInstance as e_plainToInstance,
  serialize as e_serialize,
} from '../../../../corpus-cache/d2/npm/class-transformer@0.5.1/package/esm5/index.js';
globalThis['ClassTransformer'] = e_ClassTransformer;
globalThis['Exclude'] = e_Exclude;
globalThis['Expose'] = e_Expose;
globalThis['Transform'] = e_Transform;
globalThis['TransformInstanceToInstance'] = e_TransformInstanceToInstance;
globalThis['TransformInstanceToPlain'] = e_TransformInstanceToPlain;
globalThis['TransformPlainToInstance'] = e_TransformPlainToInstance;
globalThis['TransformationType'] = e_TransformationType;
globalThis['Type'] = e_Type;
globalThis['classToClassFromExist'] = e_classToClassFromExist;
globalThis['classToPlain'] = e_classToPlain;
globalThis['classToPlainFromExist'] = e_classToPlainFromExist;
globalThis['deserialize'] = e_deserialize;
globalThis['deserializeArray'] = e_deserializeArray;
globalThis['instanceToInstance'] = e_instanceToInstance;
globalThis['instanceToPlain'] = e_instanceToPlain;
globalThis['plainToClass'] = e_plainToClass;
globalThis['plainToClassFromExist'] = e_plainToClassFromExist;
globalThis['plainToInstance'] = e_plainToInstance;
globalThis['serialize'] = e_serialize;
