/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-class-transformer-0.5.1-pkg-esm:
 * Node.js/AMD globals referenced by npm:class-transformer@0.5.1 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var Buffer;

/** @type {?} */
var global;
