/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/url.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!URLSearchParams} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLSearchParams(obj) {
  return [
    obj.delete,
    obj.forEach,
    obj.get,
    obj.has,
    obj.keys,
    obj.sort,
    obj.append('closure-self', 'closure-self'),
    obj.values()
  ];
}
globalThis['closureSelfUseURLSearchParams'] = closureSelfUseURLSearchParams;

/**
 * @param {!URL} obj
 * @return {!Array<*>}
 */
function closureSelfUseURL(obj) {
  return [
    obj.href,
    obj.protocol,
    obj.password,
    obj.port,
    obj.search,
    obj.hash
  ];
}
globalThis['closureSelfUseURL'] = closureSelfUseURL;

/**
 * @param {!URLPatternComponentResult} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLPatternComponentResult(obj) {
  return [
    obj.groups,
    obj.input
  ];
}
globalThis['closureSelfUseURLPatternComponentResult'] = closureSelfUseURLPatternComponentResult;

/**
 * @param {!URLPatternInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLPatternInit(obj) {
  return [
    obj.baseURL,
    obj.hostname,
    obj.password,
    obj.port,
    obj.protocol,
    obj.username
  ];
}
globalThis['closureSelfUseURLPatternInit'] = closureSelfUseURLPatternInit;

/**
 * @param {!URLPatternOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLPatternOptions(obj) {
  return [
    obj.ignoreCase
  ];
}
globalThis['closureSelfUseURLPatternOptions'] = closureSelfUseURLPatternOptions;

/**
 * @param {!URLPatternResult} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLPatternResult(obj) {
  return [
    obj.hash,
    obj.inputs,
    obj.password,
    obj.port,
    obj.protocol,
    obj.username
  ];
}
globalThis['closureSelfUseURLPatternResult'] = closureSelfUseURLPatternResult;

/**
 * @param {!URLPattern} obj
 * @return {!Array<*>}
 */
function closureSelfUseURLPattern(obj) {
  return [
    obj.hasRegExpGroups,
    obj.hostname,
    obj.password,
    obj.port,
    obj.protocol,
    obj.username,
    obj.exec(),
    obj.test()
  ];
}
globalThis['closureSelfUseURLPattern'] = closureSelfUseURLPattern;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    URL.createObjectURL,
    URL.canParse,
    URL.revokeObjectURL,
    URL.domainToASCII('closure-self'),
    URL.domainToUnicode('closure-self')
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!URLSearchParamsTupleType} t0
 * @param {!URLPatternInput} t1
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1) {
  return [
    t0,
    t1
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
