// Generated by corpus/d2/candidates/npm.collect.py for npm:nanoid@6.0.2 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  customAlphabet as e_customAlphabet,
  customRandom as e_customRandom,
  nanoid as e_nanoid,
  random as e_random,
  urlAlphabet as e_urlAlphabet,
} from '../../../../corpus-cache/d2/npm/nanoid@6.0.2/package/index.browser.js';
globalThis['customAlphabet'] = e_customAlphabet;
globalThis['customRandom'] = e_customRandom;
globalThis['nanoid'] = e_nanoid;
globalThis['random'] = e_random;
globalThis['urlAlphabet'] = e_urlAlphabet;
