/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/web_app_manifest.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!BeforeInstallPromptEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseBeforeInstallPromptEvent(obj) {
  return [
    obj.userChoice,
    obj.prompt()
  ];
}
globalThis['closureSelfUseBeforeInstallPromptEvent'] = closureSelfUseBeforeInstallPromptEvent;

/**
 * @param {!Window} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindow(obj) {
  return [
    obj.onbeforeinstallprompt,
    obj.onappinstalled
  ];
}
globalThis['closureSelfUseWindow'] = closureSelfUseWindow;

/**
 * @param {!AppBannerPromptOutcome} t0
 * @param {!PromptResponseObject} t1
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1) {
  return [
    t0,
    t1
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
