// Generated by corpus/d2/candidates/npm.collect.py for npm:@noble/hashes@2.4.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import * as ns from '../../../../corpus-cache/d2/npm/@noble/hashes@2.4.0/package/index.js';
globalThis['@noble/hashes'] = ns;
