/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-web-vitals-6.2.3-pkg-cjs:
 * Node.js/AMD globals referenced by npm:web-vitals@6.2.3 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
