/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-baconjs-3.0.23-pkg-cjs:
 * Node.js/AMD globals referenced by npm:baconjs@3.0.23 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var Buffer;

/** @type {?} */
var global;

/** @type {?} */
var define;
