// Generated by corpus/d2/candidates/npm.collect.py for npm:decimal.js@10.6.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Decimal as e_Decimal,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/decimal.js@10.6.0/package/decimal.mjs';
globalThis['Decimal'] = e_Decimal;
globalThis['default'] = e_default;
