/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.storage.collectablestorage.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/storage/collectablestorage.js).
 * Requires goog.storage.CollectableStorage and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_storage_CollectableStorage');

const target = goog.require('goog.storage.CollectableStorage');

goog.exportSymbol('goog.storage.CollectableStorage', target);
goog.exportProperty(target.prototype, 'collect', target.prototype.collect);
