/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-sortablejs-1.15.7-pkg-cjs:
 * Node.js/AMD globals referenced by npm:sortablejs@1.15.7 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
