/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.positioning.anchoredposition.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/positioning/anchoredposition.js).
 * Requires goog.positioning.AnchoredPosition and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_positioning_AnchoredPosition');

const target = goog.require('goog.positioning.AnchoredPosition');

goog.exportSymbol('goog.positioning.AnchoredPosition', target);
goog.exportProperty(target.prototype, 'reposition', target.prototype.reposition);
