// Generated by corpus/d2/candidates/npm.collect.py for npm:tailwind-merge@3.7.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  createTailwindMerge as e_createTailwindMerge,
  extendTailwindMerge as e_extendTailwindMerge,
  fromTheme as e_fromTheme,
  getDefaultConfig as e_getDefaultConfig,
  mergeConfigs as e_mergeConfigs,
  twJoin as e_twJoin,
  twMerge as e_twMerge,
  validators as e_validators,
} from '../../../../corpus-cache/d2/npm/tailwind-merge@3.7.0/package/dist/bundle-mjs.mjs';
globalThis['createTailwindMerge'] = e_createTailwindMerge;
globalThis['extendTailwindMerge'] = e_extendTailwindMerge;
globalThis['fromTheme'] = e_fromTheme;
globalThis['getDefaultConfig'] = e_getDefaultConfig;
globalThis['mergeConfigs'] = e_mergeConfigs;
globalThis['twJoin'] = e_twJoin;
globalThis['twMerge'] = e_twMerge;
globalThis['validators'] = e_validators;
