// Generated by corpus/d2/candidates/npm.collect.py for npm:semver@7.8.5 (ISC).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/semver@7.8.5/package/index.js');
globalThis['semver'] = pkg;
