/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-semver-7.8.5-pkg-cjs:
 * Node.js/AMD globals referenced by npm:semver@7.8.5 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;
