// Generated by corpus/d2/candidates/npm.collect.py for npm:acorn-walk@8.3.5 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  ancestor as e_ancestor,
  base as e_base,
  findNodeAfter as e_findNodeAfter,
  findNodeAround as e_findNodeAround,
  findNodeAt as e_findNodeAt,
  findNodeBefore as e_findNodeBefore,
  full as e_full,
  fullAncestor as e_fullAncestor,
  make as e_make,
  recursive as e_recursive,
  simple as e_simple,
} from '../../../../corpus-cache/d2/npm/acorn-walk@8.3.5/package/dist/walk.mjs';
globalThis['ancestor'] = e_ancestor;
globalThis['base'] = e_base;
globalThis['findNodeAfter'] = e_findNodeAfter;
globalThis['findNodeAround'] = e_findNodeAround;
globalThis['findNodeAt'] = e_findNodeAt;
globalThis['findNodeBefore'] = e_findNodeBefore;
globalThis['full'] = e_full;
globalThis['fullAncestor'] = e_fullAncestor;
globalThis['make'] = e_make;
globalThis['recursive'] = e_recursive;
globalThis['simple'] = e_simple;
