/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.tweak.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/tweak/tweak.js).
 * Requires goog.tweak and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_tweak');

const target = goog.require('goog.tweak');

goog.exportSymbol('goog.tweak.beginBooleanGroup', target.beginBooleanGroup);
goog.exportSymbol('goog.tweak.endBooleanGroup', target.endBooleanGroup);
goog.exportSymbol('goog.tweak.registerButton', target.registerButton);
goog.exportSymbol('goog.tweak.getBoolean', target.getBoolean);
goog.exportSymbol('goog.tweak.getString', target.getString);
goog.exportSymbol('goog.tweak.getNumber', target.getNumber);
