/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.reflect.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/reflect/reflect.js).
 * Requires goog.reflect and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_reflect');

const target = goog.require('goog.reflect');

goog.exportSymbol('goog.reflect.object', target.object);
goog.exportSymbol('goog.reflect.objectProperty', target.objectProperty);
goog.exportSymbol('goog.reflect.sinkValue', target.sinkValue);
goog.exportSymbol('goog.reflect.canAccessProperty', target.canAccessProperty);
goog.exportSymbol('goog.reflect.cache', target.cache);
