// Generated by corpus/d2/candidates/npm.collect.py for npm:rrule@2.8.1 (BSD-3-Clause).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/rrule@2.8.1/package/dist/es5/rrule.js');
globalThis['rrule'] = pkg.rrule;
globalThis['rrule'] = pkg;
