// Generated by corpus/d2/candidates/npm.collect.py for npm:uikit@3.25.26 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/uikit@3.25.26/package/dist/js/uikit.js');
globalThis['uikit'] = pkg;
