/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-uikit-3.25.26-pkg-cjs:
 * Node.js/AMD globals referenced by npm:uikit@3.25.26 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
