// Generated by corpus/d2/candidates/npm.collect.py for npm:clipboard@2.0.11 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/clipboard@2.0.11/package/dist/clipboard.js');
globalThis['ClipboardJS'] = pkg.ClipboardJS;
globalThis['node'] = pkg.node;
globalThis['nodeList'] = pkg.nodeList;
globalThis['string'] = pkg.string;
globalThis['fn'] = pkg.fn;
globalThis['TinyEmitter'] = pkg.TinyEmitter;
globalThis['clipboard'] = pkg;
