/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.menuitemrenderer.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/menuitemrenderer.js).
 * Requires goog.ui.MenuItemRenderer and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_MenuItemRenderer');

const target = goog.require('goog.ui.MenuItemRenderer');

goog.exportSymbol('goog.ui.MenuItemRenderer', target);
goog.exportSymbol('goog.ui.MenuItemRenderer.CSS_CLASS', target.CSS_CLASS);
goog.exportProperty(target.prototype, 'getAriaRole', target.prototype.getAriaRole);
goog.exportProperty(target.prototype, 'createDom', target.prototype.createDom);
goog.exportProperty(target.prototype, 'getContentElement', target.prototype.getContentElement);
goog.exportProperty(target.prototype, 'decorate', target.prototype.decorate);
