// Generated by corpus/d2/candidates/npm.collect.py for npm:js-cookie@3.0.8 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/js-cookie@3.0.8/package/dist/js.cookie.js');
globalThis['noConflict'] = pkg.noConflict;
globalThis['js-cookie'] = pkg;
