/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-js-cookie-3.0.8-pkg-cjs:
 * Node.js/AMD globals referenced by npm:js-cookie@3.0.8 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
