// Generated by corpus/d2/candidates/npm.collect.py for npm:fraction.js@5.3.4 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Fraction as e_Fraction,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/fraction.js@5.3.4/package/dist/fraction.mjs';
globalThis['Fraction'] = e_Fraction;
globalThis['default'] = e_default;
