// closure-rs D2 whole-program case whole-program-leven-4.1.0: runs the own test suite of
// leven@4.1.0 (sindresorhus/leven @ 235e7758c8ec) against a compiled output.
//   node corpus/d2/shims/whole-program-leven-4.1.0/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-leven-4.1.0/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-leven-4.1.0",
  "global": "leven",
  "testDir": "corpus-cache/d2/whole-program/leven@4.1.0/repo",
  "framework": "ava",
  "files": [
    "test.js"
  ],
  "modules": {
    "./index.js": {
      "path": [],
      "namespace": true
    }
  },
  "expectTests": 3
});
