/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.tooltip.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/tooltip.js).
 * Requires goog.ui.Tooltip and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_Tooltip');

const target = goog.require('goog.ui.Tooltip');

goog.exportSymbol('goog.ui.Tooltip', target);
goog.exportSymbol('goog.ui.Tooltip.State', target.State);
goog.exportSymbol('goog.ui.Tooltip.Activation', target.Activation);
goog.exportSymbol('goog.ui.Tooltip.CursorTooltipPosition', target.CursorTooltipPosition);
goog.exportSymbol('goog.ui.Tooltip.ElementTooltipPosition', target.ElementTooltipPosition);
goog.exportProperty(target.prototype, 'className', target.prototype.className);
goog.exportProperty(target.prototype, 'getDomHelper', target.prototype.getDomHelper);
goog.exportProperty(target.prototype, 'attach', target.prototype.attach);
goog.exportProperty(target.prototype, 'detach', target.prototype.detach);
