// Generated by corpus/d2/candidates/npm.collect.py for npm:simplex-noise@4.0.3 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/simplex-noise@4.0.3/package/dist/cjs/simplex-noise.js');
globalThis['buildPermutationTable'] = pkg.buildPermutationTable;
globalThis['createNoise4D'] = pkg.createNoise4D;
globalThis['createNoise3D'] = pkg.createNoise3D;
globalThis['createNoise2D'] = pkg.createNoise2D;
