/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-bignumber.js-11.1.5.
 *
 * The library's own tests run uncompiled against the compiled bignumber.js@11.1.5, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files, plus randomBytes. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype.ALPHABET;
/** @type {?} */
Object.prototype.BigNumber;
/** @type {?} */
Object.prototype.CRYPTO;
/** @type {?} */
Object.prototype.DECIMAL_PLACES;
/** @type {?} */
Object.prototype.EXPONENTIAL_AT;
/** @type {?} */
Object.prototype.FORMAT;
/** @type {?} */
Object.prototype.POW_PRECISION;
/** @type {?} */
Object.prototype.RANGE;
/** @type {?} */
Object.prototype.ROUNDING_MODE;
/** @type {?} */
Object.prototype.ROUND_HALF_CEIL;
/** @type {?} */
Object.prototype.STRICT;
/** @type {?} */
Object.prototype._isBigNumber;
/** @type {?} */
Object.prototype.abs;
/** @type {?} */
Object.prototype.absoluteValue;
/** @type {?} */
Object.prototype.c;
/** @type {?} */
Object.prototype.call;
/** @type {?} */
Object.prototype.clone;
/** @type {?} */
Object.prototype.comparedTo;
/** @type {?} */
Object.prototype.config;
/** @type {?} */
Object.prototype.decimalPlaces;
/** @type {?} */
Object.prototype.decimalSeparator;
/** @type {?} */
Object.prototype.div;
/** @type {?} */
Object.prototype.dividedBy;
/** @type {?} */
Object.prototype.dividedToIntegerBy;
/** @type {?} */
Object.prototype.dp;
/** @type {?} */
Object.prototype.e;
/** @type {?} */
Object.prototype.eq;
/** @type {?} */
Object.prototype.exponentiatedBy;
/** @type {?} */
Object.prototype.floor;
/** @type {?} */
Object.prototype.fractionGroupSeparator;
/** @type {?} */
Object.prototype.fractionGroupSize;
/** @type {?} */
Object.prototype.fromFormat;
/** @type {?} */
Object.prototype.groupSeparator;
/** @type {?} */
Object.prototype.groupSize;
/** @type {?} */
Object.prototype.gt;
/** @type {?} */
Object.prototype.gte;
/** @type {?} */
Object.prototype.idiv;
/** @type {?} */
Object.prototype.integerValue;
/** @type {?} */
Object.prototype.isBigNumber;
/** @type {?} */
Object.prototype.isEqualTo;
/** @type {?} */
Object.prototype.isFinite;
/** @type {?} */
Object.prototype.isGreaterThan;
/** @type {?} */
Object.prototype.isGreaterThanOrEqualTo;
/** @type {?} */
Object.prototype.isInteger;
/** @type {?} */
Object.prototype.isLessThan;
/** @type {?} */
Object.prototype.isLessThanOrEqualTo;
/** @type {?} */
Object.prototype.isNaN;
/** @type {?} */
Object.prototype.isNegative;
/** @type {?} */
Object.prototype.isPositive;
/** @type {?} */
Object.prototype.isZero;
/** @type {?} */
Object.prototype.length;
/** @type {?} */
Object.prototype.lt;
/** @type {?} */
Object.prototype.lte;
/** @type {?} */
Object.prototype.max;
/** @type {?} */
Object.prototype.maximum;
/** @type {?} */
Object.prototype.min;
/** @type {?} */
Object.prototype.minimum;
/** @type {?} */
Object.prototype.minus;
/** @type {?} */
Object.prototype.mod;
/** @type {?} */
Object.prototype.modulo;
/** @type {?} */
Object.prototype.multipliedBy;
/** @type {?} */
Object.prototype.negated;
/** @type {?} */
Object.prototype.negativeSign;
/** @type {?} */
Object.prototype.plus;
/** @type {?} */
Object.prototype.positiveSign;
/** @type {?} */
Object.prototype.pow;
/** @type {?} */
Object.prototype.precision;
/** @type {?} */
Object.prototype.prefix;
/** @type {?} */
Object.prototype.r;
/** @type {?} */
Object.prototype.random;
/** @type {?} */
Object.prototype.randomBytes;
/** @type {?} */
Object.prototype.replace;
/** @type {?} */
Object.prototype.s;
/** @type {?} */
Object.prototype.sd;
/** @type {?} */
Object.prototype.secondaryGroupSize;
/** @type {?} */
Object.prototype.set;
/** @type {?} */
Object.prototype.shiftedBy;
/** @type {?} */
Object.prototype.slice;
/** @type {?} */
Object.prototype.sqrt;
/** @type {?} */
Object.prototype.squareRoot;
/** @type {?} */
Object.prototype.suffix;
/** @type {?} */
Object.prototype.sum;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.times;
/** @type {?} */
Object.prototype.toBigInt;
/** @type {?} */
Object.prototype.toExponential;
/** @type {?} */
Object.prototype.toFixed;
/** @type {?} */
Object.prototype.toFormat;
/** @type {?} */
Object.prototype.toFraction;
/** @type {?} */
Object.prototype.toNumber;
/** @type {?} */
Object.prototype.toObject;
/** @type {?} */
Object.prototype.toPrecision;
