// closure-rs D2 whole-program case whole-program-bignumber.js-11.1.5: runs the own test suite of
// bignumber.js@11.1.5 (MikeMcl/bignumber.js @ 275cd8518104) against a compiled output.
//   node corpus/d2/shims/whole-program-bignumber.js-11.1.5/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-bignumber.js-11.1.5/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-bignumber.js-11.1.5",
  "global": "BigNumber",
  "testDir": "corpus-cache/d2/whole-program/bignumber.js@11.1.5/repo",
  "framework": "custom",
  "modules": {
    "../dist/bignumber.cjs": {
      "path": []
    },
    "../bignumber": {
      "path": []
    }
  },
  "expectTests": 34,
  register(h) {
    // Same files, in the same order, as the upstream runner test/test.js (list parsed from it).
    const list = [...h.read("test/test.js").match(/\[([^\]]*)\]\s*\.forEach/)[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
    h.require("test/tester.js");
    for (const name of list) {
      h.test(`test/methods/${name}.js`, () => {
        h.require(`test/methods/${name}.js`);
        const [passed, count] = globalThis.Test.result;
        if (count === 0 || passed !== count) throw new Error(`${passed} of ${count} assertions passed`);
      });
    }
  },
});
