// Generated by corpus/d2/candidates/npm.collect.py for npm:notyf@3.10.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/notyf@3.10.0/package/notyf.js');
globalThis['NotyfArrayEvent'] = pkg.NotyfArrayEvent;
globalThis['NotyfEvent'] = pkg.NotyfEvent;
globalThis['DEFAULT_OPTIONS'] = pkg.DEFAULT_OPTIONS;
globalThis['Notyf'] = pkg.Notyf;
globalThis['NotyfArray'] = pkg.NotyfArray;
globalThis['NotyfNotification'] = pkg.NotyfNotification;
globalThis['NotyfView'] = pkg.NotyfView;
