/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-immer-11.1.21-pkg-esm:
 * Node.js/AMD globals referenced by npm:immer@11.1.21 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;
