// Generated by corpus/d2/candidates/npm.collect.py for npm:goober@2.1.19 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/goober@2.1.19/package/dist/goober.cjs');
globalThis['css'] = pkg.css;
globalThis['extractCss'] = pkg.extractCss;
globalThis['glob'] = pkg.glob;
globalThis['keyframes'] = pkg.keyframes;
globalThis['setup'] = pkg.setup;
globalThis['styled'] = pkg.styled;
