/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-autosize-6.0.1-pkg-cjs:
 * Node.js/AMD globals referenced by npm:autosize@6.0.1 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
