/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-tiny-invariant-1.3.3-pkg-cjs:
 * Node.js/AMD globals referenced by npm:tiny-invariant@1.3.3 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;
