// Generated by corpus/d2/candidates/npm.collect.py for npm:navigo@8.11.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/navigo@8.11.1/package/lib/navigo.js');
globalThis['Navigo'] = pkg.Navigo;
globalThis['navigo'] = pkg;
