// Generated by corpus/d2/candidates/npm.collect.py for npm:regenerator-runtime@0.14.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/regenerator-runtime@0.14.1/package/runtime.js');
globalThis['wrap'] = pkg.wrap;
globalThis['isGeneratorFunction'] = pkg.isGeneratorFunction;
globalThis['mark'] = pkg.mark;
globalThis['awrap'] = pkg.awrap;
globalThis['AsyncIterator'] = pkg.AsyncIterator;
globalThis['async'] = pkg.async;
globalThis['keys'] = pkg.keys;
globalThis['values'] = pkg.values;
