// Generated by corpus/d2/candidates/npm.collect.py for npm:cleave.js@1.6.0 (Apache-2.0).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/cleave.js@1.6.0/package/dist/cleave-esm.js';
globalThis['default'] = e_default;
