/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.events.eventobserver.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/events/eventobserver.js).
 * Requires goog.testing.events.EventObserver and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_events_EventObserver');

const target = goog.require('goog.testing.events.EventObserver');

goog.exportSymbol('goog.testing.events.EventObserver', target);
goog.exportProperty(target.prototype, 'handleEvent', target.prototype.handleEvent);
goog.exportProperty(target.prototype, 'getEvents', target.prototype.getEvents);
goog.exportProperty(target.prototype, 'clear', target.prototype.clear);
