/*
 * Copyright 2021 The Closure Compiler Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Ported from Closure Compiler (https://github.com/google/closure-compiler), commit bb8c8e7:
//   src/com/google/javascript/jscomp/serialization/ColorSerializer.java.

//! Port of serialization/ColorSerializer.java.
use super::serialization_options::SerializationOptions;
use super::type_pointers::{OFFSET_TO_AXIOMATIC_COLOR, TypePointers};
use super::types_proto::{
    ObjectTypeProto, SubtypingEdge, TypePool, TypePoolDebugInfo, TypePoolDebugInfoMismatch,
    TypeProto, UnionTypeProto,
};
use closure_rhino::check_not_null;
use closure_rhino::fx_hash::{IndexMap, IndexSet};
use closure_rhino::js_string::JsString;
use closure_rhino::jscomp_colors::color::Color;
use closure_rhino::jscomp_colors::color_id::ColorId;

/// `Function<Color, ImmutableSet<String>>` of `generateTypePool`.
pub type MismatchSourceRefsFn<'f> = &'f dyn Fn(&Color) -> IndexSet<String>;

/// port: ColorSerializer
///
/// Serializes `Color`s and information about them into a `TypePool`.
///
/// Client code should call `addColor()` for each of the colors it wants to have included in the
/// `TypePool`, then call `generateTypePool()` to get the result.
pub struct ColorSerializer<'a> {
    serialization_mode: SerializationOptions,
    /// Used to find the index at which a `String` will appear in the `StringPoolProto` that will
    /// eventually be serialized with the `TypePool` generated by this `ColorSerializer`.
    get_string_pool_index_fn: Box<dyn FnMut(&JsString) -> i32 + 'a>,
    /// Only property names that pass this predicate will be serialized.
    property_filter: Box<dyn Fn(&JsString) -> bool + 'a>,

    /// Stores the `Integer` values assigned to `Color`s as they are added for serialization, so
    /// they can be looked up and used for references between the output `TypeProto`s.
    color_id_to_type_pointer: IndexMap<ColorId, i32>,

    /// Stores the `Color`s to be serialized in the order they will be serialized.
    ///
    /// This is used as a worklist when the `TypePool` is generated.
    colors_in_serialized_order: Vec<Color>,
}

impl<'a> ColorSerializer<'a> {
    /// Create a ColorSerializer.
    ///
    /// `serialization_mode` determines what parts of the `TypePool` proto to fill in.
    /// `string_pool_index_fn` is used to request an integer index to encode in place of string
    /// value. The `TypePool` generated by this object will use these indices, so a
    /// `StringPoolProto` that contains the actual `String` values needs to be serialized along
    /// with it. Property names for which `property_filter` returns `false` will not be included
    /// in the generated `TypeProto`s.
    // port: ColorSerializer#<init>
    pub fn new(
        serialization_mode: SerializationOptions,
        string_pool_index_fn: impl FnMut(&JsString) -> i32 + 'a,
        property_filter: impl Fn(&JsString) -> bool + 'a,
    ) -> Self {
        let mut this = Self {
            serialization_mode,
            get_string_pool_index_fn: Box::new(string_pool_index_fn),
            property_filter: Box::new(property_filter),
            color_id_to_type_pointer: IndexMap::<_, _>::default(),
            colors_in_serialized_order: Vec::new(),
        };
        // We must pre-populate the type pointers with the few axiomatic colors that won't actually
        // be serialized. These types are required to get the first few offsets in the order they
        // are specified by `TypePointers.OFFSET_TO_AXIOMATIC_COLOR`.
        for color in OFFSET_TO_AXIOMATIC_COLOR.iter() {
            this.add_color(color);
        }
        this
    }

    /// Add a collection of `Color`s to the list of those that must be serialized.
    ///
    /// Returns the list of `Integer`s that will refer to the input `Color`s in the `TypePool` that
    /// this object will create. The order will match the order of the input `Color`s.
    // port: ColorSerializer#addColors
    pub fn add_colors<'c>(&mut self, colors: impl IntoIterator<Item = &'c Color>) -> Vec<i32> {
        let mut builder = Vec::new();
        for color in colors {
            builder.push(self.add_color(color));
        }
        builder
    }

    /// Add `color` to the list of those that must be serialized (if it wasn't already there) and
    /// return the `Integer` value that will refer to it in the `TypePool` that this object will
    /// create.
    // port: ColorSerializer#addColor
    pub fn add_color(&mut self, color: &Color) -> i32 {
        if let Some(&index) = self.color_id_to_type_pointer.get(&color.get_id()) {
            return index;
        }
        let index = self.colors_in_serialized_order.len() as i32;
        self.colors_in_serialized_order.push(color.clone());
        self.color_id_to_type_pointer.insert(color.get_id(), index);
        index
    }

    /// Generate a `TypePool` proto built from the previously added `Color`s and the arguments
    /// supplied to this method.
    ///
    /// `get_disambiguation_supertypes_fn`: given a `Color` return a set of `Color`s it inherits
    /// from. `get_mismatch_source_refs_fn` may be `None` if this `serialization_mode` does not
    /// include debug info. Otherwise, this function must provide a set of all the source reference
    /// strings indicating code locations where the given `Color` encountered a type mismatch.
    // port: ColorSerializer#generateTypePool
    pub fn generate_type_pool(
        &mut self,
        get_disambiguation_supertypes_fn: &dyn Fn(&Color) -> IndexSet<Color>,
        get_mismatch_source_refs_fn: Option<MismatchSourceRefsFn<'_>>,
    ) -> TypePool {
        let mut type_pool_builder = TypePool::new_builder();
        // We use an indexed loop here for 2 reasons.
        // 1. We must skip serialization of the axiomatic colors that start our list of serialized
        //    colors.
        // 2. The logic in the loop may end up adding more colors to the list. It's often hard to
        //    tell what effect changing an iterable will have on an iteration that is in progress.
        let mut i = TypePointers::untrim_offset(0) as usize;
        while i < self.colors_in_serialized_order.len() {
            let color = self.colors_in_serialized_order[i].clone();
            let type_pointer = self.color_id_to_type_pointer[&color.get_id()];
            let type_proto = self.generate_type_proto(&color);
            type_pool_builder.type_.push(type_proto);
            for supertype in get_disambiguation_supertypes_fn(&color).iter() {
                let supertype_pointer = self.add_color(supertype);
                type_pool_builder.disambiguation_edges.push(
                    SubtypingEdge::new_builder()
                        .set_subtype(type_pointer)
                        .set_supertype(supertype_pointer),
                );
            }
            i += 1;
        }

        if self.serialization_mode.include_debug_info() {
            let get_mismatch_source_refs_fn = check_not_null!(get_mismatch_source_refs_fn);
            let debug_info_builder = type_pool_builder
                .debug_info
                .get_or_insert_with(TypePoolDebugInfo::new_builder);

            // Construct a map from source reference string to type pointers,
            // because that's the way the Mismatch protos work.
            // Construct entries only for those colors that we have actually serialized in order to
            // save space.
            let mut src_ref_to_type_pointer_list: IndexMap<String, Vec<i32>> =
                IndexMap::<_, _>::default();
            for color in &self.colors_in_serialized_order {
                let type_pointer = self.color_id_to_type_pointer[&color.get_id()];
                for src_ref in get_mismatch_source_refs_fn(color) {
                    let type_pointer_list =
                        src_ref_to_type_pointer_list.entry(src_ref).or_default();
                    type_pointer_list.push(type_pointer);
                }
            }

            // Now use the map to build the Mismatch protos and put them into the debug info.
            for (key, value) in src_ref_to_type_pointer_list {
                debug_info_builder.mismatch.push(
                    TypePoolDebugInfoMismatch::new_builder()
                        .set_source_ref(key)
                        .add_all_involved_color(value),
                );
            }
        }
        type_pool_builder.build()
    }

    // port: ColorSerializer#generateTypeProto
    fn generate_type_proto(&mut self, color: &Color) -> TypeProto {
        let type_proto_builder = TypeProto::new_builder();
        if color.is_union() {
            let members = self.add_colors(color.get_union_elements().iter());
            type_proto_builder
                .set_union(UnionTypeProto::new_builder().add_all_union_member(members))
        } else {
            let instance_type = self.add_colors(color.get_instance_colors().iter());
            let prototype = self.add_colors(color.get_prototypes().iter());
            let own_property = self.get_own_property_string_pool_offsets(color);
            let object_type_proto_builder = ObjectTypeProto::new_builder()
                .set_is_invalidating(color.is_invalidating())
                .set_uuid(color.get_id().as_byte_string())
                .set_properties_keep_original_name(color.get_properties_keep_original_name())
                .add_all_instance_type(instance_type)
                .add_all_prototype(prototype)
                .set_marked_constructor(color.is_constructor())
                .add_all_own_property(own_property)
                .set_closure_assert(color.is_closure_assert());
            type_proto_builder.set_object(object_type_proto_builder)
        }
        .build()
    }

    // port: ColorSerializer#getOwnPropertyStringPoolOffsets
    fn get_own_property_string_pool_offsets(&mut self, color: &Color) -> Vec<i32> {
        let mut builder = Vec::new();
        for own_property in color.get_own_properties() {
            // The client code may know that some properties are unused in the AST, so there's no
            // need to serialize them.
            if (self.property_filter)(own_property) {
                builder.push((self.get_string_pool_index_fn)(own_property));
            }
        }
        builder
    }
}
