// Generated by corpus/d2/candidates/npm.collect.py for npm:swiper@14.3.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Swiper as e_Swiper,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/swiper@14.3.0/package/swiper.mjs';
globalThis['Swiper'] = e_Swiper;
globalThis['default'] = e_default;
