/*
 * reserved comment block
 * DO NOT REMOVE OR ALTER!
 */
/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Ported from OpenJDK 21 (the src.zip of Temurin-21.0.12.1+1):
//   java.xml/com/sun/org/apache/xerces/internal/util/XMLChar.java.

//! Port of `com.sun.org.apache.xerces.internal.util.XMLChar` (JDK 21), the character
//! classification tables the JDK's XML parser uses. Only the parts the SAX parser of
//! `sax_parser` needs are ported.

use std::sync::OnceLock;

/// Valid characters mask.
pub const MASK_VALID: u8 = 0x01;
/// Space characters mask.
pub const MASK_SPACE: u8 = 0x02;
/// Name start characters mask.
pub const MASK_NAME_START: u8 = 0x04;
/// Name characters mask.
pub const MASK_NAME: u8 = 0x08;
/// Pubid characters mask.
pub const MASK_PUBID: u8 = 0x10;
/// Content characters mask. Special characters are those that can be considered the start of
/// markup, such as '&lt;' and '&amp;'. The various newline characters are considered special as
/// well. All other valid XML characters can be considered content.
pub const MASK_CONTENT: u8 = 0x20;
/// NCName start characters mask.
pub const MASK_NCNAME_START: u8 = 0x40;
/// NCName characters mask.
pub const MASK_NCNAME: u8 = 0x80;

fn fill(chars: &mut [i8], from: usize, to: usize, value: i8) {
    for c in &mut chars[from..to] {
        *c = value;
    }
}

/// Character flags.
// port: XMLChar#<clinit>
fn chars() -> &'static [i8] {
    static CHARS: OnceLock<Vec<i8>> = OnceLock::new();
    CHARS.get_or_init(|| {
        let mut chars = vec![0i8; 1 << 16];
        // Initializing the Character Flag Array
        // Code generated by: XMLCharGenerator.
        chars[9] = 35;
        chars[10] = 19;
        chars[13] = 19;
        chars[32] = 51;
        chars[33] = 49;
        chars[34] = 33;
        fill(&mut chars, 35, 38, 49);
        chars[38] = 1;
        fill(&mut chars, 39, 45, 49);
        fill(&mut chars, 45, 47, -71);
        chars[47] = 49;
        fill(&mut chars, 48, 58, -71);
        chars[58] = 61;
        chars[59] = 49;
        chars[60] = 1;
        chars[61] = 49;
        chars[62] = 33;
        fill(&mut chars, 63, 65, 49);
        fill(&mut chars, 65, 91, -3);
        fill(&mut chars, 91, 93, 33);
        chars[93] = 1;
        chars[94] = 33;
        chars[95] = -3;
        chars[96] = 33;
        fill(&mut chars, 97, 123, -3);
        fill(&mut chars, 123, 183, 33);
        chars[183] = -87;
        fill(&mut chars, 184, 192, 33);
        fill(&mut chars, 192, 215, -19);
        chars[215] = 33;
        fill(&mut chars, 216, 247, -19);
        chars[247] = 33;
        fill(&mut chars, 248, 306, -19);
        fill(&mut chars, 306, 308, 33);
        fill(&mut chars, 308, 319, -19);
        fill(&mut chars, 319, 321, 33);
        fill(&mut chars, 321, 329, -19);
        chars[329] = 33;
        fill(&mut chars, 330, 383, -19);
        chars[383] = 33;
        fill(&mut chars, 384, 452, -19);
        fill(&mut chars, 452, 461, 33);
        fill(&mut chars, 461, 497, -19);
        fill(&mut chars, 497, 500, 33);
        fill(&mut chars, 500, 502, -19);
        fill(&mut chars, 502, 506, 33);
        fill(&mut chars, 506, 536, -19);
        fill(&mut chars, 536, 592, 33);
        fill(&mut chars, 592, 681, -19);
        fill(&mut chars, 681, 699, 33);
        fill(&mut chars, 699, 706, -19);
        fill(&mut chars, 706, 720, 33);
        fill(&mut chars, 720, 722, -87);
        fill(&mut chars, 722, 768, 33);
        fill(&mut chars, 768, 838, -87);
        fill(&mut chars, 838, 864, 33);
        fill(&mut chars, 864, 866, -87);
        fill(&mut chars, 866, 902, 33);
        chars[902] = -19;
        chars[903] = -87;
        fill(&mut chars, 904, 907, -19);
        chars[907] = 33;
        chars[908] = -19;
        chars[909] = 33;
        fill(&mut chars, 910, 930, -19);
        chars[930] = 33;
        fill(&mut chars, 931, 975, -19);
        chars[975] = 33;
        fill(&mut chars, 976, 983, -19);
        fill(&mut chars, 983, 986, 33);
        chars[986] = -19;
        chars[987] = 33;
        chars[988] = -19;
        chars[989] = 33;
        chars[990] = -19;
        chars[991] = 33;
        chars[992] = -19;
        chars[993] = 33;
        fill(&mut chars, 994, 1012, -19);
        fill(&mut chars, 1012, 1025, 33);
        fill(&mut chars, 1025, 1037, -19);
        chars[1037] = 33;
        fill(&mut chars, 1038, 1104, -19);
        chars[1104] = 33;
        fill(&mut chars, 1105, 1117, -19);
        chars[1117] = 33;
        fill(&mut chars, 1118, 1154, -19);
        chars[1154] = 33;
        fill(&mut chars, 1155, 1159, -87);
        fill(&mut chars, 1159, 1168, 33);
        fill(&mut chars, 1168, 1221, -19);
        fill(&mut chars, 1221, 1223, 33);
        fill(&mut chars, 1223, 1225, -19);
        fill(&mut chars, 1225, 1227, 33);
        fill(&mut chars, 1227, 1229, -19);
        fill(&mut chars, 1229, 1232, 33);
        fill(&mut chars, 1232, 1260, -19);
        fill(&mut chars, 1260, 1262, 33);
        fill(&mut chars, 1262, 1270, -19);
        fill(&mut chars, 1270, 1272, 33);
        fill(&mut chars, 1272, 1274, -19);
        fill(&mut chars, 1274, 1329, 33);
        fill(&mut chars, 1329, 1367, -19);
        fill(&mut chars, 1367, 1369, 33);
        chars[1369] = -19;
        fill(&mut chars, 1370, 1377, 33);
        fill(&mut chars, 1377, 1415, -19);
        fill(&mut chars, 1415, 1425, 33);
        fill(&mut chars, 1425, 1442, -87);
        chars[1442] = 33;
        fill(&mut chars, 1443, 1466, -87);
        chars[1466] = 33;
        fill(&mut chars, 1467, 1470, -87);
        chars[1470] = 33;
        chars[1471] = -87;
        chars[1472] = 33;
        fill(&mut chars, 1473, 1475, -87);
        chars[1475] = 33;
        chars[1476] = -87;
        fill(&mut chars, 1477, 1488, 33);
        fill(&mut chars, 1488, 1515, -19);
        fill(&mut chars, 1515, 1520, 33);
        fill(&mut chars, 1520, 1523, -19);
        fill(&mut chars, 1523, 1569, 33);
        fill(&mut chars, 1569, 1595, -19);
        fill(&mut chars, 1595, 1600, 33);
        chars[1600] = -87;
        fill(&mut chars, 1601, 1611, -19);
        fill(&mut chars, 1611, 1619, -87);
        fill(&mut chars, 1619, 1632, 33);
        fill(&mut chars, 1632, 1642, -87);
        fill(&mut chars, 1642, 1648, 33);
        chars[1648] = -87;
        fill(&mut chars, 1649, 1720, -19);
        fill(&mut chars, 1720, 1722, 33);
        fill(&mut chars, 1722, 1727, -19);
        chars[1727] = 33;
        fill(&mut chars, 1728, 1743, -19);
        chars[1743] = 33;
        fill(&mut chars, 1744, 1748, -19);
        chars[1748] = 33;
        chars[1749] = -19;
        fill(&mut chars, 1750, 1765, -87);
        fill(&mut chars, 1765, 1767, -19);
        fill(&mut chars, 1767, 1769, -87);
        chars[1769] = 33;
        fill(&mut chars, 1770, 1774, -87);
        fill(&mut chars, 1774, 1776, 33);
        fill(&mut chars, 1776, 1786, -87);
        fill(&mut chars, 1786, 2305, 33);
        fill(&mut chars, 2305, 2308, -87);
        chars[2308] = 33;
        fill(&mut chars, 2309, 2362, -19);
        fill(&mut chars, 2362, 2364, 33);
        chars[2364] = -87;
        chars[2365] = -19;
        fill(&mut chars, 2366, 2382, -87);
        fill(&mut chars, 2382, 2385, 33);
        fill(&mut chars, 2385, 2389, -87);
        fill(&mut chars, 2389, 2392, 33);
        fill(&mut chars, 2392, 2402, -19);
        fill(&mut chars, 2402, 2404, -87);
        fill(&mut chars, 2404, 2406, 33);
        fill(&mut chars, 2406, 2416, -87);
        fill(&mut chars, 2416, 2433, 33);
        fill(&mut chars, 2433, 2436, -87);
        chars[2436] = 33;
        fill(&mut chars, 2437, 2445, -19);
        fill(&mut chars, 2445, 2447, 33);
        fill(&mut chars, 2447, 2449, -19);
        fill(&mut chars, 2449, 2451, 33);
        fill(&mut chars, 2451, 2473, -19);
        chars[2473] = 33;
        fill(&mut chars, 2474, 2481, -19);
        chars[2481] = 33;
        chars[2482] = -19;
        fill(&mut chars, 2483, 2486, 33);
        fill(&mut chars, 2486, 2490, -19);
        fill(&mut chars, 2490, 2492, 33);
        chars[2492] = -87;
        chars[2493] = 33;
        fill(&mut chars, 2494, 2501, -87);
        fill(&mut chars, 2501, 2503, 33);
        fill(&mut chars, 2503, 2505, -87);
        fill(&mut chars, 2505, 2507, 33);
        fill(&mut chars, 2507, 2510, -87);
        fill(&mut chars, 2510, 2519, 33);
        chars[2519] = -87;
        fill(&mut chars, 2520, 2524, 33);
        fill(&mut chars, 2524, 2526, -19);
        chars[2526] = 33;
        fill(&mut chars, 2527, 2530, -19);
        fill(&mut chars, 2530, 2532, -87);
        fill(&mut chars, 2532, 2534, 33);
        fill(&mut chars, 2534, 2544, -87);
        fill(&mut chars, 2544, 2546, -19);
        fill(&mut chars, 2546, 2562, 33);
        chars[2562] = -87;
        fill(&mut chars, 2563, 2565, 33);
        fill(&mut chars, 2565, 2571, -19);
        fill(&mut chars, 2571, 2575, 33);
        fill(&mut chars, 2575, 2577, -19);
        fill(&mut chars, 2577, 2579, 33);
        fill(&mut chars, 2579, 2601, -19);
        chars[2601] = 33;
        fill(&mut chars, 2602, 2609, -19);
        chars[2609] = 33;
        fill(&mut chars, 2610, 2612, -19);
        chars[2612] = 33;
        fill(&mut chars, 2613, 2615, -19);
        chars[2615] = 33;
        fill(&mut chars, 2616, 2618, -19);
        fill(&mut chars, 2618, 2620, 33);
        chars[2620] = -87;
        chars[2621] = 33;
        fill(&mut chars, 2622, 2627, -87);
        fill(&mut chars, 2627, 2631, 33);
        fill(&mut chars, 2631, 2633, -87);
        fill(&mut chars, 2633, 2635, 33);
        fill(&mut chars, 2635, 2638, -87);
        fill(&mut chars, 2638, 2649, 33);
        fill(&mut chars, 2649, 2653, -19);
        chars[2653] = 33;
        chars[2654] = -19;
        fill(&mut chars, 2655, 2662, 33);
        fill(&mut chars, 2662, 2674, -87);
        fill(&mut chars, 2674, 2677, -19);
        fill(&mut chars, 2677, 2689, 33);
        fill(&mut chars, 2689, 2692, -87);
        chars[2692] = 33;
        fill(&mut chars, 2693, 2700, -19);
        chars[2700] = 33;
        chars[2701] = -19;
        chars[2702] = 33;
        fill(&mut chars, 2703, 2706, -19);
        chars[2706] = 33;
        fill(&mut chars, 2707, 2729, -19);
        chars[2729] = 33;
        fill(&mut chars, 2730, 2737, -19);
        chars[2737] = 33;
        fill(&mut chars, 2738, 2740, -19);
        chars[2740] = 33;
        fill(&mut chars, 2741, 2746, -19);
        fill(&mut chars, 2746, 2748, 33);
        chars[2748] = -87;
        chars[2749] = -19;
        fill(&mut chars, 2750, 2758, -87);
        chars[2758] = 33;
        fill(&mut chars, 2759, 2762, -87);
        chars[2762] = 33;
        fill(&mut chars, 2763, 2766, -87);
        fill(&mut chars, 2766, 2784, 33);
        chars[2784] = -19;
        fill(&mut chars, 2785, 2790, 33);
        fill(&mut chars, 2790, 2800, -87);
        fill(&mut chars, 2800, 2817, 33);
        fill(&mut chars, 2817, 2820, -87);
        chars[2820] = 33;
        fill(&mut chars, 2821, 2829, -19);
        fill(&mut chars, 2829, 2831, 33);
        fill(&mut chars, 2831, 2833, -19);
        fill(&mut chars, 2833, 2835, 33);
        fill(&mut chars, 2835, 2857, -19);
        chars[2857] = 33;
        fill(&mut chars, 2858, 2865, -19);
        chars[2865] = 33;
        fill(&mut chars, 2866, 2868, -19);
        fill(&mut chars, 2868, 2870, 33);
        fill(&mut chars, 2870, 2874, -19);
        fill(&mut chars, 2874, 2876, 33);
        chars[2876] = -87;
        chars[2877] = -19;
        fill(&mut chars, 2878, 2884, -87);
        fill(&mut chars, 2884, 2887, 33);
        fill(&mut chars, 2887, 2889, -87);
        fill(&mut chars, 2889, 2891, 33);
        fill(&mut chars, 2891, 2894, -87);
        fill(&mut chars, 2894, 2902, 33);
        fill(&mut chars, 2902, 2904, -87);
        fill(&mut chars, 2904, 2908, 33);
        fill(&mut chars, 2908, 2910, -19);
        chars[2910] = 33;
        fill(&mut chars, 2911, 2914, -19);
        fill(&mut chars, 2914, 2918, 33);
        fill(&mut chars, 2918, 2928, -87);
        fill(&mut chars, 2928, 2946, 33);
        fill(&mut chars, 2946, 2948, -87);
        chars[2948] = 33;
        fill(&mut chars, 2949, 2955, -19);
        fill(&mut chars, 2955, 2958, 33);
        fill(&mut chars, 2958, 2961, -19);
        chars[2961] = 33;
        fill(&mut chars, 2962, 2966, -19);
        fill(&mut chars, 2966, 2969, 33);
        fill(&mut chars, 2969, 2971, -19);
        chars[2971] = 33;
        chars[2972] = -19;
        chars[2973] = 33;
        fill(&mut chars, 2974, 2976, -19);
        fill(&mut chars, 2976, 2979, 33);
        fill(&mut chars, 2979, 2981, -19);
        fill(&mut chars, 2981, 2984, 33);
        fill(&mut chars, 2984, 2987, -19);
        fill(&mut chars, 2987, 2990, 33);
        fill(&mut chars, 2990, 2998, -19);
        chars[2998] = 33;
        fill(&mut chars, 2999, 3002, -19);
        fill(&mut chars, 3002, 3006, 33);
        fill(&mut chars, 3006, 3011, -87);
        fill(&mut chars, 3011, 3014, 33);
        fill(&mut chars, 3014, 3017, -87);
        chars[3017] = 33;
        fill(&mut chars, 3018, 3022, -87);
        fill(&mut chars, 3022, 3031, 33);
        chars[3031] = -87;
        fill(&mut chars, 3032, 3047, 33);
        fill(&mut chars, 3047, 3056, -87);
        fill(&mut chars, 3056, 3073, 33);
        fill(&mut chars, 3073, 3076, -87);
        chars[3076] = 33;
        fill(&mut chars, 3077, 3085, -19);
        chars[3085] = 33;
        fill(&mut chars, 3086, 3089, -19);
        chars[3089] = 33;
        fill(&mut chars, 3090, 3113, -19);
        chars[3113] = 33;
        fill(&mut chars, 3114, 3124, -19);
        chars[3124] = 33;
        fill(&mut chars, 3125, 3130, -19);
        fill(&mut chars, 3130, 3134, 33);
        fill(&mut chars, 3134, 3141, -87);
        chars[3141] = 33;
        fill(&mut chars, 3142, 3145, -87);
        chars[3145] = 33;
        fill(&mut chars, 3146, 3150, -87);
        fill(&mut chars, 3150, 3157, 33);
        fill(&mut chars, 3157, 3159, -87);
        fill(&mut chars, 3159, 3168, 33);
        fill(&mut chars, 3168, 3170, -19);
        fill(&mut chars, 3170, 3174, 33);
        fill(&mut chars, 3174, 3184, -87);
        fill(&mut chars, 3184, 3202, 33);
        fill(&mut chars, 3202, 3204, -87);
        chars[3204] = 33;
        fill(&mut chars, 3205, 3213, -19);
        chars[3213] = 33;
        fill(&mut chars, 3214, 3217, -19);
        chars[3217] = 33;
        fill(&mut chars, 3218, 3241, -19);
        chars[3241] = 33;
        fill(&mut chars, 3242, 3252, -19);
        chars[3252] = 33;
        fill(&mut chars, 3253, 3258, -19);
        fill(&mut chars, 3258, 3262, 33);
        fill(&mut chars, 3262, 3269, -87);
        chars[3269] = 33;
        fill(&mut chars, 3270, 3273, -87);
        chars[3273] = 33;
        fill(&mut chars, 3274, 3278, -87);
        fill(&mut chars, 3278, 3285, 33);
        fill(&mut chars, 3285, 3287, -87);
        fill(&mut chars, 3287, 3294, 33);
        chars[3294] = -19;
        chars[3295] = 33;
        fill(&mut chars, 3296, 3298, -19);
        fill(&mut chars, 3298, 3302, 33);
        fill(&mut chars, 3302, 3312, -87);
        fill(&mut chars, 3312, 3330, 33);
        fill(&mut chars, 3330, 3332, -87);
        chars[3332] = 33;
        fill(&mut chars, 3333, 3341, -19);
        chars[3341] = 33;
        fill(&mut chars, 3342, 3345, -19);
        chars[3345] = 33;
        fill(&mut chars, 3346, 3369, -19);
        chars[3369] = 33;
        fill(&mut chars, 3370, 3386, -19);
        fill(&mut chars, 3386, 3390, 33);
        fill(&mut chars, 3390, 3396, -87);
        fill(&mut chars, 3396, 3398, 33);
        fill(&mut chars, 3398, 3401, -87);
        chars[3401] = 33;
        fill(&mut chars, 3402, 3406, -87);
        fill(&mut chars, 3406, 3415, 33);
        chars[3415] = -87;
        fill(&mut chars, 3416, 3424, 33);
        fill(&mut chars, 3424, 3426, -19);
        fill(&mut chars, 3426, 3430, 33);
        fill(&mut chars, 3430, 3440, -87);
        fill(&mut chars, 3440, 3585, 33);
        fill(&mut chars, 3585, 3631, -19);
        chars[3631] = 33;
        chars[3632] = -19;
        chars[3633] = -87;
        fill(&mut chars, 3634, 3636, -19);
        fill(&mut chars, 3636, 3643, -87);
        fill(&mut chars, 3643, 3648, 33);
        fill(&mut chars, 3648, 3654, -19);
        fill(&mut chars, 3654, 3663, -87);
        chars[3663] = 33;
        fill(&mut chars, 3664, 3674, -87);
        fill(&mut chars, 3674, 3713, 33);
        fill(&mut chars, 3713, 3715, -19);
        chars[3715] = 33;
        chars[3716] = -19;
        fill(&mut chars, 3717, 3719, 33);
        fill(&mut chars, 3719, 3721, -19);
        chars[3721] = 33;
        chars[3722] = -19;
        fill(&mut chars, 3723, 3725, 33);
        chars[3725] = -19;
        fill(&mut chars, 3726, 3732, 33);
        fill(&mut chars, 3732, 3736, -19);
        chars[3736] = 33;
        fill(&mut chars, 3737, 3744, -19);
        chars[3744] = 33;
        fill(&mut chars, 3745, 3748, -19);
        chars[3748] = 33;
        chars[3749] = -19;
        chars[3750] = 33;
        chars[3751] = -19;
        fill(&mut chars, 3752, 3754, 33);
        fill(&mut chars, 3754, 3756, -19);
        chars[3756] = 33;
        fill(&mut chars, 3757, 3759, -19);
        chars[3759] = 33;
        chars[3760] = -19;
        chars[3761] = -87;
        fill(&mut chars, 3762, 3764, -19);
        fill(&mut chars, 3764, 3770, -87);
        chars[3770] = 33;
        fill(&mut chars, 3771, 3773, -87);
        chars[3773] = -19;
        fill(&mut chars, 3774, 3776, 33);
        fill(&mut chars, 3776, 3781, -19);
        chars[3781] = 33;
        chars[3782] = -87;
        chars[3783] = 33;
        fill(&mut chars, 3784, 3790, -87);
        fill(&mut chars, 3790, 3792, 33);
        fill(&mut chars, 3792, 3802, -87);
        fill(&mut chars, 3802, 3864, 33);
        fill(&mut chars, 3864, 3866, -87);
        fill(&mut chars, 3866, 3872, 33);
        fill(&mut chars, 3872, 3882, -87);
        fill(&mut chars, 3882, 3893, 33);
        chars[3893] = -87;
        chars[3894] = 33;
        chars[3895] = -87;
        chars[3896] = 33;
        chars[3897] = -87;
        fill(&mut chars, 3898, 3902, 33);
        fill(&mut chars, 3902, 3904, -87);
        fill(&mut chars, 3904, 3912, -19);
        chars[3912] = 33;
        fill(&mut chars, 3913, 3946, -19);
        fill(&mut chars, 3946, 3953, 33);
        fill(&mut chars, 3953, 3973, -87);
        chars[3973] = 33;
        fill(&mut chars, 3974, 3980, -87);
        fill(&mut chars, 3980, 3984, 33);
        fill(&mut chars, 3984, 3990, -87);
        chars[3990] = 33;
        chars[3991] = -87;
        chars[3992] = 33;
        fill(&mut chars, 3993, 4014, -87);
        fill(&mut chars, 4014, 4017, 33);
        fill(&mut chars, 4017, 4024, -87);
        chars[4024] = 33;
        chars[4025] = -87;
        fill(&mut chars, 4026, 4256, 33);
        fill(&mut chars, 4256, 4294, -19);
        fill(&mut chars, 4294, 4304, 33);
        fill(&mut chars, 4304, 4343, -19);
        fill(&mut chars, 4343, 4352, 33);
        chars[4352] = -19;
        chars[4353] = 33;
        fill(&mut chars, 4354, 4356, -19);
        chars[4356] = 33;
        fill(&mut chars, 4357, 4360, -19);
        chars[4360] = 33;
        chars[4361] = -19;
        chars[4362] = 33;
        fill(&mut chars, 4363, 4365, -19);
        chars[4365] = 33;
        fill(&mut chars, 4366, 4371, -19);
        fill(&mut chars, 4371, 4412, 33);
        chars[4412] = -19;
        chars[4413] = 33;
        chars[4414] = -19;
        chars[4415] = 33;
        chars[4416] = -19;
        fill(&mut chars, 4417, 4428, 33);
        chars[4428] = -19;
        chars[4429] = 33;
        chars[4430] = -19;
        chars[4431] = 33;
        chars[4432] = -19;
        fill(&mut chars, 4433, 4436, 33);
        fill(&mut chars, 4436, 4438, -19);
        fill(&mut chars, 4438, 4441, 33);
        chars[4441] = -19;
        fill(&mut chars, 4442, 4447, 33);
        fill(&mut chars, 4447, 4450, -19);
        chars[4450] = 33;
        chars[4451] = -19;
        chars[4452] = 33;
        chars[4453] = -19;
        chars[4454] = 33;
        chars[4455] = -19;
        chars[4456] = 33;
        chars[4457] = -19;
        fill(&mut chars, 4458, 4461, 33);
        fill(&mut chars, 4461, 4463, -19);
        fill(&mut chars, 4463, 4466, 33);
        fill(&mut chars, 4466, 4468, -19);
        chars[4468] = 33;
        chars[4469] = -19;
        fill(&mut chars, 4470, 4510, 33);
        chars[4510] = -19;
        fill(&mut chars, 4511, 4520, 33);
        chars[4520] = -19;
        fill(&mut chars, 4521, 4523, 33);
        chars[4523] = -19;
        fill(&mut chars, 4524, 4526, 33);
        fill(&mut chars, 4526, 4528, -19);
        fill(&mut chars, 4528, 4535, 33);
        fill(&mut chars, 4535, 4537, -19);
        chars[4537] = 33;
        chars[4538] = -19;
        chars[4539] = 33;
        fill(&mut chars, 4540, 4547, -19);
        fill(&mut chars, 4547, 4587, 33);
        chars[4587] = -19;
        fill(&mut chars, 4588, 4592, 33);
        chars[4592] = -19;
        fill(&mut chars, 4593, 4601, 33);
        chars[4601] = -19;
        fill(&mut chars, 4602, 7680, 33);
        fill(&mut chars, 7680, 7836, -19);
        fill(&mut chars, 7836, 7840, 33);
        fill(&mut chars, 7840, 7930, -19);
        fill(&mut chars, 7930, 7936, 33);
        fill(&mut chars, 7936, 7958, -19);
        fill(&mut chars, 7958, 7960, 33);
        fill(&mut chars, 7960, 7966, -19);
        fill(&mut chars, 7966, 7968, 33);
        fill(&mut chars, 7968, 8006, -19);
        fill(&mut chars, 8006, 8008, 33);
        fill(&mut chars, 8008, 8014, -19);
        fill(&mut chars, 8014, 8016, 33);
        fill(&mut chars, 8016, 8024, -19);
        chars[8024] = 33;
        chars[8025] = -19;
        chars[8026] = 33;
        chars[8027] = -19;
        chars[8028] = 33;
        chars[8029] = -19;
        chars[8030] = 33;
        fill(&mut chars, 8031, 8062, -19);
        fill(&mut chars, 8062, 8064, 33);
        fill(&mut chars, 8064, 8117, -19);
        chars[8117] = 33;
        fill(&mut chars, 8118, 8125, -19);
        chars[8125] = 33;
        chars[8126] = -19;
        fill(&mut chars, 8127, 8130, 33);
        fill(&mut chars, 8130, 8133, -19);
        chars[8133] = 33;
        fill(&mut chars, 8134, 8141, -19);
        fill(&mut chars, 8141, 8144, 33);
        fill(&mut chars, 8144, 8148, -19);
        fill(&mut chars, 8148, 8150, 33);
        fill(&mut chars, 8150, 8156, -19);
        fill(&mut chars, 8156, 8160, 33);
        fill(&mut chars, 8160, 8173, -19);
        fill(&mut chars, 8173, 8178, 33);
        fill(&mut chars, 8178, 8181, -19);
        chars[8181] = 33;
        fill(&mut chars, 8182, 8189, -19);
        fill(&mut chars, 8189, 8400, 33);
        fill(&mut chars, 8400, 8413, -87);
        fill(&mut chars, 8413, 8417, 33);
        chars[8417] = -87;
        fill(&mut chars, 8418, 8486, 33);
        chars[8486] = -19;
        fill(&mut chars, 8487, 8490, 33);
        fill(&mut chars, 8490, 8492, -19);
        fill(&mut chars, 8492, 8494, 33);
        chars[8494] = -19;
        fill(&mut chars, 8495, 8576, 33);
        fill(&mut chars, 8576, 8579, -19);
        fill(&mut chars, 8579, 12293, 33);
        chars[12293] = -87;
        chars[12294] = 33;
        chars[12295] = -19;
        fill(&mut chars, 12296, 12321, 33);
        fill(&mut chars, 12321, 12330, -19);
        fill(&mut chars, 12330, 12336, -87);
        chars[12336] = 33;
        fill(&mut chars, 12337, 12342, -87);
        fill(&mut chars, 12342, 12353, 33);
        fill(&mut chars, 12353, 12437, -19);
        fill(&mut chars, 12437, 12441, 33);
        fill(&mut chars, 12441, 12443, -87);
        fill(&mut chars, 12443, 12445, 33);
        fill(&mut chars, 12445, 12447, -87);
        fill(&mut chars, 12447, 12449, 33);
        fill(&mut chars, 12449, 12539, -19);
        chars[12539] = 33;
        fill(&mut chars, 12540, 12543, -87);
        fill(&mut chars, 12543, 12549, 33);
        fill(&mut chars, 12549, 12589, -19);
        fill(&mut chars, 12589, 19968, 33);
        fill(&mut chars, 19968, 40870, -19);
        fill(&mut chars, 40870, 44032, 33);
        fill(&mut chars, 44032, 55204, -19);
        fill(&mut chars, 55204, 55296, 33);
        fill(&mut chars, 57344, 65534, 33);
        chars
    })
}

fn flags(c: i32) -> u8 {
    chars()[c as usize] as u8
}

/// Returns true if the specified character is a supplemental character.
// port: XMLChar#isSupplemental
pub fn is_supplemental(c: i32) -> bool {
    (0x10000..=0x10FFFF).contains(&c)
}

/// Returns true the supplemental character corresponding to the given surrogates.
// port: XMLChar#supplemental
pub fn supplemental(h: u16, l: u16) -> i32 {
    (h as i32 - 0xD800) * 0x400 + (l as i32 - 0xDC00) + 0x10000
}

/// Returns whether the given character is a high surrogate.
// port: XMLChar#isHighSurrogate
pub fn is_high_surrogate(c: i32) -> bool {
    (0xD800..=0xDBFF).contains(&c)
}

/// Returns whether the given character is a low surrogate.
// port: XMLChar#isLowSurrogate
pub fn is_low_surrogate(c: i32) -> bool {
    (0xDC00..=0xDFFF).contains(&c)
}

/// Returns true if the specified character is valid. This method also checks the surrogate
/// character range from 0x10000 to 0x10FFFF.
// port: XMLChar#isValid
pub fn is_valid(c: i32) -> bool {
    (0..0x10000).contains(&c) && (flags(c) & MASK_VALID) != 0 || (0x10000..=0x10FFFF).contains(&c)
}

/// Returns true if the specified character is invalid.
// port: XMLChar#isInvalid
pub fn is_invalid(c: i32) -> bool {
    !is_valid(c)
}

/// Returns true if the specified character can be considered content.
// port: XMLChar#isContent
pub fn is_content(c: i32) -> bool {
    (0..0x10000).contains(&c) && (flags(c) & MASK_CONTENT) != 0 || (0x10000..=0x10FFFF).contains(&c)
}

/// Returns true if the specified character is a space character as defined by production [3]
/// in the XML 1.0 specification.
// port: XMLChar#isSpace
pub fn is_space(c: i32) -> bool {
    (0..=0x20).contains(&c) && (flags(c) & MASK_SPACE) != 0
}

/// Returns true if the specified character is a valid name start character as defined by
/// production [5] in the XML 1.0 specification.
// port: XMLChar#isNameStart
pub fn is_name_start(c: i32) -> bool {
    (0..0x10000).contains(&c) && (flags(c) & MASK_NAME_START) != 0
}

/// Returns true if the specified character is a valid name character as defined by production
/// [4] in the XML 1.0 specification.
// port: XMLChar#isName
pub fn is_name(c: i32) -> bool {
    (0..0x10000).contains(&c) && (flags(c) & MASK_NAME) != 0
}

/// Returns true if the specified character is a valid Pubid character as defined by production
/// [13] in the XML 1.0 specification.
// port: XMLChar#isPubid
pub fn is_pubid(c: i32) -> bool {
    (0..0x10000).contains(&c) && (flags(c) & MASK_PUBID) != 0
}
