// Generated by corpus/d2/candidates/npm.collect.py for npm:@preact/signals-core@1.14.4 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Computed as e_Computed,
  Effect as e_Effect,
  Signal as e_Signal,
  action as e_action,
  batch as e_batch,
  computed as e_computed,
  createModel as e_createModel,
  effect as e_effect,
  signal as e_signal,
  untracked as e_untracked,
} from '../../../../corpus-cache/d2/npm/@preact/signals-core@1.14.4/package/dist/signals-core.module.js';
globalThis['Computed'] = e_Computed;
globalThis['Effect'] = e_Effect;
globalThis['Signal'] = e_Signal;
globalThis['action'] = e_action;
globalThis['batch'] = e_batch;
globalThis['computed'] = e_computed;
globalThis['createModel'] = e_createModel;
globalThis['effect'] = e_effect;
globalThis['signal'] = e_signal;
globalThis['untracked'] = e_untracked;
