/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.string.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/string/string.js).
 * Requires goog.string and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_string');

const target = goog.require('goog.string');

goog.exportSymbol('goog.string.Unicode', target.Unicode);
goog.exportSymbol('goog.string.startsWith', target.startsWith);
goog.exportSymbol('goog.string.endsWith', target.endsWith);
goog.exportSymbol('goog.string.caseInsensitiveStartsWith', target.caseInsensitiveStartsWith);
goog.exportSymbol('goog.string.caseInsensitiveEndsWith', target.caseInsensitiveEndsWith);
goog.exportSymbol('goog.string.caseInsensitiveEquals', target.caseInsensitiveEquals);
goog.exportSymbol('goog.string.subs', target.subs);
goog.exportSymbol('goog.string.collapseWhitespace', target.collapseWhitespace);
