/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/mediakeys.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!MediaKeySystemAccess} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeySystemAccess(obj) {
  return [
    obj.keySystem,
    obj.createMediaKeys(),
    obj.getConfiguration()
  ];
}
globalThis['closureSelfUseMediaKeySystemAccess'] = closureSelfUseMediaKeySystemAccess;

/**
 * @param {!MediaKeys} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeys(obj) {
  return [
    obj.setServerCertificate,
    obj.createSession(),
    obj.getStatusForPolicy()
  ];
}
globalThis['closureSelfUseMediaKeys'] = closureSelfUseMediaKeys;

/**
 * @param {!MediaKeyStatusMap} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeyStatusMap(obj) {
  return [
    obj.size,
    obj.forEach,
    obj.get,
    obj.has,
    obj.keys,
    obj.entries(),
    obj.values()
  ];
}
globalThis['closureSelfUseMediaKeyStatusMap'] = closureSelfUseMediaKeyStatusMap;

/**
 * @param {!MediaKeySession} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeySession(obj) {
  return [
    obj.sessionId,
    obj.closed,
    obj.generateRequest,
    obj.close,
    obj.removeEventListener,
    obj.onkeystatuseschange,
    obj.load('closure-self'),
    obj.remove()
  ];
}
globalThis['closureSelfUseMediaKeySession'] = closureSelfUseMediaKeySession;

/**
 * @param {!MediaKeyMessageEventInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeyMessageEventInit(obj) {
  return [
    obj.messageType,
    obj.message
  ];
}
globalThis['closureSelfUseMediaKeyMessageEventInit'] = closureSelfUseMediaKeyMessageEventInit;

/**
 * @param {!MediaKeyMessageEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaKeyMessageEvent(obj) {
  return [
    obj.messageType,
    obj.message,
    obj.target
  ];
}
globalThis['closureSelfUseMediaKeyMessageEvent'] = closureSelfUseMediaKeyMessageEvent;

/**
 * @param {!MediaEncryptedEventInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaEncryptedEventInit(obj) {
  return [
    obj.initDataType,
    obj.initData
  ];
}
globalThis['closureSelfUseMediaEncryptedEventInit'] = closureSelfUseMediaEncryptedEventInit;

/**
 * @param {!MediaEncryptedEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseMediaEncryptedEvent(obj) {
  return [
    obj.initDataType,
    obj.initData,
    obj.target
  ];
}
globalThis['closureSelfUseMediaEncryptedEvent'] = closureSelfUseMediaEncryptedEvent;

/**
 * @param {!Navigator} obj
 * @return {!Array<*>}
 */
function closureSelfUseNavigator(obj) {
  return [
    obj.requestMediaKeySystemAccess
  ];
}
globalThis['closureSelfUseNavigator'] = closureSelfUseNavigator;

/**
 * @param {!HTMLMediaElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLMediaElement(obj) {
  return [
    obj.mediaKeys,
    obj.setMediaKeys
  ];
}
globalThis['closureSelfUseHTMLMediaElement'] = closureSelfUseHTMLMediaElement;

/**
 * @param {!MediaKeySystemMediaCapability} t0
 * @param {!MediaKeySystemConfiguration} t1
 * @param {!MediaKeyPolicy} t2
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2) {
  return [
    t0,
    t1,
    t2
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
