/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.component.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/component.js).
 * Requires goog.ui.Component and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_Component');

const target = goog.require('goog.ui.Component');

goog.exportSymbol('goog.ui.Component', target);
goog.exportSymbol('goog.ui.Component.EventType', target.EventType);
goog.exportSymbol('goog.ui.Component.Error', target.Error);
goog.exportSymbol('goog.ui.Component.State', target.State);
goog.exportSymbol('goog.ui.Component.getStateTransitionEvent', target.getStateTransitionEvent);
goog.exportSymbol('goog.ui.Component.setDefaultRightToLeft', target.setDefaultRightToLeft);
goog.exportProperty(target.prototype, 'getId', target.prototype.getId);
goog.exportProperty(target.prototype, 'setId', target.prototype.setId);
goog.exportProperty(target.prototype, 'getElement', target.prototype.getElement);
goog.exportProperty(target.prototype, 'getElementStrict', target.prototype.getElementStrict);
