/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.graphics.svggraphics.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/graphics/svggraphics.js).
 * Requires goog.graphics.SvgGraphics and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_graphics_SvgGraphics');

const target = goog.require('goog.graphics.SvgGraphics');

goog.exportSymbol('goog.graphics.SvgGraphics.getSvgPath', target.getSvgPath);
