/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.editor.command.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/editor/command.js).
 * Requires goog.editor.Command and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_editor_Command');

const target = goog.require('goog.editor.Command');

goog.exportSymbol('goog.editor.Command', target);
