/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/wicg_file_handling.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!LaunchParams} obj
 * @return {!Array<*>}
 */
function closureSelfUseLaunchParams(obj) {
  return [
    obj.files
  ];
}
globalThis['closureSelfUseLaunchParams'] = closureSelfUseLaunchParams;

/**
 * @param {!LaunchQueue} obj
 * @return {!Array<*>}
 */
function closureSelfUseLaunchQueue(obj) {
  return [
    obj.setConsumer
  ];
}
globalThis['closureSelfUseLaunchQueue'] = closureSelfUseLaunchQueue;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    window.launchQueue
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!LaunchConsumer} t0
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0) {
  return [
    t0
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
