// Generated by corpus/d2/candidates/npm.collect.py for npm:idb@8.0.4 (ISC).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  deleteDB as e_deleteDB,
  openDB as e_openDB,
  unwrap as e_unwrap,
  wrap as e_wrap,
} from '../../../../corpus-cache/d2/npm/idb@8.0.4/package/build/index.js';
globalThis['deleteDB'] = e_deleteDB;
globalThis['openDB'] = e_openDB;
globalThis['unwrap'] = e_unwrap;
globalThis['wrap'] = e_wrap;
