// Generated by corpus/d2/candidates/npm.collect.py for npm:dexie@4.4.6 (Apache-2.0).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/dexie@4.4.6/package/dist/dexie.js');
globalThis['dexie'] = pkg;
