/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-dexie-4.4.6-pkg-cjs:
 * Node.js/AMD globals referenced by npm:dexie@4.4.6 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
