/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.date.utcdatetime.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/date/utcdatetime.js).
 * Requires goog.date.UtcDateTime and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_date_UtcDateTime');

const target = goog.require('goog.date.UtcDateTime');

goog.exportSymbol('goog.date.UtcDateTime', target);
goog.exportSymbol('goog.date.UtcDateTime.fromTimestamp', target.fromTimestamp);
goog.exportSymbol('goog.date.UtcDateTime.fromIsoString', target.fromIsoString);
goog.exportProperty(target.prototype, 'clone', target.prototype.clone);
goog.exportProperty(target.prototype, 'add', target.prototype.add);
goog.exportProperty(target.prototype, 'getTimezoneOffset', target.prototype.getTimezoneOffset);
goog.exportProperty(target.prototype, 'getFullYear', target.prototype.getFullYear);
