/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.datepicker.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/datepicker.js).
 * Requires goog.ui.DatePicker and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_DatePicker');

const target = goog.require('goog.ui.DatePicker');

goog.exportSymbol('goog.ui.DatePicker', target);
goog.exportSymbol('goog.ui.DatePicker.Events', target.Events);
goog.exportProperty(target.prototype, 'getFirstWeekday', target.prototype.getFirstWeekday);
goog.exportProperty(target.prototype, 'getWeekdayClass', target.prototype.getWeekdayClass);
goog.exportProperty(target.prototype, 'getShowFixedNumWeeks', target.prototype.getShowFixedNumWeeks);
goog.exportProperty(target.prototype, 'getShowOtherMonths', target.prototype.getShowOtherMonths);
