/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.net.xhrio.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/net/xhrio.js).
 * Requires goog.net.XhrIo and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_net_XhrIo');

const target = goog.require('goog.net.XhrIo');

goog.exportSymbol('goog.net.XhrIo', target);
goog.exportSymbol('goog.net.XhrIo.ResponseType', target.ResponseType);
goog.exportSymbol('goog.net.XhrIo.CONTENT_TYPE_HEADER', target.CONTENT_TYPE_HEADER);
goog.exportSymbol('goog.net.XhrIo.CONTENT_TRANSFER_ENCODING', target.CONTENT_TRANSFER_ENCODING);
goog.exportSymbol('goog.net.XhrIo.HTTP_SCHEME_PATTERN', target.HTTP_SCHEME_PATTERN);
goog.exportSymbol('goog.net.XhrIo.METHODS_WITH_FORM_DATA', target.METHODS_WITH_FORM_DATA);
goog.exportSymbol('goog.net.XhrIo.FORM_CONTENT_TYPE', target.FORM_CONTENT_TYPE);
goog.exportSymbol('goog.net.XhrIo.send', target.send);
goog.exportSymbol('goog.net.XhrIo.cleanup', target.cleanup);
goog.exportProperty(target.prototype, 'getTimeoutInterval', target.prototype.getTimeoutInterval);
goog.exportProperty(target.prototype, 'setTimeoutInterval', target.prototype.setTimeoutInterval);
goog.exportProperty(target.prototype, 'setResponseType', target.prototype.setResponseType);
goog.exportProperty(target.prototype, 'getResponseType', target.prototype.getResponseType);
