/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.html.sanitizer.unsafe.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/html/sanitizer/unsafe.js).
 * Requires goog.html.sanitizer.unsafe and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_html_sanitizer_unsafe');

const target = goog.require('goog.html.sanitizer.unsafe');

goog.exportSymbol('goog.html.sanitizer.unsafe.alsoAllowTags', target.alsoAllowTags);
goog.exportSymbol('goog.html.sanitizer.unsafe.alsoAllowAttributes', target.alsoAllowAttributes);
