/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/web_animations.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!AnimationPlaybackEventInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseAnimationPlaybackEventInit(obj) {
  return [
    obj.currentTime,
    obj.timelineTime
  ];
}
globalThis['closureSelfUseAnimationPlaybackEventInit'] = closureSelfUseAnimationPlaybackEventInit;

/**
 * @param {!Animation} obj
 * @return {!Array<*>}
 */
function closureSelfUseAnimation(obj) {
  return [
    obj.addEventListener,
    obj.pause,
    obj.currentTime,
    obj.onfinish,
    obj.playbackRate,
    obj.timeline,
    obj.cancel(),
    obj.updatePlaybackRate(1)
  ];
}
globalThis['closureSelfUseAnimation'] = closureSelfUseAnimation;

/**
 * @param {!KeyframeEffect} obj
 * @return {!Array<*>}
 */
function closureSelfUseKeyframeEffect(obj) {
  return [
    obj.setKeyframes,
    obj.getKeyframes()
  ];
}
globalThis['closureSelfUseKeyframeEffect'] = closureSelfUseKeyframeEffect;

/**
 * @param {!PropertyIndexedKeyframes} obj
 * @return {!Array<*>}
 */
function closureSelfUsePropertyIndexedKeyframes(obj) {
  return [
    obj.composite,
    obj.easing,
    obj.offset
  ];
}
globalThis['closureSelfUsePropertyIndexedKeyframes'] = closureSelfUsePropertyIndexedKeyframes;

/**
 * @param {!AnimationEffectTimingProperties} obj
 * @return {!Array<*>}
 */
function closureSelfUseAnimationEffectTimingProperties(obj) {
  return [
    obj.delay,
    obj.endDelay,
    obj.iterationStart,
    obj.iterations,
    obj.direction,
    obj.easing
  ];
}
globalThis['closureSelfUseAnimationEffectTimingProperties'] = closureSelfUseAnimationEffectTimingProperties;

/**
 * @param {!ComputedTimingProperties} obj
 * @return {!Array<*>}
 */
function closureSelfUseComputedTimingProperties(obj) {
  return [
    obj.endTime,
    obj.activeDuration,
    obj.localTime,
    obj.progress,
    obj.currentIteration
  ];
}
globalThis['closureSelfUseComputedTimingProperties'] = closureSelfUseComputedTimingProperties;

/**
 * @param {!AnimationTimeline} obj
 * @return {!Array<*>}
 */
function closureSelfUseAnimationTimeline(obj) {
  return [
    obj.currentTime,
    obj.duration
  ];
}
globalThis['closureSelfUseAnimationTimeline'] = closureSelfUseAnimationTimeline;

/**
 * @param {!TimelineRangeOffset} obj
 * @return {!Array<*>}
 */
function closureSelfUseTimelineRangeOffset(obj) {
  return [
    obj.offset,
    obj.rangeName
  ];
}
globalThis['closureSelfUseTimelineRangeOffset'] = closureSelfUseTimelineRangeOffset;

/**
 * @param {!ViewTimeline} obj
 * @return {!Array<*>}
 */
function closureSelfUseViewTimeline(obj) {
  return [
    obj.endOffset,
    obj.startOffset,
    obj.subject,
    obj.currentTime,
    obj.duration
  ];
}
globalThis['closureSelfUseViewTimeline'] = closureSelfUseViewTimeline;

/**
 * @param {!SequenceEffect} obj
 * @return {!Array<*>}
 */
function closureSelfUseSequenceEffect(obj) {
  return [
    obj.updateTiming,
    obj.timing,
    obj.children,
    obj.getTiming(),
    obj.getComputedTiming()
  ];
}
globalThis['closureSelfUseSequenceEffect'] = closureSelfUseSequenceEffect;

/**
 * @param {!Element} obj
 * @return {!Array<*>}
 */
function closureSelfUseElement(obj) {
  return [
    obj.animate,
    obj.getAnimations()
  ];
}
globalThis['closureSelfUseElement'] = closureSelfUseElement;

/**
 * @param {!ShadowRoot} obj
 * @return {!Array<*>}
 */
function closureSelfUseShadowRoot(obj) {
  return [
    obj.getAnimations()
  ];
}
globalThis['closureSelfUseShadowRoot'] = closureSelfUseShadowRoot;

/**
 * @param {!ScrollAxis} t0
 * @param {!DocumentTimelineOptions} t1
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1) {
  return [
    t0,
    t1
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
