/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.events.keyhandler.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/events/keyhandler.js).
 * Requires goog.events.KeyHandler and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_events_KeyHandler');

const target = goog.require('goog.events.KeyHandler');

goog.exportSymbol('goog.events.KeyHandler', target);
goog.exportProperty(target.prototype, 'resetState', target.prototype.resetState);
goog.exportProperty(target.prototype, 'handleEvent', target.prototype.handleEvent);
goog.exportProperty(target.prototype, 'getElement', target.prototype.getElement);
goog.exportProperty(target.prototype, 'attach', target.prototype.attach);
