// Generated by corpus/d2/candidates/npm.collect.py for npm:tiny-invariant@1.3.3 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/tiny-invariant@1.3.3/package/dist/esm/tiny-invariant.js';
globalThis['default'] = e_default;
