// Generated by corpus/d2/candidates/npm.collect.py for npm:compute-scroll-into-view@3.1.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  compute as e_compute,
} from '../../../../corpus-cache/d2/npm/compute-scroll-into-view@3.1.1/package/dist/index.js';
globalThis['compute'] = e_compute;
