/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.dom.safe.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/dom/safe.js).
 * Requires goog.dom.safe and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_dom_safe');

const target = goog.require('goog.dom.safe');

goog.exportSymbol('goog.dom.safe.InsertAdjacentHtmlPosition', target.InsertAdjacentHtmlPosition);
goog.exportSymbol('goog.dom.safe.insertAdjacentHtml', target.insertAdjacentHtml);
goog.exportSymbol('goog.dom.safe.unsafeSetInnerHtmlDoNotUseOrElse', target.unsafeSetInnerHtmlDoNotUseOrElse);
goog.exportSymbol('goog.dom.safe.setInnerHtml', target.setInnerHtml);
goog.exportSymbol('goog.dom.safe.setInnerHtmlFromConstant', target.setInnerHtmlFromConstant);
goog.exportSymbol('goog.dom.safe.setOuterHtml', target.setOuterHtml);
goog.exportSymbol('goog.dom.safe.setFormElementAction', target.setFormElementAction);
goog.exportSymbol('goog.dom.safe.setButtonFormAction', target.setButtonFormAction);
