/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.net.xhrio.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/net/xhrio.js).
 * Requires goog.testing.net.XhrIo and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_net_XhrIo');

const target = goog.require('goog.testing.net.XhrIo');

goog.exportSymbol('goog.testing.net.XhrIo', target);
goog.exportSymbol('goog.testing.net.XhrIo.allowUnsafeAccessToXhrIoOutsideCallbacks', target.allowUnsafeAccessToXhrIoOutsideCallbacks);
goog.exportSymbol('goog.testing.net.XhrIo.ResponseType', target.ResponseType);
goog.exportSymbol('goog.testing.net.XhrIo.METHODS_WITH_FORM_DATA', target.METHODS_WITH_FORM_DATA);
goog.exportSymbol('goog.testing.net.XhrIo.getSendInstances', target.getSendInstances);
goog.exportSymbol('goog.testing.net.XhrIo.cleanup', target.cleanup);
goog.exportSymbol('goog.testing.net.XhrIo.send', target.send);
goog.exportProperty(target.prototype, 'getTimeoutInterval', target.prototype.getTimeoutInterval);
goog.exportProperty(target.prototype, 'setTimeoutInterval', target.prototype.setTimeoutInterval);
goog.exportProperty(target.prototype, 'simulateTimeout', target.prototype.simulateTimeout);
goog.exportProperty(target.prototype, 'setResponseType', target.prototype.setResponseType);
