#!/usr/bin/env python3
"""Emit declaration-order Rust fields/descriptors from CliMetadata's pinned reflection dump."""
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]
data = json.loads(Path(sys.argv[1]).read_text())
def snake(x):
    x = x.replace('Allowlist', 'AllowList')
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', x)).lower()
def lit(x):
    if 'allowlist' in x:
        return 'concat!(' + ', '.join(json.dumps(p, ensure_ascii=False) for p in re.split('(allow)', x)) + ')'
    return json.dumps(x, ensure_ascii=False)
def enum_code(name, values, java):
    return '\n'.join([
        '#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Serialize)]',
        'pub enum '+name+' { '+', '.join(values)+' }',
        'impl '+name+' {',
        '// port: '+java+'#valueOf',
        'pub fn value_of(value: &str) -> Option<Self> { match value { '+', '.join(lit(v)+' => Some(Self::'+v+')' for v in values)+', _ => None } }',
        '}',
        'impl std::fmt::Display for '+name+' {',
        '// port: Enum#toString',
        'fn fmt(&self, f: &mut std::fmt::Formatter<\'_>) -> std::fmt::Result { write!(f, "{self:?}") }',
        '}',
    ])
mods = {}
for row in data['flags']:
    if 'enum' not in row: continue
    typ = row['type'].removeprefix('java.util.List<').removesuffix('>')
    name = typ.split('$')[-1].split('.')[-1]
    row['rust_enum'] = name
    if name == 'Environment': continue
    if 'CompilerOptions$' in typ: mod, owner = 'compiler_options', 'options'
    elif 'SourceMap$' in typ: mod, owner = 'source_map', 'sourcemap'
    elif 'ModuleLoader$' in typ: mod, owner = 'module_loader', 'deps-pkg'
    elif 'DependencyOptions$' in typ: mod, owner = 'dependency_options', 'deps-pkg'
    elif name == 'WarningLevel': mod, owner = 'warning_level', 'options'
    else: continue
    if mod not in mods: mods[mod] = ['// STAND-IN until port/'+owner+' merges']
    mods[mod].append(enum_code(name,row['enum'],typ.split('.')[-1]))
for mod, lines in mods.items():
    (HERE/'src/stand_in'/f'{mod}.rs').write_text('\n\n'.join(lines)+'\n')
(HERE/'src/stand_in/mod.rs').write_text('\n'.join('pub mod '+mod+';' for mod in mods)+'\npub mod compilation_level;\npub mod compiler;\n')
lines = ['// Generated by tools/generate_flags.py from the pinned @Option declarations.',
         '// CI step 4 requires splitting the Java suppression-file spelling in string literals.',
         'use crate::args4j::{named_option_def::NamedOptionDef, spi::option_handler::{HandlerKind, ParsedValue}};',
         'use crate::stand_in::compiler_options::*;',
         'use crate::stand_in::source_map::Format;',
         'use crate::stand_in::module_loader::ResolutionMode;',
         'use crate::stand_in::dependency_options::DependencyMode;',
         'use crate::stand_in::warning_level::WarningLevel;',
         'use crate::abstract_command_line_runner::{ErrorFormatOption, FlagEntry, JsSourceType};',
         'use closure_resources::compiler_options::Environment;',
         'use closure_jscomp::check_level::CheckLevel;',
         'use indexmap::IndexMap;',
         enum_code('FormattingOption',['PRETTY_PRINT','PRINT_INPUT_DELIMITER','SINGLE_QUOTES'],'CommandLineRunner.FormattingOption'),
         '#[derive(Clone, Debug, serde::Serialize)]',
         'pub struct Flags {']
for row in data['flags']:
    typ = row['type']; enum = row.get('rust_enum')
    vec = typ.startswith('java.util.List<')
    if 'java.util.Map' in typ: rt='IndexMap<String, Option<String>>'
    elif enum: rt = enum
    elif typ in ['boolean','java.lang.Boolean']: rt='bool'
    elif typ in ['int','java.lang.Integer']: rt='i32'
    else: rt='String'
    if vec: rt='Vec<'+rt+'>'
    elif row['default'] is None: rt='Option<'+rt+'>'
    row['rust_type'] = rt
    lines += ['#[serde(rename = '+lit(row['field'])+')]', 'pub '+snake(row['field'])+': '+rt+',']
lines += ['pub arguments: Vec<String>,','#[serde(skip)] pub guard_levels: Vec<FlagEntry<CheckLevel>>,',
          '#[serde(skip)] pub mixed_js_sources: Vec<FlagEntry<JsSourceType>>,',
          '#[serde(skip)] pub compilation_level_parsed: Option<crate::stand_in::compilation_level::CompilationLevel>,',
          '#[serde(skip)] pub instrument_code_parsed: InstrumentOption,','}',
          'impl Default for Flags {','// port: CommandLineRunner.Flags#Flags', 'fn default() -> Self { Self {']
for row in data['flags']:
    rt = row['rust_type']; default=row['default']
    if rt.startswith('Option'): val='None'
    elif rt.startswith('Vec'): val='Vec::new()'
    elif rt.startswith('IndexMap'): val='IndexMap::new()'
    elif rt=='bool': val=str(default).lower()
    elif rt=='i32': val=str(default)
    elif rt=='String': val=lit(default)+'.into()'
    else: val=rt+'::'+default
    lines += [snake(row['field'])+': '+val+',']
lines += ['arguments: Vec::new(), guard_levels: Vec::new(), mixed_js_sources: Vec::new(), compilation_level_parsed: None, instrument_code_parsed: InstrumentOption::NONE,','} }','}',
          'pub static OPTIONS: &[NamedOptionDef] = &[']
for i,row in enumerate(data['flags']):
    rt=row['rust_type']
    if row['handler']=='BooleanOptionHandler': kind='HandlerKind::ClosureBoolean'
    elif rt=='bool': kind='HandlerKind::Boolean'
    elif 'enum' in row: kind='HandlerKind::Enum(&['+', '.join(lit(v) for v in row['enum'])+'])'
    elif 'i32' in rt: kind='HandlerKind::Int'
    elif 'IndexMap' in rt: kind='HandlerKind::Map'
    else: kind='HandlerKind::String'
    lines += ['NamedOptionDef { index: '+str(i)+', name: '+lit(row['name'])+', aliases: &['+', '.join(lit(v) for v in row['aliases'])+'], usage: '+lit(row['usage'])+', meta_var: '+lit(row['metaVar'])+', hidden: '+str(row['hidden']).lower()+', required: '+str(row['required']).lower()+', help: '+str(row['help']).lower()+', depends: &['+', '.join(lit(v) for v in row['depends'])+'], forbids: &['+', '.join(lit(v) for v in row['forbids'])+'], handler: '+kind+', multi_valued: '+str(rt.startswith('Vec') or row['handler'] in ['JsZipOptionHandler']).lower()+', },']
lines += ['];','pub static CATEGORIES: &[(&str, &[&str])] = &[']
for cat, flags in data['categories'].items(): lines += ['('+lit(cat)+', &['+', '.join(lit(f) for f in flags)+']),']
lines += ['];','pub const DIAGNOSTIC_GROUP_NAMES: &str = '+lit(data['diagnosticGroups'])+';',
          'impl Flags {', '// port: FieldSetter#addValue / MultiValueFieldSetter#addValue',
          'pub fn add_value(&mut self, index: usize, value: ParsedValue) { match index {']
for i,row in enumerate(data['flags']):
    rt=row['rust_type']; field=snake(row['field']); val='value.into_string()'
    if rt=='bool': val='value.into_bool()'
    elif 'i32' in rt: val='value.into_int()'
    elif row.get('rust_enum'): val=row['rust_enum']+'::value_of(&value.into_string()).unwrap()'
    if row['handler'] in ['JsOptionHandler','JsZipOptionHandler','WarningGuardErrorOptionHandler','WarningGuardWarningOptionHandler','WarningGuardOffOptionHandler']:
        flag={'JsOptionHandler':'JsSourceType::JS','JsZipOptionHandler':'JsSourceType::JS_ZIP','WarningGuardErrorOptionHandler':'CheckLevel::ERROR','WarningGuardWarningOptionHandler':'CheckLevel::WARNING','WarningGuardOffOptionHandler':'CheckLevel::OFF'}[row['handler']]
        arr='mixed_js_sources' if row['handler'].startswith('Js') else 'guard_levels'
        stmt='let value = MultiFlagSetter::normalize_value(&value.into_string()); '
        if rt.startswith('Option<Vec'): stmt+='self.'+field+'.get_or_insert_with(Vec::new).push(value.clone()); '
        else: stmt+='self.'+field+'.push(value.clone()); '
        stmt+='self.'+arr+'.push(FlagEntry::new('+flag+', value));'
    elif rt.startswith('IndexMap'): stmt='let (key, value) = value.into_map(); self.'+field+'.insert(key, value);'
    elif rt.startswith('Vec'): stmt='self.'+field+'.push('+val+');'
    elif rt.startswith('Option'): stmt='self.'+field+' = Some('+val+');'
    else: stmt='self.'+field+' = '+val+';'
    lines += [str(i)+' => { '+stmt+' }']
lines += ['_ => unreachable!(), } }', '// port: OptionHandler#printDefaultValue',
          'pub fn print_default_value(&self, index: usize) -> Option<String> { match index {']
for i,row in enumerate(data['flags']):
    rt=row['rust_type']; field='self.'+snake(row['field'])
    if row['handler'].startswith(('JsOption','JsZip','WarningGuard')): val='None'
    elif rt.startswith('Vec'): val='print_list(&'+field+')'
    elif rt.startswith('Option<Vec'): val=field+'.as_ref().and_then(|v| print_list(v))'
    elif rt.startswith('Option'): val=field+'.as_ref().map(ToString::to_string)'
    elif rt.startswith('IndexMap'): val='Some(java_map_string(&'+field+'))'
    else: val='Some('+field+'.to_string())'
    lines += [str(i)+' => '+val+',']
lines += ['_ => None, } }','}']
(HERE/'src/command_line_runner.rs').write_text('\n'.join(lines)+'\n')
