/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.math.integer.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/math/integer.js).
 * Requires goog.math.Integer and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_math_Integer');

const target = goog.require('goog.math.Integer');

goog.exportSymbol('goog.math.Integer', target);
goog.exportSymbol('goog.math.Integer.fromInt', target.fromInt);
goog.exportSymbol('goog.math.Integer.fromNumber', target.fromNumber);
goog.exportSymbol('goog.math.Integer.fromBits', target.fromBits);
goog.exportSymbol('goog.math.Integer.fromString', target.fromString);
goog.exportSymbol('goog.math.Integer.ZERO', target.ZERO);
goog.exportSymbol('goog.math.Integer.ONE', target.ONE);
goog.exportSymbol('goog.math.Integer.DivisionResult', target.DivisionResult);
goog.exportProperty(target.prototype, 'toInt', target.prototype.toInt);
goog.exportProperty(target.prototype, 'toNumber', target.prototype.toNumber);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
goog.exportProperty(target.prototype, 'getBits', target.prototype.getBits);
