/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.debug.console.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/debug/console.js).
 * Requires goog.debug.Console and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_debug_Console');

const target = goog.require('goog.debug.Console');

goog.exportSymbol('goog.debug.Console', target);
goog.exportSymbol('goog.debug.Console.instance', target.instance);
goog.exportSymbol('goog.debug.Console.setConsole', target.setConsole);
goog.exportSymbol('goog.debug.Console.autoInstall', target.autoInstall);
goog.exportSymbol('goog.debug.Console.show', target.show);
goog.exportProperty(target.prototype, 'getFormatter', target.prototype.getFormatter);
goog.exportProperty(target.prototype, 'setCapturing', target.prototype.setCapturing);
goog.exportProperty(target.prototype, 'addLogRecord', target.prototype.addLogRecord);
goog.exportProperty(target.prototype, 'addFilter', target.prototype.addFilter);
