/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/iphone.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!GestureEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseGestureEvent(obj) {
  return [
    obj.scale,
    obj.rotation,
    obj.target,
    obj.initGestureEvent
  ];
}
globalThis['closureSelfUseGestureEvent'] = closureSelfUseGestureEvent;

/**
 * @param {!Touch} obj
 * @return {!Array<*>}
 */
function closureSelfUseTouch(obj) {
  return [
    obj.webkitForce,
    obj.webkitRadiusX,
    obj.webkitRadiusY
  ];
}
globalThis['closureSelfUseTouch'] = closureSelfUseTouch;

/**
 * @param {!TouchEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseTouchEvent(obj) {
  return [
    obj.scale,
    obj.rotation,
    obj.initTouchEvent
  ];
}
globalThis['closureSelfUseTouchEvent'] = closureSelfUseTouchEvent;

/**
 * @param {!Element} obj
 * @return {!Array<*>}
 */
function closureSelfUseElement(obj) {
  return [
    obj.ongesturestart,
    obj.ongesturechange,
    obj.ongestureend
  ];
}
globalThis['closureSelfUseElement'] = closureSelfUseElement;

/**
 * @param {!Window} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindow(obj) {
  return [
    obj.onorientationchange,
    obj.orientation
  ];
}
globalThis['closureSelfUseWindow'] = closureSelfUseWindow;

/**
 * @param {!HTMLInputElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLInputElement(obj) {
  return [
    obj.autocorrect,
    obj.autocapitalize
  ];
}
globalThis['closureSelfUseHTMLInputElement'] = closureSelfUseHTMLInputElement;

/**
 * @param {!HTMLTextAreaElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLTextAreaElement(obj) {
  return [
    obj.autocorrect,
    obj.autocapitalize
  ];
}
globalThis['closureSelfUseHTMLTextAreaElement'] = closureSelfUseHTMLTextAreaElement;
