/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-minimist-1.2.8.
 *
 * The library's own tests run uncompiled against the compiled minimist@1.2.8, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype._;
/** @type {?} */
Object.prototype.alias;
/** @type {?} */
Object.prototype.boolean;
/** @type {?} */
Object.prototype.default;
/** @type {?} */
Object.prototype.length;
/** @type {?} */
Object.prototype.push;
/** @type {?} */
Object.prototype.split;
/** @type {?} */
Object.prototype.stopEarly;
/** @type {?} */
Object.prototype.string;
/** @type {?} */
Object.prototype.strings;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.unknown;
/** @type {?} */
Object.prototype.unknownFn;
