/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.labs.net.webchannel.testing.fakewebchannel.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/net/webchannel/testing/fakewebchannel.js).
 * Requires goog.labs.net.webChannel.testing.FakeWebChannel and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_labs_net_webChannel_testing_FakeWebChannel');

const target = goog.require('goog.labs.net.webChannel.testing.FakeWebChannel');

goog.exportSymbol('goog.labs.net.webChannel.testing.FakeWebChannel.FakeWebChannel', target.FakeWebChannel);
