/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/nonstandard_fileapi.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!BlobBuilder} obj
 * @return {!Array<*>}
 */
function closureSelfUseBlobBuilder(obj) {
  return [
    obj.append,
    obj.getBlob()
  ];
}
globalThis['closureSelfUseBlobBuilder'] = closureSelfUseBlobBuilder;

/**
 * @param {!FileError} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileError(obj) {
  return [
    obj.NOT_FOUND_ERR,
    obj.ABORT_ERR,
    obj.ENCODING_ERR,
    obj.SYNTAX_ERR,
    obj.QUOTA_EXCEEDED_ERR,
    obj.PATH_EXISTS_ERR
  ];
}
globalThis['closureSelfUseFileError'] = closureSelfUseFileError;

/**
 * @param {!FileWriter} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileWriter(obj) {
  return [
    obj.position,
    obj.length,
    obj.write,
    obj.seek(1),
    obj.truncate(1)
  ];
}
globalThis['closureSelfUseFileWriter'] = closureSelfUseFileWriter;

/**
 * @param {!StorageInfo} obj
 * @return {!Array<*>}
 */
function closureSelfUseStorageInfo(obj) {
  return [
    obj.TEMPORARY,
    obj.PERSISTENT,
    obj.requestQuota,
    obj.queryUsageAndQuota
  ];
}
globalThis['closureSelfUseStorageInfo'] = closureSelfUseStorageInfo;

/**
 * @param {!FileWriterSync} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileWriterSync(obj) {
  return [
    obj.position,
    obj.length,
    obj.write,
    obj.seek(1),
    obj.truncate(1)
  ];
}
globalThis['closureSelfUseFileWriterSync'] = closureSelfUseFileWriterSync;

/**
 * @param {!EntrySync} obj
 * @return {!Array<*>}
 */
function closureSelfUseEntrySync(obj) {
  return [
    obj.isFile,
    obj.name,
    obj.fullPath,
    obj.moveTo,
    obj.copyTo,
    obj.getMetadata,
    obj.toURL(),
    obj.getParent()
  ];
}
globalThis['closureSelfUseEntrySync'] = closureSelfUseEntrySync;

/**
 * @param {!DirectoryReaderSync} obj
 * @return {!Array<*>}
 */
function closureSelfUseDirectoryReaderSync(obj) {
  return [
    obj.readEntries()
  ];
}
globalThis['closureSelfUseDirectoryReaderSync'] = closureSelfUseDirectoryReaderSync;

/**
 * @param {!FileException} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileException(obj) {
  return [
    obj.NOT_FOUND_ERR,
    obj.ABORT_ERR,
    obj.NO_MODIFICATION_ALLOWED_ERR,
    obj.SYNTAX_ERR,
    obj.TYPE_MISMATCH_ERR,
    obj.code
  ];
}
globalThis['closureSelfUseFileException'] = closureSelfUseFileException;

/**
 * @param {!FileSystemDirectoryEntry} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemDirectoryEntry(obj) {
  return [
    obj.removeRecursively
  ];
}
globalThis['closureSelfUseFileSystemDirectoryEntry'] = closureSelfUseFileSystemDirectoryEntry;

/**
 * @param {!DataTransferItem} obj
 * @return {!Array<*>}
 */
function closureSelfUseDataTransferItem(obj) {
  return [
    obj.webkitGetAsEntry()
  ];
}
globalThis['closureSelfUseDataTransferItem'] = closureSelfUseDataTransferItem;

/**
 * @param {!FileSystemFileEntry} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemFileEntry(obj) {
  return [
    obj.createWriter
  ];
}
globalThis['closureSelfUseFileSystemFileEntry'] = closureSelfUseFileSystemFileEntry;

/**
 * @param {!Navigator} obj
 * @return {!Array<*>}
 */
function closureSelfUseNavigator(obj) {
  return [
    obj.webkitPersistentStorage,
    obj.webkitTemporaryStorage
  ];
}
globalThis['closureSelfUseNavigator'] = closureSelfUseNavigator;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    FileError.NOT_FOUND_ERR,
    FileError.NOT_READABLE_ERR,
    FileError.INVALID_STATE_ERR,
    FileError.TYPE_MISMATCH_ERR,
    resolveLocalFileSystemURI,
    createObjectURL,
    FileException.SECURITY_ERR,
    FileException.NO_MODIFICATION_ALLOWED_ERR,
    FileException.INVALID_MODIFICATION_ERR,
    FileException.PATH_EXISTS_ERR,
    revokeObjectURL('closure-self'),
    webkitURL.revokeObjectURL('closure-self'),
    requestFileSystemSync(1, 1),
    webkitRequestFileSystemSync(1, 1)
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!Entry} t0
 * @param {!FileSystemCallback} t1
 * @param {!EntriesCallback} t2
 * @param {!ErrorCallback} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
