/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.structs.set.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/structs/set.js).
 * Requires goog.structs.Set and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 * (Every public member of goog.structs.Set is @deprecated.)
 */
goog.module('closure_library_shim.goog_structs_Set');

const target = goog.require('goog.structs.Set');

goog.exportSymbol('goog.structs.Set', target);
goog.exportProperty(target.prototype, 'getCount', target.prototype.getCount);
goog.exportProperty(target.prototype, 'add', target.prototype.add);
goog.exportProperty(target.prototype, 'addAll', target.prototype.addAll);
goog.exportProperty(target.prototype, 'removeAll', target.prototype.removeAll);
