/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.fs.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/fs/fs.js).
 * Requires goog.testing.fs and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_fs');

const target = goog.require('goog.testing.fs');

goog.exportSymbol('goog.testing.fs.getTemporary', target.getTemporary);
goog.exportSymbol('goog.testing.fs.getPersistent', target.getPersistent);
goog.exportSymbol('goog.testing.fs.createObjectUrl', target.createObjectUrl);
goog.exportSymbol('goog.testing.fs.revokeObjectUrl', target.revokeObjectUrl);
goog.exportSymbol('goog.testing.fs.isObjectUrlGranted', target.isObjectUrlGranted);
goog.exportSymbol('goog.testing.fs.getBlob', target.getBlob);
goog.exportSymbol('goog.testing.fs.getBlobWithProperties', target.getBlobWithProperties);
goog.exportSymbol('goog.testing.fs.sliceBlob', target.sliceBlob);
