/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/html5.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!HTMLCanvasElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLCanvasElement(obj) {
  return [
    obj.width,
    obj.height,
    obj.toBlob,
    obj.getContext,
    obj.captureStream,
    obj.toDataURL(),
    obj.transferControlToOffscreen()
  ];
}
globalThis['closureSelfUseHTMLCanvasElement'] = closureSelfUseHTMLCanvasElement;

/**
 * @param {!ImageDataSettings} obj
 * @return {!Array<*>}
 */
function closureSelfUseImageDataSettings(obj) {
  return [
    obj.colorSpace,
    obj.pixelFormat
  ];
}
globalThis['closureSelfUseImageDataSettings'] = closureSelfUseImageDataSettings;

/**
 * @param {!SharedWorker} obj
 * @return {!Array<*>}
 */
function closureSelfUseSharedWorker(obj) {
  return [
    obj.addEventListener,
    obj.removeEventListener,
    obj.dispatchEvent,
    obj.port,
    obj.onerror
  ];
}
globalThis['closureSelfUseSharedWorker'] = closureSelfUseSharedWorker;

/**
 * @param {!VideoFrameMetadata} obj
 * @return {!Array<*>}
 */
function closureSelfUseVideoFrameMetadata(obj) {
  return [
    obj.presentationTime,
    obj.width,
    obj.mediaTime,
    obj.presentedFrames,
    obj.captureTime,
    obj.rtpTimestamp
  ];
}
globalThis['closureSelfUseVideoFrameMetadata'] = closureSelfUseVideoFrameMetadata;

/**
 * @param {!DataTransferItemList} obj
 * @return {!Array<*>}
 */
function closureSelfUseDataTransferItemList(obj) {
  return [
    obj.length,
    obj.add,
    obj.remove,
    obj.item(1),
    obj.clear()
  ];
}
globalThis['closureSelfUseDataTransferItemList'] = closureSelfUseDataTransferItemList;

/**
 * @param {!XMLHttpRequestEventTarget} obj
 * @return {!Array<*>}
 */
function closureSelfUseXMLHttpRequestEventTarget(obj) {
  return [
    obj.addEventListener,
    obj.removeEventListener,
    obj.dispatchEvent
  ];
}
globalThis['closureSelfUseXMLHttpRequestEventTarget'] = closureSelfUseXMLHttpRequestEventTarget;

/**
 * @param {!ErrorEventInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseErrorEventInit(obj) {
  return [
    obj.message,
    obj.filename,
    obj.lineno,
    obj.colno,
    obj.error
  ];
}
globalThis['closureSelfUseErrorEventInit'] = closureSelfUseErrorEventInit;

/**
 * @param {!HTMLMeterElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLMeterElement(obj) {
  return [
    obj.value,
    obj.min,
    obj.max,
    obj.high,
    obj.optimum,
    obj.labels
  ];
}
globalThis['closureSelfUseHTMLMeterElement'] = closureSelfUseHTMLMeterElement;

/**
 * @param {!VisualViewport} obj
 * @return {!Array<*>}
 */
function closureSelfUseVisualViewport(obj) {
  return [
    obj.offsetLeft,
    obj.pageLeft,
    obj.width,
    obj.addEventListener,
    obj.dispatchEvent,
    obj.onscroll
  ];
}
globalThis['closureSelfUseVisualViewport'] = closureSelfUseVisualViewport;

/**
 * @param {!ViewTransitionTypeSet} obj
 * @return {!Array<*>}
 */
function closureSelfUseViewTransitionTypeSet(obj) {
  return [
    obj.forEach
  ];
}
globalThis['closureSelfUseViewTransitionTypeSet'] = closureSelfUseViewTransitionTypeSet;

/**
 * @param {!Text} obj
 * @return {!Array<*>}
 */
function closureSelfUseText(obj) {
  return [
    obj.getDestinationInsertionPoints()
  ];
}
globalThis['closureSelfUseText'] = closureSelfUseText;

/**
 * @param {!UIEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseUIEvent(obj) {
  return [
    obj.sourceCapabilities
  ];
}
globalThis['closureSelfUseUIEvent'] = closureSelfUseUIEvent;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    createImageBitmap,
    ApplicationCache.IDLE,
    ApplicationCache.OBSOLETE,
    HTMLElement.formAssociated,
    HTMLMediaElement.NETWORK_NO_SOURCE,
    HTMLMediaElement.HAVE_FUTURE_DATA,
    MediaError.MEDIA_ERR_DECODE,
    WheelEvent.DOM_DELTA_LINE,
    WebSocket.CLOSING,
    clientInformation,
    openDatabase('closure-self', 'closure-self', 'closure-self', 1),
    atob('closure-self'),
    btoa('closure-self'),
    importScripts()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!OffscreenRenderingContext} t0
 * @param {!ImageBitmapSource} t1
 * @param {!MessageEventSource} t2
 * @param {!StorageEstimate} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
