/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.dom.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/dom/dom.js).
 * Requires goog.dom and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_dom');

const target = goog.require('goog.dom');

goog.exportSymbol('goog.dom.getDomHelper', target.getDomHelper);
goog.exportSymbol('goog.dom.getDocument', target.getDocument);
goog.exportSymbol('goog.dom.getElement', target.getElement);
goog.exportSymbol('goog.dom.getHTMLElement', target.getHTMLElement);
goog.exportSymbol('goog.dom.getRequiredElement', target.getRequiredElement);
goog.exportSymbol('goog.dom.getRequiredHTMLElement', target.getRequiredHTMLElement);
goog.exportSymbol('goog.dom.getElementsByTagName', target.getElementsByTagName);
goog.exportSymbol('goog.dom.getElementsByTagNameAndClass', target.getElementsByTagNameAndClass);
