/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/wicg_ink.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!InkPresenterParam} obj
 * @return {!Array<*>}
 */
function closureSelfUseInkPresenterParam(obj) {
  return [
    obj.presentationArea
  ];
}
globalThis['closureSelfUseInkPresenterParam'] = closureSelfUseInkPresenterParam;

/**
 * @param {!Ink} obj
 * @return {!Array<*>}
 */
function closureSelfUseInk(obj) {
  return [
    obj.requestPresenter()
  ];
}
globalThis['closureSelfUseInk'] = closureSelfUseInk;

/**
 * @param {!InkPresenter} obj
 * @return {!Array<*>}
 */
function closureSelfUseInkPresenter(obj) {
  return [
    obj.presentationArea,
    obj.expectedImprovement,
    obj.updateInkTrailStartPoint
  ];
}
globalThis['closureSelfUseInkPresenter'] = closureSelfUseInkPresenter;

/**
 * @param {!InkTrailStyle} obj
 * @return {!Array<*>}
 */
function closureSelfUseInkTrailStyle(obj) {
  return [
    obj.color,
    obj.diameter
  ];
}
globalThis['closureSelfUseInkTrailStyle'] = closureSelfUseInkTrailStyle;

/**
 * @param {!Navigator} obj
 * @return {!Array<*>}
 */
function closureSelfUseNavigator(obj) {
  return [
    obj.ink
  ];
}
globalThis['closureSelfUseNavigator'] = closureSelfUseNavigator;
