/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/wicg_floc.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!InterestCohort} obj
 * @return {!Array<*>}
 */
function closureSelfUseInterestCohort(obj) {
  return [
    obj.id,
    obj.version
  ];
}
globalThis['closureSelfUseInterestCohort'] = closureSelfUseInterestCohort;

/**
 * @param {!Document} obj
 * @return {!Array<*>}
 */
function closureSelfUseDocument(obj) {
  return [
    obj.interestCohort()
  ];
}
globalThis['closureSelfUseDocument'] = closureSelfUseDocument;
