/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.fs.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/fs/fs.js).
 * Requires goog.fs and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_fs');

const target = goog.require('goog.fs');

goog.exportSymbol('goog.fs.getTemporary', target.getTemporary);
goog.exportSymbol('goog.fs.getPersistent', target.getPersistent);
goog.exportSymbol('goog.fs.sliceBlob', target.sliceBlob);
