// Generated by corpus/d2/candidates/npm.collect.py for npm:riot@10.1.6 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/riot@10.1.6/package/cjs/riot.cjs');
globalThis['__'] = pkg.__;
globalThis['component'] = pkg.component;
globalThis['createPureComponent'] = pkg.createPureComponent;
globalThis['install'] = pkg.install;
globalThis['mount'] = pkg.mount;
globalThis['pure'] = pkg.pure;
globalThis['register'] = pkg.register;
globalThis['uninstall'] = pkg.uninstall;
globalThis['unmount'] = pkg.unmount;
globalThis['unregister'] = pkg.unregister;
globalThis['version'] = pkg.version;
globalThis['withTypes'] = pkg.withTypes;
