// Generated by corpus/d2/candidates/npm.collect.py for npm:redux@5.0.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/redux@5.0.1/package/dist/cjs/redux.cjs');
globalThis['redux'] = pkg;
