// Generated by corpus/d2/candidates/npm.collect.py for npm:lit-html@3.3.3 (BSD-3-Clause).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  _$LH as e__$LH,
  html as e_html,
  mathml as e_mathml,
  noChange as e_noChange,
  nothing as e_nothing,
  render as e_render,
  svg as e_svg,
} from '../../../../corpus-cache/d2/npm/lit-html@3.3.3/package/lit-html.js';
globalThis['_$LH'] = e__$LH;
globalThis['html'] = e_html;
globalThis['mathml'] = e_mathml;
globalThis['noChange'] = e_noChange;
globalThis['nothing'] = e_nothing;
globalThis['render'] = e_render;
globalThis['svg'] = e_svg;
