// Generated by corpus/d2/candidates/npm.collect.py for npm:set-cookie-parser@3.1.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/set-cookie-parser@3.1.2/package/dist/set-cookie.cjs');
globalThis['set-cookie-parser'] = pkg;
