// Generated by corpus/d2/candidates/npm.collect.py for npm:dequal@2.0.3 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  dequal as e_dequal,
} from '../../../../corpus-cache/d2/npm/dequal@2.0.3/package/dist/index.mjs';
globalThis['dequal'] = e_dequal;
