// Generated by corpus/d2/candidates/npm.collect.py for npm:nouislider@15.8.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  PipsMode as e_PipsMode,
  PipsType as e_PipsType,
  create as e_create,
  cssClasses as e_cssClasses,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/nouislider@15.8.1/package/dist/nouislider.mjs';
globalThis['PipsMode'] = e_PipsMode;
globalThis['PipsType'] = e_PipsType;
globalThis['create'] = e_create;
globalThis['cssClasses'] = e_cssClasses;
globalThis['default'] = e_default;
