/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-kefir-3.8.8-pkg-esm:
 * Node.js/AMD globals referenced by npm:kefir@3.8.8 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var module;
