// closure-rs D2 whole-program case whole-program-jsesc-3.1.0: runs the own test suite of
// jsesc@3.1.0 (mathiasbynens/jsesc @ 819f534875fd) against a compiled output.
//   node corpus/d2/shims/whole-program-jsesc-3.1.0/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-jsesc-3.1.0/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-jsesc-3.1.0",
  "global": "jsesc",
  "testDir": "corpus-cache/d2/whole-program/jsesc@3.1.0/repo",
  "framework": "mocha",
  "files": [
    "tests/tests.js"
  ],
  "modules": {
    "../jsesc.js": {
      "path": []
    }
  },
  "expectTests": 2
});
