// Generated by corpus/d2/candidates/npm.collect.py for npm:dat.gui@0.7.9 (Apache-2.0).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  GUI as e_GUI,
  color as e_color,
  controllers as e_controllers,
  default as e_default,
  dom as e_dom,
  gui as e_gui,
} from '../../../../corpus-cache/d2/npm/dat.gui@0.7.9/package/build/dat.gui.module.js';
globalThis['GUI'] = e_GUI;
globalThis['color'] = e_color;
globalThis['controllers'] = e_controllers;
globalThis['default'] = e_default;
globalThis['dom'] = e_dom;
globalThis['gui'] = e_gui;
