// Generated by corpus/d2/candidates/npm.collect.py for npm:timeago.js@4.0.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/timeago.js@4.0.2/package/lib/index.js');
globalThis['register'] = pkg.register;
globalThis['format'] = pkg.format;
globalThis['render'] = pkg.render;
globalThis['cancel'] = pkg.cancel;
