// GENERATED by scripts/gen_npm_types.mjs; do not edit by hand.
// Flags: scope/flags.txt (102 CommandLineRunner flags) and the OPTIONS table of
// crates/cli/src/command_line_runner.rs. Exports: the runtime in npm/closure-rs/, compatible with
// @types/google-closure-compiler@20231112.0.0 and google-closure-compiler@20261006.0.0.

/// <reference types="node" />
import type {ChildProcess, SpawnOptions} from 'child_process';

// ---- flag values --------------------------------------------------------------------------------

// Every flag value type below also admits any string (`string & {}` keeps the listed literals as
// editor suggestions). The official package and @types/google-closure-compiler pass strings
// through, and TypeScript widens the values of an options object declared before the call to
// `string`; rejecting those would break build files that compile against the official types.
// What the types do reject: booleans for non-boolean flags, arrays for flags that take one value.

/**
 * Value of a boolean flag. `true`/`false` become `--flag=true`/`--flag=false`; the strings are
 * the spellings CommandLineRunner's BooleanOptionHandler accepts (any case).
 */
export type BooleanFlag = boolean | 'true' | 'false' | 'on' | 'off' | 'yes' | 'no' | '1' | '0' | (string & {});

/** Value of an integer flag. */
export type IntFlag = number | `${number}` | (string & {});

/**
 * Value of a flag with a fixed set of values: one of the listed values, or its lower-case spelling
 * (the compiler ignores case).
 */
export type EnumFlag<T extends string> = T | Lowercase<T> | (string & {});

/** A flag that may be given several times: an array gives the flag once per item. */
export type Repeatable<T> = T | T[];

/** Values of `--jscomp_dev_mode`. */
export type DevMode =
  | 'OFF'
  | 'START'
  | 'START_AND_END'
  | 'EVERY_PASS';

/** Values of `--segment_of_compilation_to_run`. */
export type SegmentOfCompilationToRun =
  | 'ENTIRE_COMPILATION'
  | 'CHECKS'
  | 'OPTIMIZATIONS_FIRST_HALF'
  | 'OPTIMIZATIONS_SECOND_HALF'
  | 'OPTIMIZATIONS'
  | 'OPTIMIZATIONS_AND_FINALIZATIONS'
  | 'FINALIZATIONS';

/** Values of `--isolation_mode`. */
export type IsolationMode =
  | 'NONE'
  | 'IIFE';

/** Values of `--source_map_format`. */
export type SourceMapFormat =
  | 'DEFAULT'
  | 'V3';

/** Values of `--compilation_level`. */
export type CompilationLevel =
  | 'BUNDLE'
  | 'WHITESPACE_ONLY'
  | 'WHITESPACE'
  | 'TRANSPILE_ONLY'
  | 'SIMPLE_OPTIMIZATIONS'
  | 'SIMPLE'
  | 'ADVANCED_OPTIMIZATIONS'
  | 'ADVANCED';

/** Values of `--incremental_check_mode`. */
export type IncrementalCheckMode =
  | 'OFF'
  | 'GENERATE_IJS';

/** Values of `--warning_level`. */
export type WarningLevel =
  | 'QUIET'
  | 'DEFAULT'
  | 'VERBOSE';

/** Values of `--formatting`. */
export type FormattingOption =
  | 'PRETTY_PRINT'
  | 'PRINT_INPUT_DELIMITER'
  | 'SINGLE_QUOTES';

/** Values of `--language_in`, `--language_out`. */
export type LanguageMode =
  | 'ECMASCRIPT3'
  | 'ES3'
  | 'ECMASCRIPT5'
  | 'ES5'
  | 'ECMASCRIPT5_STRICT'
  | 'ES5_STRICT'
  | 'ECMASCRIPT_2015'
  | 'ES_2015'
  | 'ECMASCRIPT_2016'
  | 'ES_2016'
  | 'ECMASCRIPT_2017'
  | 'ES_2017'
  | 'ECMASCRIPT_2018'
  | 'ES_2018'
  | 'ECMASCRIPT_2019'
  | 'ES_2019'
  | 'ECMASCRIPT_2020'
  | 'ES_2020'
  | 'ECMASCRIPT_2021'
  | 'ES_2021'
  | 'ECMASCRIPT_2022'
  | 'ES_2022'
  | 'ECMASCRIPT_NEXT'
  | 'ES_NEXT'
  | 'STABLE'
  | 'NO_TRANSPILE'
  | 'UNSTABLE'
  | 'ECMASCRIPT6'
  | 'ES6'
  | 'ECMASCRIPT6_STRICT'
  | 'ES6_STRICT';

/** Values of `--tracer_mode`. */
export type TracerMode =
  | 'ALL'
  | 'RAW_SIZE'
  | 'AST_SIZE_AND_PRUNING'
  | 'AST_SIZE'
  | 'TIMING_ONLY'
  | 'OFF';

/** Values of `--env`. */
export type Environment =
  | 'BROWSER'
  | 'CUSTOM';

/** Values of `--json_streams`. */
export type JsonStreamMode =
  | 'NONE'
  | 'IN'
  | 'OUT'
  | 'BOTH';

/** Values of `--dependency_mode`. */
export type DependencyMode =
  | 'NONE'
  | 'SORT_ONLY'
  | 'PRUNE_LEGACY'
  | 'PRUNE'
  | 'PRUNE_ALLOW_NO_ENTRY_POINTS';

/** Values of `--module_resolution`. */
export type ResolutionMode =
  | 'BROWSER'
  | 'BROWSER_WITH_TRANSFORMED_PREFIXES'
  | 'NODE'
  | 'WEBPACK';

/** Values of `--error_format`. */
export type ErrorFormatOption =
  | 'STANDARD'
  | 'JSON';

/** Values of `--chunk_output_type`. */
export type ChunkOutputType =
  | 'GLOBAL_NAMESPACE'
  | 'ES_MODULES';

// ---- options ------------------------------------------------------------------------------------

/**
 * Every closure-rs (= CommandLineRunner) flag, by its name without the leading `--`, and by its
 * camelCase spelling (the wrapper turns `compilationLevel` into `--compilation_level`).
 *
 * Each entry becomes `--name=value`; an array value repeats the flag; `null` or `undefined`
 * gives the bare `--name` (as in the official package, so leave unset flags out of the object).
 */
export interface CompilerFlags {
  /**
   * shortcut for defining goog.FEATURESET_YEAR=YYYY. The minimum valid value of the browser year is 2012
   *
   * `--browser_featureset_year`. Default: `0`. Category: Miscellaneous.
   */
  browser_featureset_year?: IntFlag;
  /**
   * shortcut for defining goog.FEATURESET_YEAR=YYYY. The minimum valid value of the browser year is 2012
   *
   * `--browser_featureset_year`. Default: `0`. Category: Miscellaneous.
   * Same flag as `browser_featureset_year`.
   */
  browserFeaturesetYear?: IntFlag;
  /**
   * Displays this message on stdout and exit
   *
   * `--help`. Default: `false`. Category: Miscellaneous.
   */
  help?: BooleanFlag;
  /**
   * Prints out the parse tree and exits
   *
   * `--print_tree`. Default: `false`. Hidden in --help.
   */
  print_tree?: BooleanFlag;
  /**
   * Prints out the parse tree and exits
   *
   * `--print_tree`. Default: `false`. Hidden in --help.
   * Same flag as `print_tree`.
   */
  printTree?: BooleanFlag;
  /**
   * Prints out the parse tree as json and exits
   *
   * `--print_tree_json`. Default: `false`. Hidden in --help.
   */
  print_tree_json?: BooleanFlag;
  /**
   * Prints out the parse tree as json and exits
   *
   * `--print_tree_json`. Default: `false`. Hidden in --help.
   * Same flag as `print_tree_json`.
   */
  printTreeJson?: BooleanFlag;
  /**
   * Prints a dot file describing the internal abstract syntax tree and exits
   *
   * `--print_ast`. Default: `false`. Hidden in --help.
   */
  print_ast?: BooleanFlag;
  /**
   * Prints a dot file describing the internal abstract syntax tree and exits
   *
   * `--print_ast`. Default: `false`. Hidden in --help.
   * Same flag as `print_ast`.
   */
  printAst?: BooleanFlag;
  /**
   * Start output with "'use strict';".
   *
   * `--emit_use_strict`. Default: `false`. Category: Output.
   */
  emit_use_strict?: BooleanFlag;
  /**
   * Start output with "'use strict';".
   *
   * `--emit_use_strict`. Default: `false`. Category: Output.
   * Same flag as `emit_use_strict`.
   */
  emitUseStrict?: BooleanFlag;
  /**
   * Assume input sources are to run in strict mode.
   *
   * `--strict_mode_input`. Default: `true`. Category: Warning and Error Management.
   */
  strict_mode_input?: BooleanFlag;
  /**
   * Assume input sources are to run in strict mode.
   *
   * `--strict_mode_input`. Default: `true`. Category: Warning and Error Management.
   * Same flag as `strict_mode_input`.
   */
  strictModeInput?: BooleanFlag;
  /**
   * `--jscomp_dev_mode` (alias `--dev_mode`). Default: `OFF`. Hidden in --help.
   */
  jscomp_dev_mode?: EnumFlag<DevMode>;
  /**
   * `--jscomp_dev_mode` (alias `--dev_mode`). Default: `OFF`. Hidden in --help.
   * Same flag as `jscomp_dev_mode`.
   */
  jscompDevMode?: EnumFlag<DevMode>;
  /**
   * `--jscomp_dev_mode` (alias `--dev_mode`). Default: `OFF`. Hidden in --help.
   * Same flag as `jscomp_dev_mode`.
   */
  dev_mode?: EnumFlag<DevMode>;
  /**
   * `--jscomp_dev_mode` (alias `--dev_mode`). Default: `OFF`. Hidden in --help.
   * Same flag as `jscomp_dev_mode`.
   */
  devMode?: EnumFlag<DevMode>;
  /**
   * The logging level (standard java.util.logging.Level values) for Compiler progress. Does not control errors or warnings for the JavaScript code under compilation
   *
   * `--logging_level`. Default: `WARNING`. Hidden in --help.
   */
  logging_level?: string;
  /**
   * The logging level (standard java.util.logging.Level values) for Compiler progress. Does not control errors or warnings for the JavaScript code under compilation
   *
   * `--logging_level`. Default: `WARNING`. Hidden in --help.
   * Same flag as `logging_level`.
   */
  loggingLevel?: string;
  /**
   * The file containing JavaScript externs. You may specify multiple
   *
   * `--externs`. Category: Basic Usage.
   * Repeatable: an array gives the flag once per item.
   */
  externs?: Repeatable<string>;
  /**
   * The JavaScript filename. You may specify multiple. The flag name is optional, because args are interpreted as files by default. You may also use minimatch-style glob patterns. For example, use --js='**.js' --js='!**_test.js' to recursively include all js files that do not end in _test.js
   *
   * `--js`. Category: Basic Usage.
   * Repeatable: an array gives the flag once per item.
   */
  js?: Repeatable<string>;
  /**
   * The JavaScript zip filename. You may specify multiple.
   *
   * `--jszip`. Hidden in --help.
   * Repeatable: an array gives the flag once per item.
   */
  jszip?: Repeatable<string>;
  /**
   * Primary output filename. If not specified, output is written to stdout
   *
   * `--js_output_file`. Category: Basic Usage.
   */
  js_output_file?: string;
  /**
   * Primary output filename. If not specified, output is written to stdout
   *
   * `--js_output_file`. Category: Basic Usage.
   * Same flag as `js_output_file`.
   */
  jsOutputFile?: string;
  /**
   * A JavaScript chunk specification. The format is <name>:<num-js-files>[:[<dep>,...][:]]]. Chunk names must be unique. Each dep is the name of a chunk that this chunk depends on. Chunks must be listed in dependency order, and JS source files must be listed in the corresponding order. Where --chunk flags occur in relation to --js flags is unimportant. <num-js-files> may be set to 'auto' for the first chunk if it has no dependencies. Provide the value 'auto' to trigger chunk creation from CommonJS modules.
   *
   * `--chunk`. Category: Code Splitting.
   * Repeatable: an array gives the flag once per item.
   */
  chunk?: Repeatable<string>;
  /**
   * Filename to save state so that the compilation can be resumed later.
   *
   * `--filename_to_save_to`. Hidden in --help.
   */
  filename_to_save_to?: string;
  /**
   * Filename to save state so that the compilation can be resumed later.
   *
   * `--filename_to_save_to`. Hidden in --help.
   * Same flag as `filename_to_save_to`.
   */
  filenameToSaveTo?: string;
  /**
   * Filename where a compilation state was previously saved.
   *
   * `--filename_to_restore_from`. Hidden in --help.
   */
  filename_to_restore_from?: string;
  /**
   * Filename where a compilation state was previously saved.
   *
   * `--filename_to_restore_from`. Hidden in --help.
   * Same flag as `filename_to_restore_from`.
   */
  filenameToRestoreFrom?: string;
  /**
   * Which segment of the compilation to run.
   *
   * `--segment_of_compilation_to_run`. Default: `ENTIRE_COMPILATION`. Hidden in --help.
   */
  segment_of_compilation_to_run?: EnumFlag<SegmentOfCompilationToRun>;
  /**
   * Which segment of the compilation to run.
   *
   * `--segment_of_compilation_to_run`. Default: `ENTIRE_COMPILATION`. Hidden in --help.
   * Same flag as `segment_of_compilation_to_run`.
   */
  segmentOfCompilationToRun?: EnumFlag<SegmentOfCompilationToRun>;
  /**
   * File where the serialized version of the variable renaming map produced should be saved
   *
   * `--variable_renaming_report`. Category: Reports.
   */
  variable_renaming_report?: string;
  /**
   * File where the serialized version of the variable renaming map produced should be saved
   *
   * `--variable_renaming_report`. Category: Reports.
   * Same flag as `variable_renaming_report`.
   */
  variableRenamingReport?: string;
  /**
   * File where the encoded parameters created by Production Instrumentation are mapped to their pre-encoded values. The %outname% placeholder will expand to the name of the output file that the source map corresponds to. Must be used in tandem with --instrument_for_coverage_option=PRODUCTION
   *
   * `--instrument_mapping_report`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   */
  instrument_mapping_report?: string;
  /**
   * File where the encoded parameters created by Production Instrumentation are mapped to their pre-encoded values. The %outname% placeholder will expand to the name of the output file that the source map corresponds to. Must be used in tandem with --instrument_for_coverage_option=PRODUCTION
   *
   * `--instrument_mapping_report`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   * Same flag as `instrument_mapping_report`.
   */
  instrumentMappingReport?: string;
  /**
   * If true, variable renaming and property renaming report files will be produced as {binary name}_vars_renaming_report.out and {binary name}_props_renaming_report.out. Note that this flag cannot be used in conjunction with either variable_renaming_report or property_renaming_report
   *
   * `--create_renaming_reports`. Default: `false`. Hidden in --help.
   */
  create_renaming_reports?: BooleanFlag;
  /**
   * If true, variable renaming and property renaming report files will be produced as {binary name}_vars_renaming_report.out and {binary name}_props_renaming_report.out. Note that this flag cannot be used in conjunction with either variable_renaming_report or property_renaming_report
   *
   * `--create_renaming_reports`. Default: `false`. Hidden in --help.
   * Same flag as `create_renaming_reports`.
   */
  createRenamingReports?: BooleanFlag;
  /**
   * Includes sources content into source map. Greatly increases the size of source maps but offers greater portability
   *
   * `--source_map_include_content`. Default: `false`. Category: Reports.
   */
  source_map_include_content?: BooleanFlag;
  /**
   * Includes sources content into source map. Greatly increases the size of source maps but offers greater portability
   *
   * `--source_map_include_content`. Default: `false`. Category: Reports.
   * Same flag as `source_map_include_content`.
   */
  sourceMapIncludeContent?: BooleanFlag;
  /**
   * File where the serialized version of the property renaming map produced should be saved
   *
   * `--property_renaming_report`. Category: Reports.
   */
  property_renaming_report?: string;
  /**
   * File where the serialized version of the property renaming map produced should be saved
   *
   * `--property_renaming_report`. Category: Reports.
   * Same flag as `property_renaming_report`.
   */
  propertyRenamingReport?: string;
  /**
   * Check source validity but do not enforce Closure style rules and conventions
   *
   * `--third_party`. Default: `false`. Category: Miscellaneous.
   */
  third_party?: BooleanFlag;
  /**
   * Check source validity but do not enforce Closure style rules and conventions
   *
   * `--third_party`. Default: `false`. Category: Miscellaneous.
   * Same flag as `third_party`.
   */
  thirdParty?: BooleanFlag;
  /**
   * Controls how detailed the compilation summary is. Values: 0 (never print summary), 1 (print summary only if there are errors or warnings), 2 (print summary if the 'checkTypes' diagnostic group is enabled, see --jscomp_warning), 3 (always print summary). The default level is 1
   *
   * `--summary_detail_level`. Default: `1`. Hidden in --help.
   */
  summary_detail_level?: IntFlag;
  /**
   * Controls how detailed the compilation summary is. Values: 0 (never print summary), 1 (print summary only if there are errors or warnings), 2 (print summary if the 'checkTypes' diagnostic group is enabled, see --jscomp_warning), 3 (always print summary). The default level is 1
   *
   * `--summary_detail_level`. Default: `1`. Hidden in --help.
   * Same flag as `summary_detail_level`.
   */
  summaryDetailLevel?: IntFlag;
  /**
   * `--isolation_mode`. Default: `NONE`. Category: Output.
   */
  isolation_mode?: EnumFlag<IsolationMode>;
  /**
   * `--isolation_mode`. Default: `NONE`. Category: Output.
   * Same flag as `isolation_mode`.
   */
  isolationMode?: EnumFlag<IsolationMode>;
  /**
   * Interpolate output into this string at the place denoted by the marker token %output%. Use marker token %output|jsstring% to do js string escaping on the output. Consider using the --isolation_mode flag instead.
   *
   * `--output_wrapper`. Category: Output.
   */
  output_wrapper?: string;
  /**
   * Interpolate output into this string at the place denoted by the marker token %output%. Use marker token %output|jsstring% to do js string escaping on the output. Consider using the --isolation_mode flag instead.
   *
   * `--output_wrapper`. Category: Output.
   * Same flag as `output_wrapper`.
   */
  outputWrapper?: string;
  /**
   * Loads the specified file and passes the file contents to the --output_wrapper flag, replacing the value if it exists. This is useful if you want special characters like newline in the wrapper.
   *
   * `--output_wrapper_file`. Category: Output.
   */
  output_wrapper_file?: string;
  /**
   * Loads the specified file and passes the file contents to the --output_wrapper flag, replacing the value if it exists. This is useful if you want special characters like newline in the wrapper.
   *
   * `--output_wrapper_file`. Category: Output.
   * Same flag as `output_wrapper_file`.
   */
  outputWrapperFile?: string;
  /**
   * An output wrapper for a JavaScript chunk (optional). The format is <name>:<wrapper>. The chunk name must correspond with a chunk specified using --chunk. The wrapper must contain %s as the code placeholder. Alternately, %output% can be used in place of %s. %n% can be used to represent a newline. The %basename% placeholder can also be used to substitute the base name of the chunk output file.
   *
   * `--chunk_wrapper`. Category: Code Splitting.
   * Repeatable: an array gives the flag once per item.
   */
  chunk_wrapper?: Repeatable<string>;
  /**
   * An output wrapper for a JavaScript chunk (optional). The format is <name>:<wrapper>. The chunk name must correspond with a chunk specified using --chunk. The wrapper must contain %s as the code placeholder. Alternately, %output% can be used in place of %s. %n% can be used to represent a newline. The %basename% placeholder can also be used to substitute the base name of the chunk output file.
   *
   * `--chunk_wrapper`. Category: Code Splitting.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `chunk_wrapper`.
   */
  chunkWrapper?: Repeatable<string>;
  /**
   * Prefix for filenames of compiled JS chunks. <chunk-name>.js will be appended to this prefix. Directories will be created as needed. Use with --chunk
   *
   * `--chunk_output_path_prefix`. Default: `./`. Category: Code Splitting.
   */
  chunk_output_path_prefix?: string;
  /**
   * Prefix for filenames of compiled JS chunks. <chunk-name>.js will be appended to this prefix. Directories will be created as needed. Use with --chunk
   *
   * `--chunk_output_path_prefix`. Default: `./`. Category: Code Splitting.
   * Same flag as `chunk_output_path_prefix`.
   */
  chunkOutputPathPrefix?: string;
  /**
   * If specified, a source map file mapping the generated source files back to the original source file will be output to the specified path. The %outname% placeholder will expand to the name of the output file that the source map corresponds to.
   *
   * `--create_source_map`. Category: Reports.
   */
  create_source_map?: string;
  /**
   * If specified, a source map file mapping the generated source files back to the original source file will be output to the specified path. The %outname% placeholder will expand to the name of the output file that the source map corresponds to.
   *
   * `--create_source_map`. Category: Reports.
   * Same flag as `create_source_map`.
   */
  createSourceMap?: string;
  /**
   * The source map format to produce. Options are V3 and DEFAULT, which are equivalent.
   *
   * `--source_map_format`. Default: `DEFAULT`. Hidden in --help.
   */
  source_map_format?: EnumFlag<SourceMapFormat>;
  /**
   * The source map format to produce. Options are V3 and DEFAULT, which are equivalent.
   *
   * `--source_map_format`. Default: `DEFAULT`. Hidden in --help.
   * Same flag as `source_map_format`.
   */
  sourceMapFormat?: EnumFlag<SourceMapFormat>;
  /**
   * Source map location mapping separated by a '|' (i.e. filesystem-path|webserver-path)
   *
   * `--source_map_location_mapping`. Category: Reports.
   * Repeatable: an array gives the flag once per item.
   */
  source_map_location_mapping?: Repeatable<string>;
  /**
   * Source map location mapping separated by a '|' (i.e. filesystem-path|webserver-path)
   *
   * `--source_map_location_mapping`. Category: Reports.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `source_map_location_mapping`.
   */
  sourceMapLocationMapping?: Repeatable<string>;
  /**
   * Source map locations for input files, separated by a '|', (i.e. input-file-path|input-source-map)
   *
   * `--source_map_input`. Category: Reports.
   * Repeatable: an array gives the flag once per item.
   */
  source_map_input?: Repeatable<string>;
  /**
   * Source map locations for input files, separated by a '|', (i.e. input-file-path|input-source-map)
   *
   * `--source_map_input`. Category: Reports.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `source_map_input`.
   */
  sourceMapInput?: Repeatable<string>;
  /**
   * `--parse_inline_source_maps`. Default: `true`.
   */
  parse_inline_source_maps?: BooleanFlag;
  /**
   * `--parse_inline_source_maps`. Default: `true`.
   * Same flag as `parse_inline_source_maps`.
   */
  parseInlineSourceMaps?: BooleanFlag;
  /**
   * Apply input source maps to the output source map, i.e. have the result map back to original inputs. Input sourcemaps can be located in 2 ways: 1) by the + + + +
   *
   * `--apply_input_source_maps`. Default: `true`.
   */
  apply_input_source_maps?: BooleanFlag;
  /**
   * Apply input source maps to the output source map, i.e. have the result map back to original inputs. Input sourcemaps can be located in 2 ways: 1) by the + + + +
   *
   * `--apply_input_source_maps`. Default: `true`.
   * Same flag as `apply_input_source_maps`.
   */
  applyInputSourceMaps?: BooleanFlag;
  /**
   * Make the named class of warnings an error. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_error`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  jscomp_error?: Repeatable<string>;
  /**
   * Make the named class of warnings an error. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_error`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `jscomp_error`.
   */
  jscompError?: Repeatable<string>;
  /**
   * Make the named class of warnings a normal warning. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_warning`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  jscomp_warning?: Repeatable<string>;
  /**
   * Make the named class of warnings a normal warning. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_warning`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `jscomp_warning`.
   */
  jscompWarning?: Repeatable<string>;
  /**
   * Turn off the named class of warnings. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_off`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  jscomp_off?: Repeatable<string>;
  /**
   * Turn off the named class of warnings. Must be one of the error group items. '*' adds all supported.
   *
   * `--jscomp_off`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `jscomp_off`.
   */
  jscompOff?: Repeatable<string>;
  /**
   * Override the value of a variable annotated @define. The format is <name>[=<val>], where <name> is the name of a @define variable and <val> is a boolean, number, or a single-quoted string that contains no single quotes. If [=<val>] is omitted, the variable is marked true
   *
   * `--define` (alias `--D`, `-D`). Category: Miscellaneous.
   * Repeatable: an array gives the flag once per item.
   */
  define?: Repeatable<string>;
  /**
   * Input and output charset for all files. By default, we accept UTF-8 as input and output US_ASCII
   *
   * `--charset`. Category: Miscellaneous.
   */
  charset?: string;
  /**
   * Specifies the compilation level to use. Options: BUNDLE, WHITESPACE_ONLY, SIMPLE (default), TRANSPILE_ONLY,ADVANCED
   *
   * `--compilation_level` (alias `-O`). Default: `SIMPLE`. Category: Basic Usage.
   */
  compilation_level?: EnumFlag<CompilationLevel>;
  /**
   * Specifies the compilation level to use. Options: BUNDLE, WHITESPACE_ONLY, SIMPLE (default), TRANSPILE_ONLY,ADVANCED
   *
   * `--compilation_level` (alias `-O`). Default: `SIMPLE`. Category: Basic Usage.
   * Same flag as `compilation_level`.
   */
  compilationLevel?: EnumFlag<CompilationLevel>;
  /**
   * Use multiple threads to parallelize parts of the compilation.
   *
   * `--num_parallel_threads`. Default: `1`. Hidden in --help.
   */
  num_parallel_threads?: IntFlag;
  /**
   * Use multiple threads to parallelize parts of the compilation.
   *
   * `--num_parallel_threads`. Default: `1`. Hidden in --help.
   * Same flag as `num_parallel_threads`.
   */
  numParallelThreads?: IntFlag;
  /**
   * Don't generate output. Run checks, but no optimization passes.
   *
   * `--checks_only` (alias `--checks-only`). Default: `false`. Category: Miscellaneous.
   */
  checks_only?: BooleanFlag;
  /**
   * Don't generate output. Run checks, but no optimization passes.
   *
   * `--checks_only` (alias `--checks-only`). Default: `false`. Category: Miscellaneous.
   * Same flag as `checks_only`.
   */
  checksOnly?: BooleanFlag;
  /**
   * Don't generate output. Run checks, but no optimization passes.
   *
   * `--checks_only` (alias `--checks-only`). Default: `false`. Category: Miscellaneous.
   * Same flag as `checks_only`.
   */
  'checks-only'?: BooleanFlag;
  /**
   * Generate or check externs-like .i.js files representing individual libraries.
   *
   * `--incremental_check_mode`. Default: `OFF`.
   */
  incremental_check_mode?: EnumFlag<IncrementalCheckMode>;
  /**
   * Generate or check externs-like .i.js files representing individual libraries.
   *
   * `--incremental_check_mode`. Default: `OFF`.
   * Same flag as `incremental_check_mode`.
   */
  incrementalCheckMode?: EnumFlag<IncrementalCheckMode>;
  /**
   * Continue trying to compile after an error is encountered.
   *
   * `--continue_after_errors`. Default: `false`.
   */
  continue_after_errors?: BooleanFlag;
  /**
   * Continue trying to compile after an error is encountered.
   *
   * `--continue_after_errors`. Default: `false`.
   * Same flag as `continue_after_errors`.
   */
  continueAfterErrors?: BooleanFlag;
  /**
   * Enable or disable the optimizations based on available type information. Inaccurate type annotations may result in incorrect results.
   *
   * `--use_types_for_optimization`. Default: `true`. Category: Miscellaneous.
   */
  use_types_for_optimization?: BooleanFlag;
  /**
   * Enable or disable the optimizations based on available type information. Inaccurate type annotations may result in incorrect results.
   *
   * `--use_types_for_optimization`. Default: `true`. Category: Miscellaneous.
   * Same flag as `use_types_for_optimization`.
   */
  useTypesForOptimization?: BooleanFlag;
  /**
   * Enable additional optimizations based on the assumption that the output will be wrapped with a function wrapper. This flag is used to indicate that "global" declarations will not actually be global but instead isolated to the compilation unit. This enables additional optimizations.
   *
   * `--assume_function_wrapper`. Default: `false`. Category: Output.
   */
  assume_function_wrapper?: BooleanFlag;
  /**
   * Enable additional optimizations based on the assumption that the output will be wrapped with a function wrapper. This flag is used to indicate that "global" declarations will not actually be global but instead isolated to the compilation unit. This enables additional optimizations.
   *
   * `--assume_function_wrapper`. Default: `false`. Category: Output.
   * Same flag as `assume_function_wrapper`.
   */
  assumeFunctionWrapper?: BooleanFlag;
  /**
   * Specifies the warning level to use. Options: QUIET, DEFAULT, VERBOSE
   *
   * `--warning_level` (alias `-W`). Default: `DEFAULT`. Category: Basic Usage.
   */
  warning_level?: EnumFlag<WarningLevel>;
  /**
   * Specifies the warning level to use. Options: QUIET, DEFAULT, VERBOSE
   *
   * `--warning_level` (alias `-W`). Default: `DEFAULT`. Category: Basic Usage.
   * Same flag as `warning_level`.
   */
  warningLevel?: EnumFlag<WarningLevel>;
  /**
   * Enable debugging options. Property renaming uses long mangled names which can be mapped back to the original name.
   *
   * `--debug`. Default: `false`. Category: Output.
   */
  debug?: BooleanFlag;
  /**
   * Sets file to output in-progress typedAST format. DO NOT USE!
   *
   * `--typed_ast_output_file`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: usage says "DO NOT USE").
   */
  typed_ast_output_file?: string;
  /**
   * Sets file to output in-progress typedAST format. DO NOT USE!
   *
   * `--typed_ast_output_file`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: usage says "DO NOT USE").
   * Same flag as `typed_ast_output_file`.
   */
  typedAstOutputFile?: string;
  /**
   * Generates export code for those marked with @export
   *
   * `--generate_exports`. Default: `true`. Category: Output.
   */
  generate_exports?: BooleanFlag;
  /**
   * Generates export code for those marked with @export
   *
   * `--generate_exports`. Default: `true`. Category: Output.
   * Same flag as `generate_exports`.
   */
  generateExports?: BooleanFlag;
  /**
   * Generates export code for local properties marked with @export
   *
   * `--export_local_property_definitions`. Default: `true`. Category: Output.
   */
  export_local_property_definitions?: BooleanFlag;
  /**
   * Generates export code for local properties marked with @export
   *
   * `--export_local_property_definitions`. Default: `true`. Category: Output.
   * Same flag as `export_local_property_definitions`.
   */
  exportLocalPropertyDefinitions?: BooleanFlag;
  /**
   * Specifies which formatting options, if any, should be applied to the output JS. Options: PRETTY_PRINT, PRINT_INPUT_DELIMITER, SINGLE_QUOTES
   *
   * `--formatting`. Category: Output.
   * Repeatable: an array gives the flag once per item.
   */
  formatting?: Repeatable<EnumFlag<FormattingOption>>;
  /**
   * Process CommonJS modules to a concatenable form.
   *
   * `--process_common_js_modules`. Default: `false`. Category: JS Modules.
   */
  process_common_js_modules?: BooleanFlag;
  /**
   * Process CommonJS modules to a concatenable form.
   *
   * `--process_common_js_modules`. Default: `false`. Category: JS Modules.
   * Same flag as `process_common_js_modules`.
   */
  processCommonJsModules?: BooleanFlag;
  /**
   * Path prefixes to be removed from ES6 & CommonJS modules.
   *
   * `--js_module_root`. Category: JS Modules.
   * Repeatable: an array gives the flag once per item.
   */
  js_module_root?: Repeatable<string>;
  /**
   * Path prefixes to be removed from ES6 & CommonJS modules.
   *
   * `--js_module_root`. Category: JS Modules.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `js_module_root`.
   */
  jsModuleRoot?: Repeatable<string>;
  /**
   * Processes built-ins from the Closure library, such as goog.require(), goog.provide(), and goog.exportSymbol(). True by default.
   *
   * `--process_closure_primitives`. Default: `true`. Category: Library and Framework Specific.
   */
  process_closure_primitives?: BooleanFlag;
  /**
   * Processes built-ins from the Closure library, such as goog.require(), goog.provide(), and goog.exportSymbol(). True by default.
   *
   * `--process_closure_primitives`. Default: `true`. Category: Library and Framework Specific.
   * Same flag as `process_closure_primitives`.
   */
  processClosurePrimitives?: BooleanFlag;
  /**
   * Generate $inject properties for AngularJS for functions annotated with @ngInject
   *
   * `--angular_pass`. Default: `false`. Category: Library and Framework Specific.
   */
  angular_pass?: BooleanFlag;
  /**
   * Generate $inject properties for AngularJS for functions annotated with @ngInject
   *
   * `--angular_pass`. Default: `false`. Category: Library and Framework Specific.
   * Same flag as `angular_pass`.
   */
  angularPass?: BooleanFlag;
  /**
   * Which version of Polymer is being used (1 or 2).
   *
   * `--polymer_version`. Category: Library and Framework Specific.
   * Outside the closure-rs port scope (docs/PORTING.md §2: Polymer area; configures the Polymer passes (PolymerPass and friends)).
   */
  polymer_version?: IntFlag;
  /**
   * Which version of Polymer is being used (1 or 2).
   *
   * `--polymer_version`. Category: Library and Framework Specific.
   * Outside the closure-rs port scope (docs/PORTING.md §2: Polymer area; configures the Polymer passes (PolymerPass and friends)).
   * Same flag as `polymer_version`.
   */
  polymerVersion?: IntFlag;
  /**
   * Enable Chrome-specific options for handling cr.* functions.
   *
   * `--chrome_pass`. Default: `false`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: Chrome area; configures the Chrome-specific passes (ChromePass)).
   */
  chrome_pass?: BooleanFlag;
  /**
   * Enable Chrome-specific options for handling cr.* functions.
   *
   * `--chrome_pass`. Default: `false`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: Chrome area; configures the Chrome-specific passes (ChromePass)).
   * Same flag as `chrome_pass`.
   */
  chromePass?: BooleanFlag;
  /**
   * Rewrite J2CL output to be compiler-friendly if enabled (ON or AUTO). Options:OFF, ON, AUTO(default)
   *
   * `--j2cl_pass`. Default: `AUTO`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: J2CL area; configures the J2CL passes (J2clPass, J2clAssertRemovalPass, ...)).
   */
  j2cl_pass?: string;
  /**
   * Rewrite J2CL output to be compiler-friendly if enabled (ON or AUTO). Options:OFF, ON, AUTO(default)
   *
   * `--j2cl_pass`. Default: `AUTO`. Hidden in --help.
   * Outside the closure-rs port scope (docs/PORTING.md §2: J2CL area; configures the J2CL passes (J2clPass, J2clAssertRemovalPass, ...)).
   * Same flag as `j2cl_pass`.
   */
  j2clPass?: string;
  /**
   * Remove calls to J2CL assertions.
   *
   * `--remove_j2cl_asserts`. Default: `true`. Hidden in --help.
   * Takes no value: pass null to emit the bare flag.
   * Outside the closure-rs port scope (docs/PORTING.md §2: J2CL area; configures the J2CL passes (J2clPass, J2clAssertRemovalPass, ...)).
   */
  remove_j2cl_asserts?: null;
  /**
   * Remove calls to J2CL assertions.
   *
   * `--remove_j2cl_asserts`. Default: `true`. Hidden in --help.
   * Takes no value: pass null to emit the bare flag.
   * Outside the closure-rs port scope (docs/PORTING.md §2: J2CL area; configures the J2CL passes (J2clPass, J2clAssertRemovalPass, ...)).
   * Same flag as `remove_j2cl_asserts`.
   */
  removeJ2clAsserts?: null;
  /**
   * Prints out a list of all the files in the compilation. If --dependency_mode=PRUNE or PRUNE_LEGACY is specified, this will not include files that got dropped because they were not required. The %outname% placeholder expands to the JS output file. If you're using modularization, using %outname% will create a manifest for each module.
   *
   * `--output_manifest`. Category: Reports.
   */
  output_manifest?: string;
  /**
   * Prints out a list of all the files in the compilation. If --dependency_mode=PRUNE or PRUNE_LEGACY is specified, this will not include files that got dropped because they were not required. The %outname% placeholder expands to the JS output file. If you're using modularization, using %outname% will create a manifest for each module.
   *
   * `--output_manifest`. Category: Reports.
   * Same flag as `output_manifest`.
   */
  outputManifest?: string;
  /**
   * Prints out a JSON file of dependencies between chunks.
   *
   * `--output_chunk_dependencies`. Category: Reports.
   */
  output_chunk_dependencies?: string;
  /**
   * Prints out a JSON file of dependencies between chunks.
   *
   * `--output_chunk_dependencies`. Category: Reports.
   * Same flag as `output_chunk_dependencies`.
   */
  outputChunkDependencies?: string;
  /**
   * Sets the language spec to which input sources should conform. Options: ECMASCRIPT3, ECMASCRIPT5, ECMASCRIPT5_STRICT, ECMASCRIPT_2015, ECMASCRIPT_2016, ECMASCRIPT_2017, ECMASCRIPT_2018, ECMASCRIPT_2019, ECMASCRIPT_2020,ECMASCRIPT_2021, STABLE, ECMASCRIPT_NEXT (latest features supported),UNSTABLE (for testing only)
   *
   * `--language_in`. Default: `STABLE`. Category: Basic Usage.
   */
  language_in?: EnumFlag<LanguageMode>;
  /**
   * Sets the language spec to which input sources should conform. Options: ECMASCRIPT3, ECMASCRIPT5, ECMASCRIPT5_STRICT, ECMASCRIPT_2015, ECMASCRIPT_2016, ECMASCRIPT_2017, ECMASCRIPT_2018, ECMASCRIPT_2019, ECMASCRIPT_2020,ECMASCRIPT_2021, STABLE, ECMASCRIPT_NEXT (latest features supported),UNSTABLE (for testing only)
   *
   * `--language_in`. Default: `STABLE`. Category: Basic Usage.
   * Same flag as `language_in`.
   */
  languageIn?: EnumFlag<LanguageMode>;
  /**
   * Sets the language spec to which output should conform. Options: ECMASCRIPT3, ECMASCRIPT5, ECMASCRIPT_2015, ECMASCRIPT_2016, ECMASCRIPT_2017, ECMASCRIPT_2018, ECMASCRIPT_2019, ECMASCRIPT_2020, ECMASCRIPT_2021, STABLE, ECMASCRIPT_NEXT (latest features supported)
   *
   * `--language_out`. Default: `ECMASCRIPT_NEXT`. Category: Basic Usage.
   */
  language_out?: EnumFlag<LanguageMode>;
  /**
   * Sets the language spec to which output should conform. Options: ECMASCRIPT3, ECMASCRIPT5, ECMASCRIPT_2015, ECMASCRIPT_2016, ECMASCRIPT_2017, ECMASCRIPT_2018, ECMASCRIPT_2019, ECMASCRIPT_2020, ECMASCRIPT_2021, STABLE, ECMASCRIPT_NEXT (latest features supported)
   *
   * `--language_out`. Default: `ECMASCRIPT_NEXT`. Category: Basic Usage.
   * Same flag as `language_out`.
   */
  languageOut?: EnumFlag<LanguageMode>;
  /**
   * Prints the compiler version to stdout and exit.
   *
   * `--version`. Default: `false`. Category: Miscellaneous.
   */
  version?: BooleanFlag;
  /**
   * Source of translated messages. Currently only supports XTB.
   *
   * `--translations_file`. Hidden in --help.
   */
  translations_file?: string;
  /**
   * Source of translated messages. Currently only supports XTB.
   *
   * `--translations_file`. Hidden in --help.
   * Same flag as `translations_file`.
   */
  translationsFile?: string;
  /**
   * Scopes all translations to the specified project.When specified, we will use different message ids so that messages in different projects can have different translations.
   *
   * `--translations_project`. Hidden in --help.
   */
  translations_project?: string;
  /**
   * Scopes all translations to the specified project.When specified, we will use different message ids so that messages in different projects can have different translations.
   *
   * `--translations_project`. Hidden in --help.
   * Same flag as `translations_project`.
   */
  translationsProject?: string;
  /**
   * A file (or files) containing additional command-line options.
   *
   * `--flagfile`. Category: Miscellaneous. Hidden in --help.
   * Repeatable: an array gives the flag once per item.
   */
  flagfile?: Repeatable<string>;
  /**
   * A file containing warnings to suppress. Each line should be of the form <file-name>:<line-number>? <warning-description>
   *
   * `--warnings_allowlist_file` (alias `--warnings_whitelist_file`). Category: Warning and Error Management.
   */
  warnings_allowlist_file?: string;
  /**
   * A file containing warnings to suppress. Each line should be of the form <file-name>:<line-number>? <warning-description>
   *
   * `--warnings_allowlist_file` (alias `--warnings_whitelist_file`). Category: Warning and Error Management.
   * Same flag as `warnings_allowlist_file`.
   */
  warningsAllowlistFile?: string;
  /**
   * A file containing warnings to suppress. Each line should be of the form <file-name>:<line-number>? <warning-description>
   *
   * `--warnings_allowlist_file` (alias `--warnings_whitelist_file`). Category: Warning and Error Management.
   * Same flag as `warnings_allowlist_file`.
   */
  warnings_whitelist_file?: string;
  /**
   * A file containing warnings to suppress. Each line should be of the form <file-name>:<line-number>? <warning-description>
   *
   * `--warnings_allowlist_file` (alias `--warnings_whitelist_file`). Category: Warning and Error Management.
   * Same flag as `warnings_allowlist_file`.
   */
  warningsWhitelistFile?: string;
  /**
   * If specified, files whose path contains this string will have their warnings hidden. You may specify multiple.
   *
   * `--hide_warnings_for`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  hide_warnings_for?: Repeatable<string>;
  /**
   * If specified, files whose path contains this string will have their warnings hidden. You may specify multiple.
   *
   * `--hide_warnings_for`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `hide_warnings_for`.
   */
  hideWarningsFor?: Repeatable<string>;
  /**
   * A allowlist of tag names in JSDoc. You may specify multiple
   *
   * `--extra_annotation_name`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  extra_annotation_name?: Repeatable<string>;
  /**
   * A allowlist of tag names in JSDoc. You may specify multiple
   *
   * `--extra_annotation_name`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `extra_annotation_name`.
   */
  extraAnnotationName?: Repeatable<string>;
  /**
   * Shows the duration of each compiler pass and the impact to the compiled output size. Options: ALL, AST_SIZE, RAW_SIZE, TIMING_ONLY, OFF
   *
   * `--tracer_mode`. Default: `OFF`. Hidden in --help.
   */
  tracer_mode?: EnumFlag<TracerMode>;
  /**
   * Shows the duration of each compiler pass and the impact to the compiled output size. Options: ALL, AST_SIZE, RAW_SIZE, TIMING_ONLY, OFF
   *
   * `--tracer_mode`. Default: `OFF`. Hidden in --help.
   * Same flag as `tracer_mode`.
   */
  tracerMode?: EnumFlag<TracerMode>;
  /**
   * Specifies a prefix that will be prepended to all variables.
   *
   * `--rename_variable_prefix`. Category: Output.
   */
  rename_variable_prefix?: string;
  /**
   * Specifies a prefix that will be prepended to all variables.
   *
   * `--rename_variable_prefix`. Category: Output.
   * Same flag as `rename_variable_prefix`.
   */
  renameVariablePrefix?: string;
  /**
   * Specifies the name of an object that will be used to store all non-extern globals
   *
   * `--rename_prefix_namespace`. Category: Code Splitting.
   */
  rename_prefix_namespace?: string;
  /**
   * Specifies the name of an object that will be used to store all non-extern globals
   *
   * `--rename_prefix_namespace`. Category: Code Splitting.
   * Same flag as `rename_prefix_namespace`.
   */
  renamePrefixNamespace?: string;
  /**
   * A list of JS Conformance configurations in text protocol buffer format.
   *
   * `--conformance_configs`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   */
  conformance_configs?: Repeatable<string>;
  /**
   * A list of JS Conformance configurations in text protocol buffer format.
   *
   * `--conformance_configs`. Category: Warning and Error Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `conformance_configs`.
   */
  conformanceConfigs?: Repeatable<string>;
  /**
   * Determines the set of builtin externs to load. Options: BROWSER, CUSTOM. Defaults to BROWSER.
   *
   * `--env`. Default: `BROWSER`. Category: Basic Usage.
   */
  env?: EnumFlag<Environment>;
  /**
   * Specifies whether standard input and output streams will be a JSON array of sources. Each source will be an object of the form {path: filename, src: file_contents, source_map: srcmap_contents }. Intended for use by stream-based build systems such as gulpjs. Options: NONE, IN, OUT, BOTH. Defaults to NONE.
   *
   * `--json_streams`. Default: `NONE`. Category: Miscellaneous.
   */
  json_streams?: EnumFlag<JsonStreamMode>;
  /**
   * Specifies whether standard input and output streams will be a JSON array of sources. Each source will be an object of the form {path: filename, src: file_contents, source_map: srcmap_contents }. Intended for use by stream-based build systems such as gulpjs. Options: NONE, IN, OUT, BOTH. Defaults to NONE.
   *
   * `--json_streams`. Default: `NONE`. Category: Miscellaneous.
   * Same flag as `json_streams`.
   */
  jsonStreams?: EnumFlag<JsonStreamMode>;
  /**
   * Preserves type annotations.
   *
   * `--preserve_type_annotations`. Default: `false`. Hidden in --help.
   */
  preserve_type_annotations?: BooleanFlag;
  /**
   * Preserves type annotations.
   *
   * `--preserve_type_annotations`. Default: `false`. Hidden in --help.
   * Same flag as `preserve_type_annotations`.
   */
  preserveTypeAnnotations?: BooleanFlag;
  /**
   * Allow injecting runtime libraries.
   *
   * `--inject_libraries`. Default: `true`. Category: Library and Framework Specific.
   */
  inject_libraries?: BooleanFlag;
  /**
   * Allow injecting runtime libraries.
   *
   * `--inject_libraries`. Default: `true`. Category: Library and Framework Specific.
   * Same flag as `inject_libraries`.
   */
  injectLibraries?: BooleanFlag;
  /**
   * Force injection of named runtime libraries. The format is <name> where <name> is the name of a runtime library. Possible libraries include: base, es6_runtime
   *
   * `--force_inject_library`. Category: Library and Framework Specific.
   * Repeatable: an array gives the flag once per item.
   */
  force_inject_library?: Repeatable<string>;
  /**
   * Force injection of named runtime libraries. The format is <name> where <name> is the name of a runtime library. Possible libraries include: base, es6_runtime
   *
   * `--force_inject_library`. Category: Library and Framework Specific.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `force_inject_library`.
   */
  forceInjectLibrary?: Repeatable<string>;
  /**
   * Specifies how the compiler should determine the set and order of files for a compilation. Options: NONE the compiler will include all src files in the order listed, SORT_ONLY the compiler will include all source files in dependency order, PRUNE files will only be included if they are transitive dependencies of files listed in the --entry_point flag and then sorted in dependency order, PRUNE_LEGACY same as PRUNE but files that do not goog.provide a namespace and are not modules will be automatically added as --entry_point entries. Defaults to PRUNE_LEGACY if entry points are defined, otherwise to NONE.
   *
   * `--dependency_mode`. Category: Dependency Management.
   */
  dependency_mode?: EnumFlag<DependencyMode>;
  /**
   * Specifies how the compiler should determine the set and order of files for a compilation. Options: NONE the compiler will include all src files in the order listed, SORT_ONLY the compiler will include all source files in dependency order, PRUNE files will only be included if they are transitive dependencies of files listed in the --entry_point flag and then sorted in dependency order, PRUNE_LEGACY same as PRUNE but files that do not goog.provide a namespace and are not modules will be automatically added as --entry_point entries. Defaults to PRUNE_LEGACY if entry points are defined, otherwise to NONE.
   *
   * `--dependency_mode`. Category: Dependency Management.
   * Same flag as `dependency_mode`.
   */
  dependencyMode?: EnumFlag<DependencyMode>;
  /**
   * A file or namespace to use as the starting point for determining which src files to include in the compilation. ES6 and CommonJS modules are specified as file paths (without the extension). Closure-library namespaces are specified with a "goog:" prefix. Example: --entry_point=goog:goog.Promise
   *
   * `--entry_point`. Category: Dependency Management.
   * Repeatable: an array gives the flag once per item.
   */
  entry_point?: Repeatable<string>;
  /**
   * A file or namespace to use as the starting point for determining which src files to include in the compilation. ES6 and CommonJS modules are specified as file paths (without the extension). Closure-library namespaces are specified with a "goog:" prefix. Example: --entry_point=goog:goog.Promise
   *
   * `--entry_point`. Category: Dependency Management.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `entry_point`.
   */
  entryPoint?: Repeatable<string>;
  /**
   * Injects polyfills for ES2015+ library classes and methods used in source. See also the "Polyfills" GitHub Wiki page.
   *
   * `--rewrite_polyfills`. Default: `true`. Category: Library and Framework Specific.
   */
  rewrite_polyfills?: BooleanFlag;
  /**
   * Injects polyfills for ES2015+ library classes and methods used in source. See also the "Polyfills" GitHub Wiki page.
   *
   * `--rewrite_polyfills`. Default: `true`. Category: Library and Framework Specific.
   * Same flag as `rewrite_polyfills`.
   */
  rewritePolyfills?: BooleanFlag;
  /**
   * Hides injected polyfills from the global scope and any external code. See the the "Polyfills" GitHub Wiki page for details.
   *
   * `--isolate_polyfills`. Default: `false`. Category: Library and Framework Specific.
   */
  isolate_polyfills?: BooleanFlag;
  /**
   * Hides injected polyfills from the global scope and any external code. See the the "Polyfills" GitHub Wiki page for details.
   *
   * `--isolate_polyfills`. Default: `false`. Category: Library and Framework Specific.
   * Same flag as `isolate_polyfills`.
   */
  isolatePolyfills?: BooleanFlag;
  /**
   * Whether to iteratively print resulting JS source per pass.
   *
   * `--print_source_after_each_pass`. Default: `false`. Hidden in --help.
   */
  print_source_after_each_pass?: BooleanFlag;
  /**
   * Whether to iteratively print resulting JS source per pass.
   *
   * `--print_source_after_each_pass`. Default: `false`. Hidden in --help.
   * Same flag as `print_source_after_each_pass`.
   */
  printSourceAfterEachPass?: BooleanFlag;
  /**
   * Specifies how the compiler locates modules. BROWSER requires all module imports to begin with a '.' or '/' and have a file extension. NODE uses the node module rules. WEBPACK looks up modules from a special lookup map.
   *
   * `--module_resolution`. Default: `BROWSER`. Category: JS Modules.
   */
  module_resolution?: EnumFlag<ResolutionMode>;
  /**
   * Specifies how the compiler locates modules. BROWSER requires all module imports to begin with a '.' or '/' and have a file extension. NODE uses the node module rules. WEBPACK looks up modules from a special lookup map.
   *
   * `--module_resolution`. Default: `BROWSER`. Category: JS Modules.
   * Same flag as `module_resolution`.
   */
  moduleResolution?: EnumFlag<ResolutionMode>;
  /**
   * Prefixes to replace in ES6 import paths before resolving. module_resolution must be BROWSER_WITH_TRANSFORMED_PREFIXES to take effect.
   *
   * `--browser_resolver_prefix_replacements`.
   */
  browser_resolver_prefix_replacements?: string;
  /**
   * Prefixes to replace in ES6 import paths before resolving. module_resolution must be BROWSER_WITH_TRANSFORMED_PREFIXES to take effect.
   *
   * `--browser_resolver_prefix_replacements`.
   * Same flag as `browser_resolver_prefix_replacements`.
   */
  browserResolverPrefixReplacements?: string;
  /**
   * Ordered list of entries to look for in package.json files when processing modules with the NODE module resolution strategy (i.e. esnext:main,browser,main). Defaults to a list with the following entries: "browser", "module", "main".
   *
   * `--package_json_entry_names`. Category: JS Modules.
   */
  package_json_entry_names?: string;
  /**
   * Ordered list of entries to look for in package.json files when processing modules with the NODE module resolution strategy (i.e. esnext:main,browser,main). Defaults to a list with the following entries: "browser", "module", "main".
   *
   * `--package_json_entry_names`. Category: JS Modules.
   * Same flag as `package_json_entry_names`.
   */
  packageJsonEntryNames?: string;
  /**
   * Specifies format for error messages.
   *
   * `--error_format`. Default: `STANDARD`. Category: Warning and Error Management.
   */
  error_format?: EnumFlag<ErrorFormatOption>;
  /**
   * Specifies format for error messages.
   *
   * `--error_format`. Default: `STANDARD`. Category: Warning and Error Management.
   * Same flag as `error_format`.
   */
  errorFormat?: EnumFlag<ErrorFormatOption>;
  /**
   * Disables variable renaming. Cannot be used with ADVANCED optimizations.
   *
   * `--renaming`. Default: `true`.
   */
  renaming?: BooleanFlag;
  /**
   * Prints markdown formatted flag usage
   *
   * `--help_markdown`. Default: `false`. Hidden in --help.
   */
  help_markdown?: BooleanFlag;
  /**
   * Prints markdown formatted flag usage
   *
   * `--help_markdown`. Default: `false`. Hidden in --help.
   * Same flag as `help_markdown`.
   */
  helpMarkdown?: BooleanFlag;
  /**
   * Enable code instrumentation to perform code coverage analysis. Options are: 1. NONE (default) 2. LINE - Instrument code by line. 3. BRANCH - Instrument code by branch. 4. PRODUCTION - Function Instrumentation on compiled JS code.
   *
   * `--instrument_for_coverage_option`. Default: `NONE`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   */
  instrument_for_coverage_option?: string;
  /**
   * Enable code instrumentation to perform code coverage analysis. Options are: 1. NONE (default) 2. LINE - Instrument code by line. 3. BRANCH - Instrument code by branch. 4. PRODUCTION - Function Instrumentation on compiled JS code.
   *
   * `--instrument_for_coverage_option`. Default: `NONE`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   * Same flag as `instrument_for_coverage_option`.
   */
  instrumentForCoverageOption?: string;
  /**
   * Name of the global array used by production instrumentation. The array name should be declared as an extern so it is not renamed by the compiler. A function that parses the global array should also be included. This flag is to be used in tandem with --instrument_code=PRODUCTION
   *
   * `--production_instrumentation_array_name`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   */
  production_instrumentation_array_name?: string;
  /**
   * Name of the global array used by production instrumentation. The array name should be declared as an extern so it is not renamed by the compiler. A function that parses the global array should also be included. This flag is to be used in tandem with --instrument_code=PRODUCTION
   *
   * `--production_instrumentation_array_name`.
   * Outside the closure-rs port scope (docs/PORTING.md §2: instrumentation area; configures code instrumentation (jscomp/instrumentation/: CoverageInstrumentationPass, ProductionCoverageInstrumentationCallback)).
   * Same flag as `production_instrumentation_array_name`.
   */
  productionInstrumentationArrayName?: string;
  /**
   * Indicates what format the compiler should use for output chunks. GLOBAL_NAMESPACE is typically used in conjunction with --rename_prefix_namespace. ES_MODULES outputs chunks as proper modules with 'import' and 'export' statements.
   *
   * `--chunk_output_type`. Default: `GLOBAL_NAMESPACE`. Category: Code Splitting.
   */
  chunk_output_type?: EnumFlag<ChunkOutputType>;
  /**
   * Indicates what format the compiler should use for output chunks. GLOBAL_NAMESPACE is typically used in conjunction with --rename_prefix_namespace. ES_MODULES outputs chunks as proper modules with 'import' and 'export' statements.
   *
   * `--chunk_output_type`. Default: `GLOBAL_NAMESPACE`. Category: Code Splitting.
   * Same flag as `chunk_output_type`.
   */
  chunkOutputType?: EnumFlag<ChunkOutputType>;
  /**
   * Indicates that the compiler should allow dynamic import expressions. Dynamic import expressions are not yet fully supported and may lead to broken output code.
   *
   * `--allow_dynamic_import`. Default: `true`.
   */
  allow_dynamic_import?: BooleanFlag;
  /**
   * Indicates that the compiler should allow dynamic import expressions. Dynamic import expressions are not yet fully supported and may lead to broken output code.
   *
   * `--allow_dynamic_import`. Default: `true`.
   * Same flag as `allow_dynamic_import`.
   */
  allowDynamicImport?: BooleanFlag;
  /**
   * Instructs the compiler to replace dynamic imports expressions with a function call using the specified name. Allows dynamic import expressions to be externally polyfilled when the output language level does not natively support them. An alias of 'import' is allowed.
   *
   * `--dynamic_import_alias`. Category: JS Modules.
   */
  dynamic_import_alias?: string;
  /**
   * Instructs the compiler to replace dynamic imports expressions with a function call using the specified name. Allows dynamic import expressions to be externally polyfilled when the output language level does not natively support them. An alias of 'import' is allowed.
   *
   * `--dynamic_import_alias`. Category: JS Modules.
   * Same flag as `dynamic_import_alias`.
   */
  dynamicImportAlias?: string;
  /**
   * Assume that static (class-side) inheritance is not being used and that static methods will not be referenced via `this` or through subclasses. This enables optimizations that could break code that did those things.
   *
   * `--assume_static_inheritance_is_not_used`. Default: `true`. Category: Miscellaneous.
   */
  assume_static_inheritance_is_not_used?: BooleanFlag;
  /**
   * Assume that static (class-side) inheritance is not being used and that static methods will not be referenced via `this` or through subclasses. This enables optimizations that could break code that did those things.
   *
   * `--assume_static_inheritance_is_not_used`. Default: `true`. Category: Miscellaneous.
   * Same flag as `assume_static_inheritance_is_not_used`.
   */
  assumeStaticInheritanceIsNotUsed?: BooleanFlag;
  /**
   * Assume that prototype method enumeration is not being used. This allows the compiler to move a prototype method declaration into a deeper chunk without creating stub functions in a parent chunk.
   *
   * `--assume_no_prototype_method_enumeration`. Default: `false`.
   */
  assume_no_prototype_method_enumeration?: BooleanFlag;
  /**
   * Assume that prototype method enumeration is not being used. This allows the compiler to move a prototype method declaration into a deeper chunk without creating stub functions in a parent chunk.
   *
   * `--assume_no_prototype_method_enumeration`. Default: `false`.
   * Same flag as `assume_no_prototype_method_enumeration`.
   */
  assumeNoPrototypeMethodEnumeration?: BooleanFlag;
  /**
   * File containing the serialized version of the variable renaming map produced by a previous compilation
   *
   * `--variable_map_input_file`.
   */
  variable_map_input_file?: string;
  /**
   * File containing the serialized version of the variable renaming map produced by a previous compilation
   *
   * `--variable_map_input_file`.
   * Same flag as `variable_map_input_file`.
   */
  variableMapInputFile?: string;
  /**
   * File containing the serialized version of the property renaming map produced by a previous compilation
   *
   * `--property_map_input_file`.
   */
  property_map_input_file?: string;
  /**
   * File containing the serialized version of the property renaming map produced by a previous compilation
   *
   * `--property_map_input_file`.
   * Same flag as `property_map_input_file`.
   */
  propertyMapInputFile?: string;
  /**
   * Expected diagnostics in the format [(line,col)]CODE:regex. CODE is the JSCompiler DiagnosticType key. regex matches the description.
   *
   * `--expected_diagnostics`.
   * Repeatable: an array gives the flag once per item.
   */
  expected_diagnostics?: Repeatable<string>;
  /**
   * Expected diagnostics in the format [(line,col)]CODE:regex. CODE is the JSCompiler DiagnosticType key. regex matches the description.
   *
   * `--expected_diagnostics`.
   * Repeatable: an array gives the flag once per item.
   * Same flag as `expected_diagnostics`.
   */
  expectedDiagnostics?: Repeatable<string>;
}

/** One value of the @types/google-closure-compiler options object. */
export type CompileOption = string | boolean;

/** The options type of @types/google-closure-compiler: an argument array or a flags object. */
export type CompileOptions = string[] | {[key: string]: CompileOption | CompileOption[]};

/**
 * Options object accepted by `new compiler(...)`: the typed flags, plus any other key (passed
 * through as `--key=value`).
 */
export interface CompilerOptions extends CompilerFlags {
  [flag: string]: CompileOption | CompileOption[] | number | null | undefined;
}

// ---- compiler -----------------------------------------------------------------------------------

/** Shape of a compiler instance (the `Compiler` interface of @types/google-closure-compiler). */
export interface Compiler {
  /** The executable `run()` spawns: the closure-rs binary. */
  javaPath: string;
  logger: (...args: any[]) => void;
  spawnOptions: SpawnOptions & {[key: string]: any};
  run(callback?: (exitCode: number, stdout: string, stderr: string) => void): ChildProcess;
  getFullCommand(): string;
}

/**
 * Runs the closure-rs binary (google-closure-compiler's `compiler` class).
 *
 * ```ts
 * import ClosureCompiler from 'google-closure-compiler';
 * new ClosureCompiler({js: 'in.js', compilation_level: 'ADVANCED'})
 *   .run((exitCode, stdout, stderr) => { ... });
 * ```
 */
export class compiler implements Compiler {
  /**
   * @param args A flags object (see {@link CompilerFlags}) or an argument array passed verbatim.
   * @param extraCommandArgs JVM arguments in the official package; closure-rs runs no JVM and
   *   ignores them unless `JAR_PATH` is set.
   */
  constructor(args: CompilerOptions | string[], extraCommandArgs?: string[]);

  /**
   * null at runtime: closure-rs has no jar. Declared `string` as in @types/google-closure-compiler
   * (the official class has no such static at runtime either: there it is undefined).
   */
  static JAR_PATH: string;
  /** Path of the closure-rs binary. */
  static COMPILER_PATH: string;
  /** Path of the bundled contrib/ folder. */
  static CONTRIB_PATH: string;
  /** Path of the bundled externs/ folder. */
  static EXTERNS_PATH: string;

  /** The arguments `run()` passes to the binary. */
  commandArguments: string[];
  extraCommandArgs: string[] | undefined;
  /** null: no jar. If set (with `javaPath` pointing at java), `run()` runs that jar instead. */
  JAR_PATH: string | null;
  /** The executable `run()` spawns; defaults to the closure-rs binary. */
  javaPath: string;
  /** When set, called with the full command line before the process starts. */
  logger: (...args: any[]) => void;
  /** Options for child_process.spawn (undefined by default). */
  spawnOptions: SpawnOptions & {[key: string]: any};

  /**
   * Starts the compiler and returns the child process (write to its stdin to compile from stdin).
   * The callback gets the exit code and the collected stdout and stderr; for a non-zero exit code
   * stderr starts with the full command line.
   */
  run(callback?: (exitCode: number, stdout: string, stderr: string) => void): ChildProcess;
  /** The executable and its arguments, joined with spaces. */
  getFullCommand(): string;
  /** `msg` preceded by the full command line. */
  prependFullCommand(msg: string): string;
  /** `--key=value`, or `--key` when `val` is null or undefined; camelCase keys become snake_case. */
  formatArgument(key: string, val?: string | boolean | number | null): string;
}

export default compiler;

/** The executable `compiler` runs by default: the closure-rs binary (`'closure-rs'` on PATH if none is installed). */
export const javaPath: string;
/** Always null: closure-rs has no jar (the official package exports the jar's path). */
export const JAR_PATH: string | null;
/** Path of the closure-rs binary. */
export const COMPILER_PATH: string;
/** Path of the bundled contrib/ folder (contrib/externs, contrib/nodejs). */
export const CONTRIB_PATH: string;
/** Path of the bundled externs/ folder (the default externs). */
export const EXTERNS_PATH: string;

// ---- gulp and grunt (not implemented: calling them throws) --------------------------------------

/** A file record of the --json_streams format. */
export interface JSONStreamFile {
  path: string;
  src: string;
  srcmap?: string | undefined;
}

export interface GulpInitOptions {
  extraArguments?: string[];
}
export type LogFunction = (message: string) => void;
export interface GulpPluginOptions {
  streamMode?: string;
  logger?: LogFunction | {warn: LogFunction};
  pluginName?: string;
  requireStreamInput?: boolean;
  platform?: string | string[];
}
export type Transform = import('stream').Transform;
export interface CompilationStream extends Transform {
  platform: string;
  src(): this;
}

/**
 * The gulp plugin. Not implemented in closure-rs: calling it throws. The first signature is the
 * one @types/google-closure-compiler declares, the second the official package's current one.
 */
export function gulp(initOptions?: GulpInitOptions): (opts: CompileOptions, pluginOpts?: GulpPluginOptions) => CompilationStream;
export function gulp(compilationOptions: CompilerOptions | string[], pluginOptions?: GulpPluginOptions): CompilationStream;

/** The parts of grunt's IGrunt the grunt plugin uses. */
export interface PartialIGrunt {
  registerMultiTask(
    taskName: string,
    taskDescription: string,
    taskFunction: (this: any, ...args: any[]) => void,
  ): void;
  file: {
    write(filepath: string, contents: string | Buffer): void;
  };
  log: {
    ok(msg: string): any;
    warn(msg: string): any;
  };
  fail: {
    warn(error: string): void;
  };
}
export type GruntTaskFunction<IGrunt extends PartialIGrunt> = Parameters<IGrunt['registerMultiTask']>[2];
export type GruntPluginOptions = string[] | {
  platform?: string | string[];
  extraArguments?: string[];
  max_parallel_compilations?: number;
  /** @deprecated use max_parallel_compilations */
  compile_in_batches?: number;
};

/** The grunt plugin. Not implemented in closure-rs: calling it throws. */
export function grunt<IGrunt extends PartialIGrunt>(
  grunt: IGrunt,
  pluginOptions?: GruntPluginOptions,
): GruntTaskFunction<IGrunt>;
