/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/es6_collections.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!ReadonlyMap} obj
 * @return {!Array<*>}
 */
function closureSelfUseReadonlyMap(obj) {
  return [
    obj.forEach,
    obj.get,
    obj.has,
    obj.keys,
    obj.size,
    obj.entries(),
    obj.values()
  ];
}
globalThis['closureSelfUseReadonlyMap'] = closureSelfUseReadonlyMap;

/**
 * @param {!Map} obj
 * @return {!Array<*>}
 */
function closureSelfUseMap(obj) {
  return [
    obj.delete,
    obj.forEach,
    obj.getOrInsert,
    obj.getOrInsertComputed,
    obj.keys,
    obj.size,
    obj.clear(),
    obj.values()
  ];
}
globalThis['closureSelfUseMap'] = closureSelfUseMap;

/**
 * @param {!WeakMap} obj
 * @return {!Array<*>}
 */
function closureSelfUseWeakMap(obj) {
  return [
    obj.delete,
    obj.get,
    obj.getOrInsert,
    obj.getOrInsertComputed,
    obj.has,
    obj.set,
    obj.clear()
  ];
}
globalThis['closureSelfUseWeakMap'] = closureSelfUseWeakMap;

/**
 * @param {!SetLike} obj
 * @return {!Array<*>}
 */
function closureSelfUseSetLike(obj) {
  return [
    obj.has,
    obj.size,
    obj.keys()
  ];
}
globalThis['closureSelfUseSetLike'] = closureSelfUseSetLike;

/**
 * @param {!ReadonlySetLike} obj
 * @return {!Array<*>}
 */
function closureSelfUseReadonlySetLike(obj) {
  return [
    obj.has,
    obj.size,
    obj.keys()
  ];
}
globalThis['closureSelfUseReadonlySetLike'] = closureSelfUseReadonlySetLike;

/**
 * @param {!ReadonlySet} obj
 * @return {!Array<*>}
 */
function closureSelfUseReadonlySet(obj) {
  return [
    obj.forEach,
    obj.size,
    obj.union,
    obj.difference,
    obj.isSubsetOf,
    obj.isDisjointFrom,
    obj.entries(),
    obj.values()
  ];
}
globalThis['closureSelfUseReadonlySet'] = closureSelfUseReadonlySet;

/**
 * @param {!Set} obj
 * @return {!Array<*>}
 */
function closureSelfUseSet(obj) {
  return [
    obj.add,
    obj.forEach,
    obj.keys,
    obj.difference,
    obj.isSupersetOf,
    obj.size,
    obj.clear(),
    obj.values()
  ];
}
globalThis['closureSelfUseSet'] = closureSelfUseSet;

/**
 * @param {!WeakSet} obj
 * @return {!Array<*>}
 */
function closureSelfUseWeakSet(obj) {
  return [
    obj.add,
    obj.delete,
    obj.has,
    obj.clear()
  ];
}
globalThis['closureSelfUseWeakSet'] = closureSelfUseWeakSet;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Map.groupBy
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
