// Generated by corpus/d2/candidates/npm.collect.py for npm:petite-vue@0.4.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/petite-vue@0.4.1/package/dist/petite-vue.umd.js');
globalThis['petite-vue'] = pkg;
