/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/wicg_constructable_stylesheets.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!CSSStyleSheetInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseCSSStyleSheetInit(obj) {
  return [
    obj.media,
    obj.title,
    obj.alternate,
    obj.disabled,
    obj.baseURL
  ];
}
globalThis['closureSelfUseCSSStyleSheetInit'] = closureSelfUseCSSStyleSheetInit;

/**
 * @param {!CSSStyleSheet} obj
 * @return {!Array<*>}
 */
function closureSelfUseCSSStyleSheet(obj) {
  return [
    obj.replace('closure-self'),
    obj.replaceSync('closure-self')
  ];
}
globalThis['closureSelfUseCSSStyleSheet'] = closureSelfUseCSSStyleSheet;

/**
 * @param {!Document} obj
 * @return {!Array<*>}
 */
function closureSelfUseDocument(obj) {
  return [
    obj.adoptedStyleSheets
  ];
}
globalThis['closureSelfUseDocument'] = closureSelfUseDocument;

/**
 * @param {!ShadowRoot} obj
 * @return {!Array<*>}
 */
function closureSelfUseShadowRoot(obj) {
  return [
    obj.adoptedStyleSheets
  ];
}
globalThis['closureSelfUseShadowRoot'] = closureSelfUseShadowRoot;
