/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.pubsub.pubsub.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/pubsub/pubsub.js).
 * Requires goog.pubsub.PubSub and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_pubsub_PubSub');

const target = goog.require('goog.pubsub.PubSub');

goog.exportSymbol('goog.pubsub.PubSub', target);
goog.exportProperty(target.prototype, 'subscribe', target.prototype.subscribe);
goog.exportProperty(target.prototype, 'subscribeOnce', target.prototype.subscribeOnce);
goog.exportProperty(target.prototype, 'unsubscribe', target.prototype.unsubscribe);
goog.exportProperty(target.prototype, 'unsubscribeByKey', target.prototype.unsubscribeByKey);
