/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.color.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/color/color.js).
 * Requires goog.color and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_color');

const target = goog.require('goog.color');

goog.exportSymbol('goog.color.parse', target.parse);
goog.exportSymbol('goog.color.isValidColor', target.isValidColor);
goog.exportSymbol('goog.color.parseRgb', target.parseRgb);
goog.exportSymbol('goog.color.hexToRgbStyle', target.hexToRgbStyle);
goog.exportSymbol('goog.color.normalizeHex', target.normalizeHex);
goog.exportSymbol('goog.color.hexToRgb', target.hexToRgb);
goog.exportSymbol('goog.color.rgbToHex', target.rgbToHex);
goog.exportSymbol('goog.color.rgbArrayToHex', target.rgbArrayToHex);
