/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-dat.gui-0.7.9-pkg-cjs:
 * Node.js/AMD globals referenced by npm:dat.gui@0.7.9 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
