// Generated by corpus/d2/candidates/npm.collect.py for npm:timeago.js@4.0.2 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  cancel as e_cancel,
  format as e_format,
  register as e_register,
  render as e_render,
} from '../../../../corpus-cache/d2/npm/timeago.js@4.0.2/package/esm/index.js';
globalThis['cancel'] = e_cancel;
globalThis['format'] = e_format;
globalThis['register'] = e_register;
globalThis['render'] = e_render;
