// Generated by corpus/d2/candidates/npm.collect.py for npm:jsonc-parser@3.3.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  ParseErrorCode as e_ParseErrorCode,
  ScanError as e_ScanError,
  SyntaxKind as e_SyntaxKind,
  applyEdits as e_applyEdits,
  createScanner as e_createScanner,
  findNodeAtLocation as e_findNodeAtLocation,
  findNodeAtOffset as e_findNodeAtOffset,
  format as e_format,
  getLocation as e_getLocation,
  getNodePath as e_getNodePath,
  getNodeValue as e_getNodeValue,
  modify as e_modify,
  parse as e_parse,
  parseTree as e_parseTree,
  printParseErrorCode as e_printParseErrorCode,
  stripComments as e_stripComments,
  visit as e_visit,
} from '../../../../corpus-cache/d2/npm/jsonc-parser@3.3.1/package/lib/esm/main.js';
globalThis['ParseErrorCode'] = e_ParseErrorCode;
globalThis['ScanError'] = e_ScanError;
globalThis['SyntaxKind'] = e_SyntaxKind;
globalThis['applyEdits'] = e_applyEdits;
globalThis['createScanner'] = e_createScanner;
globalThis['findNodeAtLocation'] = e_findNodeAtLocation;
globalThis['findNodeAtOffset'] = e_findNodeAtOffset;
globalThis['format'] = e_format;
globalThis['getLocation'] = e_getLocation;
globalThis['getNodePath'] = e_getNodePath;
globalThis['getNodeValue'] = e_getNodeValue;
globalThis['modify'] = e_modify;
globalThis['parse'] = e_parse;
globalThis['parseTree'] = e_parseTree;
globalThis['printParseErrorCode'] = e_printParseErrorCode;
globalThis['stripComments'] = e_stripComments;
globalThis['visit'] = e_visit;
