// Generated by corpus/d2/candidates/npm.collect.py for npm:cytoscape@3.34.3 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/cytoscape@3.34.3/package/dist/cytoscape.esm.mjs';
globalThis['default'] = e_default;
