/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-cytoscape-3.34.3-pkg-esm:
 * Node.js/AMD globals referenced by npm:cytoscape@3.34.3 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;

/** @type {?} */
var module;
