// Generated by corpus/d2/candidates/npm.collect.py for npm:proxy-compare@3.0.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  affectedToPathList as e_affectedToPathList,
  createProxy as e_createProxy,
  getUntracked as e_getUntracked,
  isChanged as e_isChanged,
  markToTrack as e_markToTrack,
  replaceNewProxy as e_replaceNewProxy,
  trackMemo as e_trackMemo,
} from '../../../../corpus-cache/d2/npm/proxy-compare@3.0.1/package/dist/index.js';
globalThis['affectedToPathList'] = e_affectedToPathList;
globalThis['createProxy'] = e_createProxy;
globalThis['getUntracked'] = e_getUntracked;
globalThis['isChanged'] = e_isChanged;
globalThis['markToTrack'] = e_markToTrack;
globalThis['replaceNewProxy'] = e_replaceNewProxy;
globalThis['trackMemo'] = e_trackMemo;
