/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.tree.treecontrol.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/tree/treecontrol.js).
 * Requires goog.ui.tree.TreeControl and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_tree_TreeControl');

const target = goog.require('goog.ui.tree.TreeControl');

goog.exportSymbol('goog.ui.tree.TreeControl', target);
goog.exportSymbol('goog.ui.tree.TreeControl.defaultConfig', target.defaultConfig);
goog.exportProperty(target.prototype, 'getTree', target.prototype.getTree);
goog.exportProperty(target.prototype, 'getDepth', target.prototype.getDepth);
goog.exportProperty(target.prototype, 'reveal', target.prototype.reveal);
goog.exportProperty(target.prototype, 'hasFocus', target.prototype.hasFocus);
