/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/es6_proxy.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!ProxyHandler} obj
 * @return {!Array<*>}
 */
function closureSelfUseProxyHandler(obj) {
  return [
    obj.getPrototypeOf,
    obj.isExtensible,
    obj.defineProperty,
    obj.get,
    obj.ownKeys,
    obj.construct
  ];
}
globalThis['closureSelfUseProxyHandler'] = closureSelfUseProxyHandler;

/**
 * @param {!Proxy} obj
 * @return {!Array<*>}
 */
function closureSelfUseProxy(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseProxy'] = closureSelfUseProxy;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Proxy.revocable
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
