// Generated by corpus/d2/candidates/npm.collect.py for npm:idb@8.0.4 (ISC).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/idb@8.0.4/package/build/index.cjs');
globalThis['deleteDB'] = pkg.deleteDB;
globalThis['openDB'] = pkg.openDB;
globalThis['unwrap'] = pkg.unwrap;
globalThis['wrap'] = pkg.wrap;
