/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/es5.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!ObjectPropertyDescriptor} obj
 * @return {!Array<*>}
 */
function closureSelfUseObjectPropertyDescriptor(obj) {
  return [
    obj.value,
    obj.get,
    obj.set,
    obj.writable,
    obj.enumerable,
    obj.configurable
  ];
}
globalThis['closureSelfUseObjectPropertyDescriptor'] = closureSelfUseObjectPropertyDescriptor;

/**
 * @param {!JSONType} obj
 * @return {!Array<*>}
 */
function closureSelfUseJSONType(obj) {
  return [
    obj.parse,
    obj.stringify
  ];
}
globalThis['closureSelfUseJSONType'] = closureSelfUseJSONType;

/**
 * @param {!Function} obj
 * @return {!Array<*>}
 */
function closureSelfUseFunction(obj) {
  return [
    obj.bind
  ];
}
globalThis['closureSelfUseFunction'] = closureSelfUseFunction;

/**
 * @param {string} obj
 * @return {!Array<*>}
 */
function closureSelfUseString(obj) {
  return [
    obj.trim,
    obj.trimLeft,
    obj.trimRight
  ];
}
globalThis['closureSelfUseString'] = closureSelfUseString;

/**
 * @param {!Object} obj
 * @return {!Array<*>}
 */
function closureSelfUseObject(obj) {
  return [
    obj.toJSON()
  ];
}
globalThis['closureSelfUseObject'] = closureSelfUseObject;

/**
 * @param {!Date} obj
 * @return {!Array<*>}
 */
function closureSelfUseDate(obj) {
  return [
    obj.toISOString(),
    obj.toJSON()
  ];
}
globalThis['closureSelfUseDate'] = closureSelfUseDate;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Object.create,
    Object.defineProperty,
    Object.getOwnPropertyDescriptor,
    Object.keys,
    Object.getPrototypeOf,
    Object.preventExtensions,
    Object.freeze,
    Object.isExtensible,
    Object.isFrozen,
    JSON
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
