// Generated by corpus/d2/candidates/npm.collect.py for npm:throttle-debounce@5.0.2 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  debounce as e_debounce,
  throttle as e_throttle,
} from '../../../../corpus-cache/d2/npm/throttle-debounce@5.0.2/package/esm/index.js';
globalThis['debounce'] = e_debounce;
globalThis['throttle'] = e_throttle;
