/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.math.long.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/math/long.js).
 * Requires goog.math.Long and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_math_Long');

const target = goog.require('goog.math.Long');

goog.exportSymbol('goog.math.Long', target);
goog.exportProperty(target.prototype, 'toInt', target.prototype.toInt);
goog.exportProperty(target.prototype, 'toNumber', target.prototype.toNumber);
goog.exportProperty(target.prototype, 'isSafeInteger', target.prototype.isSafeInteger);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
