// Generated by corpus/d2/candidates/npm.collect.py for npm:effector@23.4.4 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/effector@23.4.4/package/effector.cjs.js');
globalThis['PRIVATE_API_DO_NOT_TOUCH_NO_SEMVER_SUPPORT'] = pkg.PRIVATE_API_DO_NOT_TOUCH_NO_SEMVER_SUPPORT;
globalThis['allSettled'] = pkg.allSettled;
globalThis['attach'] = pkg.attach;
globalThis['clearNode'] = pkg.clearNode;
globalThis['combine'] = pkg.combine;
globalThis['createApi'] = pkg.createApi;
globalThis['createDomain'] = pkg.createDomain;
globalThis['createEffect'] = pkg.createEffect;
globalThis['createEvent'] = pkg.createEvent;
globalThis['createNode'] = pkg.createNode;
globalThis['createStore'] = pkg.createStore;
globalThis['createWatch'] = pkg.createWatch;
globalThis['fork'] = pkg.fork;
globalThis['forward'] = pkg.forward;
globalThis['fromObservable'] = pkg.fromObservable;
globalThis['guard'] = pkg.guard;
globalThis['hydrate'] = pkg.hydrate;
globalThis['is'] = pkg.is;
globalThis['launch'] = pkg.launch;
globalThis['merge'] = pkg.merge;
globalThis['restore'] = pkg.restore;
globalThis['sample'] = pkg.sample;
globalThis['scopeBind'] = pkg.scopeBind;
globalThis['serialize'] = pkg.serialize;
globalThis['setGraphInspector'] = pkg.setGraphInspector;
globalThis['setInspector'] = pkg.setInspector;
globalThis['setStoreName'] = pkg.setStoreName;
globalThis['split'] = pkg.split;
globalThis['step'] = pkg.step;
globalThis['version'] = pkg.version;
globalThis['withFactory'] = pkg.withFactory;
globalThis['withRegion'] = pkg.withRegion;
