/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.structs.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/structs/structs.js).
 * Requires goog.structs and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_structs');

const target = goog.require('goog.structs');

goog.exportSymbol('goog.structs.getCount', target.getCount);
goog.exportSymbol('goog.structs.getValues', target.getValues);
goog.exportSymbol('goog.structs.getKeys', target.getKeys);
goog.exportSymbol('goog.structs.contains', target.contains);
goog.exportSymbol('goog.structs.isEmpty', target.isEmpty);
goog.exportSymbol('goog.structs.clear', target.clear);
goog.exportSymbol('goog.structs.filter', target.filter);
goog.exportSymbol('goog.structs.map', target.map);
