/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.fs.blob.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/fs/blob.js).
 * Requires goog.testing.fs.Blob and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_fs_Blob');

const target = goog.require('goog.testing.fs.Blob');

goog.exportSymbol('goog.testing.fs.Blob', target);
goog.exportProperty(target.prototype, 'slice', target.prototype.slice);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
goog.exportProperty(target.prototype, 'toArrayBuffer', target.prototype.toArrayBuffer);
goog.exportProperty(target.prototype, 'toDataUrl', target.prototype.toDataUrl);
