/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-trix-2.1.19-pkg-cjs:
 * Node.js/AMD globals referenced by npm:trix@2.1.19 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
