/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.db.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/db/db.js).
 * Requires goog.db and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_db');

const target = goog.require('goog.db');

goog.exportSymbol('goog.db.openDatabase', target.openDatabase);
goog.exportSymbol('goog.db.deleteDatabase', target.deleteDatabase);
