/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.net.jsloader.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/net/jsloader.js).
 * Requires goog.net.jsloader and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_net_jsloader');

const target = goog.require('goog.net.jsloader');

goog.exportSymbol('goog.net.jsloader.DEFAULT_TIMEOUT', target.DEFAULT_TIMEOUT);
goog.exportSymbol('goog.net.jsloader.safeLoadMany', target.safeLoadMany);
goog.exportSymbol('goog.net.jsloader.safeLoad', target.safeLoad);
goog.exportSymbol('goog.net.jsloader.safeLoadAndVerify', target.safeLoadAndVerify);
goog.exportSymbol('goog.net.jsloader.ErrorCode', target.ErrorCode);
goog.exportSymbol('goog.net.jsloader.Error', target.Error);
