// Generated by corpus/d2/candidates/npm.collect.py for npm:choices.js@11.2.4 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/choices.js@11.2.4/package/public/assets/scripts/choices.mjs';
globalThis['default'] = e_default;
