// Generated by corpus/d2/candidates/npm.collect.py for npm:uplot@1.6.32 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/uplot@1.6.32/package/dist/uPlot.cjs.js');
globalThis['uplot'] = pkg;
