/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.positioning.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/positioning/positioning.js).
 * Requires goog.positioning and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_positioning');

const target = goog.require('goog.positioning');

goog.exportSymbol('goog.positioning.CornerBit', target.CornerBit);
goog.exportSymbol('goog.positioning.Corner', target.Corner);
goog.exportSymbol('goog.positioning.Overflow', target.Overflow);
goog.exportSymbol('goog.positioning.OverflowStatus', target.OverflowStatus);
goog.exportSymbol('goog.positioning.positionAtAnchor', target.positionAtAnchor);
goog.exportSymbol('goog.positioning.getOffsetParentPageOffset', target.getOffsetParentPageOffset);
goog.exportSymbol('goog.positioning.positionAtCoordinate', target.positionAtCoordinate);
goog.exportSymbol('goog.positioning.getPositionAtCoordinate', target.getPositionAtCoordinate);
