/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-big.js-7.0.1.
 *
 * The library's own tests run uncompiled against the compiled big.js@7.0.1, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype.DP;
/** @type {?} */
Object.prototype.NE;
/** @type {?} */
Object.prototype.PE;
/** @type {?} */
Object.prototype.RM;
/** @type {?} */
Object.prototype.abs;
/** @type {?} */
Object.prototype.c;
/** @type {?} */
Object.prototype.cmp;
/** @type {?} */
Object.prototype.div;
/** @type {?} */
Object.prototype.e;
/** @type {?} */
Object.prototype.eq;
/** @type {?} */
Object.prototype.for;
/** @type {?} */
Object.prototype.gt;
/** @type {?} */
Object.prototype.gte;
/** @type {?} */
Object.prototype.length;
/** @type {?} */
Object.prototype.lt;
/** @type {?} */
Object.prototype.lte;
/** @type {?} */
Object.prototype.minus;
/** @type {?} */
Object.prototype.mod;
/** @type {?} */
Object.prototype.neg;
/** @type {?} */
Object.prototype.plus;
/** @type {?} */
Object.prototype.pow;
/** @type {?} */
Object.prototype.prec;
/** @type {?} */
Object.prototype.replace;
/** @type {?} */
Object.prototype.round;
/** @type {?} */
Object.prototype.s;
/** @type {?} */
Object.prototype.sqrt;
/** @type {?} */
Object.prototype.strict;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.times;
/** @type {?} */
Object.prototype.toExponential;
/** @type {?} */
Object.prototype.toFixed;
/** @type {?} */
Object.prototype.toNumber;
/** @type {?} */
Object.prototype.toPrecision;
