// closure-rs D2 whole-program case whole-program-big.js-7.0.1: runs the own test suite of
// big.js@7.0.1 (MikeMcl/big.js @ e19cc83cb965) against a compiled output.
//   node corpus/d2/shims/whole-program-big.js-7.0.1/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-big.js-7.0.1/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-big.js-7.0.1",
  "global": "Big",
  "testDir": "corpus-cache/d2/whole-program/big.js@7.0.1/repo",
  "framework": "custom",
  "modules": {
    "../big": {
      "path": []
    }
  },
  "expectTests": 17,
  register(h) {
    // Same files, in the same order, as the upstream runner test/runner.js (list parsed from it).
    const list = [...h.read("test/runner.js").match(/\[([^\]]*)\]\s*\.forEach/)[1].matchAll(/'([^']+)'/g)].map((m) => m[1]);
    h.require("test/test.js");
    for (const name of list) {
      h.test(`test/methods/${name}.js`, () => {
        h.require(`test/methods/${name}.js`);
        const [passed, count] = globalThis.test.result;
        if (count === 0 || passed !== count) throw new Error(`${passed} of ${count} assertions passed`);
      });
    }
  },
});
