// Generated by corpus/d2/candidates/npm.collect.py for npm:katex@0.19.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  ParseError as e_ParseError,
  SETTINGS_SCHEMA as e_SETTINGS_SCHEMA,
  __defineFunction as e___defineFunction,
  __defineMacro as e___defineMacro,
  __defineSymbol as e___defineSymbol,
  __domTree as e___domTree,
  __parse as e___parse,
  __renderToDomTree as e___renderToDomTree,
  __renderToHTMLTree as e___renderToHTMLTree,
  __setFontMetrics as e___setFontMetrics,
  default as e_default,
  render as e_render,
  renderToString as e_renderToString,
  version as e_version,
} from '../../../../corpus-cache/d2/npm/katex@0.19.0/package/dist/katex.mjs';
globalThis['ParseError'] = e_ParseError;
globalThis['SETTINGS_SCHEMA'] = e_SETTINGS_SCHEMA;
globalThis['__defineFunction'] = e___defineFunction;
globalThis['__defineMacro'] = e___defineMacro;
globalThis['__defineSymbol'] = e___defineSymbol;
globalThis['__domTree'] = e___domTree;
globalThis['__parse'] = e___parse;
globalThis['__renderToDomTree'] = e___renderToDomTree;
globalThis['__renderToHTMLTree'] = e___renderToHTMLTree;
globalThis['__setFontMetrics'] = e___setFontMetrics;
globalThis['default'] = e_default;
globalThis['render'] = e_render;
globalThis['renderToString'] = e_renderToString;
globalThis['version'] = e_version;
