// Generated by corpus/d2/candidates/npm.collect.py for npm:fast-json-patch@3.1.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/fast-json-patch@3.1.1/package/index.js');
globalThis['JsonPatchError'] = pkg.JsonPatchError;
globalThis['deepClone'] = pkg.deepClone;
globalThis['escapePathComponent'] = pkg.escapePathComponent;
globalThis['unescapePathComponent'] = pkg.unescapePathComponent;
