/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-acorn-walk-8.3.5-pkg-cjs:
 * Node.js/AMD globals referenced by npm:acorn-walk@8.3.5 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
