// Generated by corpus/d2/candidates/npm.collect.py for npm:entities@8.1.0 (BSD-2-Clause).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  DecodingMode as e_DecodingMode,
  EncodingMode as e_EncodingMode,
  EntityDecoder as e_EntityDecoder,
  EntityLevel as e_EntityLevel,
  decode as e_decode,
  decodeHTML as e_decodeHTML,
  decodeHTMLAttribute as e_decodeHTMLAttribute,
  decodeHTMLStrict as e_decodeHTMLStrict,
  decodeXML as e_decodeXML,
  decodeXMLStrict as e_decodeXMLStrict,
  encode as e_encode,
  encodeHTML as e_encodeHTML,
  encodeNonAsciiHTML as e_encodeNonAsciiHTML,
  encodeXML as e_encodeXML,
  escape as e_escape,
  escapeAttribute as e_escapeAttribute,
  escapeText as e_escapeText,
  escapeUTF8 as e_escapeUTF8,
} from '../../../../corpus-cache/d2/npm/entities@8.1.0/package/dist/index.js';
globalThis['DecodingMode'] = e_DecodingMode;
globalThis['EncodingMode'] = e_EncodingMode;
globalThis['EntityDecoder'] = e_EntityDecoder;
globalThis['EntityLevel'] = e_EntityLevel;
globalThis['decode'] = e_decode;
globalThis['decodeHTML'] = e_decodeHTML;
globalThis['decodeHTMLAttribute'] = e_decodeHTMLAttribute;
globalThis['decodeHTMLStrict'] = e_decodeHTMLStrict;
globalThis['decodeXML'] = e_decodeXML;
globalThis['decodeXMLStrict'] = e_decodeXMLStrict;
globalThis['encode'] = e_encode;
globalThis['encodeHTML'] = e_encodeHTML;
globalThis['encodeNonAsciiHTML'] = e_encodeNonAsciiHTML;
globalThis['encodeXML'] = e_encodeXML;
globalThis['escape'] = e_escape;
globalThis['escapeAttribute'] = e_escapeAttribute;
globalThis['escapeText'] = e_escapeText;
globalThis['escapeUTF8'] = e_escapeUTF8;
