/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.container.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/container.js).
 * Requires goog.ui.Container and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_Container');

const target = goog.require('goog.ui.Container');

goog.exportSymbol('goog.ui.Container', target);
goog.exportSymbol('goog.ui.Container.EventType', target.EventType);
goog.exportSymbol('goog.ui.Container.Orientation', target.Orientation);
goog.exportProperty(target.prototype, 'getKeyEventTarget', target.prototype.getKeyEventTarget);
goog.exportProperty(target.prototype, 'setKeyEventTarget', target.prototype.setKeyEventTarget);
goog.exportProperty(target.prototype, 'getKeyHandler', target.prototype.getKeyHandler);
goog.exportProperty(target.prototype, 'getRenderer', target.prototype.getRenderer);
