/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-camelcase-9.0.0.
 *
 * The library's own tests run uncompiled against the compiled camelcase@9.0.0, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype.capitalizeAfterNumber;
/** @type {?} */
Object.prototype.locale;
/** @type {?} */
Object.prototype.pascalCase;
/** @type {?} */
Object.prototype.preserveConsecutiveUppercase;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.toLocaleLowerCase;
/** @type {?} */
Object.prototype.toLocaleUpperCase;
