// closure-rs D2 whole-program case whole-program-camelcase-9.0.0: runs the own test suite of
// camelcase@9.0.0 (sindresorhus/camelcase @ 8596a65fcbfe) against a compiled output.
//   node corpus/d2/shims/whole-program-camelcase-9.0.0/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-camelcase-9.0.0/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-camelcase-9.0.0",
  "global": "camelCase",
  "testDir": "corpus-cache/d2/whole-program/camelcase@9.0.0/repo",
  "framework": "ava",
  "files": [
    "test.js"
  ],
  "modules": {
    "./index.js": {
      "path": []
    }
  },
  "expectTests": 20
});
