// Generated by corpus/d2/candidates/npm.collect.py for npm:throttle-debounce@5.0.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/throttle-debounce@5.0.2/package/cjs/index.js');
globalThis['debounce'] = pkg.debounce;
globalThis['throttle'] = pkg.throttle;
