/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/nonstandard_selection.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Selection} obj
 * @return {!Array<*>}
 */
function closureSelfUseSelection(obj) {
  return [
    obj.baseNode,
    obj.baseOffset,
    obj.extentNode,
    obj.selectionLanguageChange,
    obj.clear,
    obj.createRange,
    obj.modify('closure-self', 'closure-self', 'closure-self'),
    obj.createRangeCollection()
  ];
}
globalThis['closureSelfUseSelection'] = closureSelfUseSelection;

/**
 * @param {!Document} obj
 * @return {!Array<*>}
 */
function closureSelfUseDocument(obj) {
  return [
    obj.selection
  ];
}
globalThis['closureSelfUseDocument'] = closureSelfUseDocument;
