// Generated by corpus/d2/candidates/npm.collect.py for npm:@socket.io/component-emitter@3.1.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/@socket.io/component-emitter@3.1.2/package/lib/cjs/index.js');
globalThis['Emitter'] = pkg.Emitter;
