// Generated by corpus/d2/candidates/npm.collect.py for npm:signature_pad@5.1.4 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/signature_pad@5.1.4/package/dist/signature_pad.umd.js');
globalThis['signature_pad'] = pkg;
