/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-signature_pad-5.1.4-pkg-cjs:
 * Node.js/AMD globals referenced by npm:signature_pad@5.1.4 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
