// Generated by corpus/d2/candidates/npm.collect.py for npm:navigo@8.11.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/navigo@8.11.1/package/lib/es/index.js';
globalThis['default'] = e_default;
