// Generated by corpus/d2/candidates/npm.collect.py for npm:countup.js@2.10.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  CountUp as e_CountUp,
} from '../../../../corpus-cache/d2/npm/countup.js@2.10.1/package/dist/countUp.min.js';
globalThis['CountUp'] = e_CountUp;
