// Generated by corpus/d2/candidates/npm.collect.py for npm:mustache@4.2.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/mustache@4.2.0/package/mustache.mjs';
globalThis['default'] = e_default;
