// Generated by corpus/d2/candidates/npm.collect.py for npm:katex@0.19.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/katex@0.19.0/package/dist/katex.js');
globalThis['katex'] = pkg.katex;
globalThis['katex'] = pkg;
