/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-katex-0.19.0-pkg-cjs:
 * Node.js/AMD globals referenced by npm:katex@0.19.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
