// Generated by corpus/d2/candidates/npm.collect.py for npm:eventemitter3@5.0.4 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/eventemitter3@5.0.4/package/index.js');
globalThis['eventemitter3'] = pkg;
