/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.vec.mat4f.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/vec/mat4f.js).
 * Requires goog.vec.mat4f and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_vec_mat4f');

const target = goog.require('goog.vec.mat4f');

goog.exportSymbol('goog.vec.mat4f.create', target.create);
goog.exportSymbol('goog.vec.mat4f.createIdentity', target.createIdentity);
goog.exportSymbol('goog.vec.mat4f.setFromValues', target.setFromValues);
goog.exportSymbol('goog.vec.mat4f.setFromMat4f', target.setFromMat4f);
goog.exportSymbol('goog.vec.mat4f.setFromMat4d', target.setFromMat4d);
goog.exportSymbol('goog.vec.mat4f.setFromArray', target.setFromArray);
goog.exportSymbol('goog.vec.mat4f.getElement', target.getElement);
goog.exportSymbol('goog.vec.mat4f.setElement', target.setElement);
