/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/fetchapi.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Headers} obj
 * @return {!Array<*>}
 */
function closureSelfUseHeaders(obj) {
  return [
    obj.delete,
    obj.entries,
    obj.get,
    obj.has,
    obj.keys,
    obj.values,
    obj.append('closure-self', 'closure-self'),
    obj.getSetCookie()
  ];
}
globalThis['closureSelfUseHeaders'] = closureSelfUseHeaders;

/**
 * @param {!Body} obj
 * @return {!Array<*>}
 */
function closureSelfUseBody(obj) {
  return [
    obj.bodyUsed,
    obj.blob,
    obj.bytes,
    obj.formData,
    obj.json,
    obj.arrayBuffer(),
    obj.text()
  ];
}
globalThis['closureSelfUseBody'] = closureSelfUseBody;

/**
 * @param {!Request} obj
 * @return {!Array<*>}
 */
function closureSelfUseRequest(obj) {
  return [
    obj.bodyUsed,
    obj.json,
    obj.url,
    obj.referrer,
    obj.cache,
    obj.keepalive,
    obj.arrayBuffer(),
    obj.clone()
  ];
}
globalThis['closureSelfUseRequest'] = closureSelfUseRequest;

/**
 * @param {!RequestInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseRequestInit(obj) {
  return [
    obj.method,
    obj.body,
    obj.mode,
    obj.cache,
    obj.signal,
    obj.window
  ];
}
globalThis['closureSelfUseRequestInit'] = closureSelfUseRequestInit;

/**
 * @param {!Response} obj
 * @return {!Array<*>}
 */
function closureSelfUseResponse(obj) {
  return [
    obj.bodyUsed,
    obj.formData,
    obj.type,
    obj.redirected,
    obj.statusText,
    obj.trailer,
    obj.arrayBuffer(),
    obj.clone()
  ];
}
globalThis['closureSelfUseResponse'] = closureSelfUseResponse;

/**
 * @param {!ResponseInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseResponseInit(obj) {
  return [
    obj.status,
    obj.statusText,
    obj.headers
  ];
}
globalThis['closureSelfUseResponseInit'] = closureSelfUseResponseInit;

/**
 * @param {!Window} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindow(obj) {
  return [
    obj.fetch
  ];
}
globalThis['closureSelfUseWindow'] = closureSelfUseWindow;

/**
 * @param {!WorkerGlobalScope} obj
 * @return {!Array<*>}
 */
function closureSelfUseWorkerGlobalScope(obj) {
  return [
    obj.fetch
  ];
}
globalThis['closureSelfUseWorkerGlobalScope'] = closureSelfUseWorkerGlobalScope;

/**
 * @param {!WorkerOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseWorkerOptions(obj) {
  return [
    obj.credentials
  ];
}
globalThis['closureSelfUseWorkerOptions'] = closureSelfUseWorkerOptions;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Response.redirect,
    fetch,
    Response.error()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!ReferrerPolicy} t0
 * @param {!RequestInfo} t1
 * @param {!RequestMode} t2
 * @param {!ResponseType} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
