/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/asynccontext.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!AsyncContext.VariableOpts} obj
 * @return {!Array<*>}
 */
function closureSelfUseAsyncContextVariableOpts(obj) {
  return [
    obj.name,
    obj.defaultValue
  ];
}
globalThis['closureSelfUseAsyncContextVariableOpts'] = closureSelfUseAsyncContextVariableOpts;

/**
 * @param {!AsyncContext.Variable} obj
 * @return {!Array<*>}
 */
function closureSelfUseAsyncContextVariable(obj) {
  return [
    obj.name,
    obj.run,
    obj.get()
  ];
}
globalThis['closureSelfUseAsyncContextVariable'] = closureSelfUseAsyncContextVariable;

/**
 * @param {!AsyncContext.Snapshot} obj
 * @return {!Array<*>}
 */
function closureSelfUseAsyncContextSnapshot(obj) {
  return [
    obj.run
  ];
}
globalThis['closureSelfUseAsyncContextSnapshot'] = closureSelfUseAsyncContextSnapshot;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    AsyncContext.Snapshot.wrap
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
