/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/weblocksapi.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Lock} obj
 * @return {!Array<*>}
 */
function closureSelfUseLock(obj) {
  return [
    obj.name,
    obj.mode
  ];
}
globalThis['closureSelfUseLock'] = closureSelfUseLock;

/**
 * @param {!LockManager} obj
 * @return {!Array<*>}
 */
function closureSelfUseLockManager(obj) {
  return [
    obj.request,
    obj.query()
  ];
}
globalThis['closureSelfUseLockManager'] = closureSelfUseLockManager;

/**
 * @param {!Navigator} obj
 * @return {!Array<*>}
 */
function closureSelfUseNavigator(obj) {
  return [
    obj.locks
  ];
}
globalThis['closureSelfUseNavigator'] = closureSelfUseNavigator;

/**
 * @param {!WorkerNavigator} obj
 * @return {!Array<*>}
 */
function closureSelfUseWorkerNavigator(obj) {
  return [
    obj.locks
  ];
}
globalThis['closureSelfUseWorkerNavigator'] = closureSelfUseWorkerNavigator;

/**
 * @param {!LockMode} t0
 * @param {!LockInfo} t1
 * @param {!LockManagerSnapshot} t2
 * @param {!LockGrantedCallback} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
