// Generated by corpus/d2/candidates/npm.collect.py for npm:@hotwired/stimulus@3.2.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/@hotwired/stimulus@3.2.2/package/dist/stimulus.umd.js');
globalThis['Application'] = pkg.Application;
globalThis['AttributeObserver'] = pkg.AttributeObserver;
globalThis['Context'] = pkg.Context;
globalThis['Controller'] = pkg.Controller;
globalThis['ElementObserver'] = pkg.ElementObserver;
globalThis['IndexedMultimap'] = pkg.IndexedMultimap;
globalThis['Multimap'] = pkg.Multimap;
globalThis['SelectorObserver'] = pkg.SelectorObserver;
globalThis['StringMapObserver'] = pkg.StringMapObserver;
globalThis['TokenListObserver'] = pkg.TokenListObserver;
globalThis['ValueListObserver'] = pkg.ValueListObserver;
globalThis['add'] = pkg.add;
globalThis['defaultSchema'] = pkg.defaultSchema;
globalThis['del'] = pkg.del;
globalThis['fetch'] = pkg.fetch;
globalThis['prune'] = pkg.prune;
