/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-hotwired__stimulus-3.2.2-pkg-cjs:
 * Node.js/AMD globals referenced by npm:@hotwired/stimulus@3.2.2 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
