/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.format.internationalizedemailaddress.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/format/internationalizedemailaddress.js).
 * Requires goog.format.InternationalizedEmailAddress and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_format_InternationalizedEmailAddress');

const target = goog.require('goog.format.InternationalizedEmailAddress');

goog.exportSymbol('goog.format.InternationalizedEmailAddress', target);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.isValidLocalPartSpec', target.isValidLocalPartSpec);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.isValidDomainPartSpec', target.isValidDomainPartSpec);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.isValidAddress', target.isValidAddress);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.isValidAddrSpec', target.isValidAddrSpec);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.parseList', target.parseList);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.parse', target.parse);
goog.exportSymbol('goog.format.InternationalizedEmailAddress.isAddressSeparator', target.isAddressSeparator);
goog.exportProperty(target.prototype, 'isValid', target.prototype.isValid);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
