/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.locale.timezonedetection.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/locale/timezonedetection.js).
 * Requires goog.locale.timeZoneDetection and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_locale_timeZoneDetection');

const target = goog.require('goog.locale.timeZoneDetection');

goog.exportSymbol('goog.locale.timeZoneDetection.useNativeTimezoneDetectionForTesting', target.useNativeTimezoneDetectionForTesting);
goog.exportSymbol('goog.locale.timeZoneDetection.getFingerprint', target.getFingerprint);
goog.exportSymbol('goog.locale.timeZoneDetection.detectTimeZone', target.detectTimeZone);
goog.exportSymbol('goog.locale.timeZoneDetection.getTimeZoneList', target.getTimeZoneList);
