// Generated by corpus/d2/candidates/npm.collect.py for npm:i18next@26.4.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/i18next@26.4.2/package/dist/cjs/i18next.js');
globalThis['i18next'] = pkg;
