/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-xpcdemo.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/demos/xpc/xpcdemo.js).
 * Requires xpcdemo and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.xpcdemo');

const target = goog.require('xpcdemo');

goog.exportSymbol('xpcdemo.initOuter', target.initOuter);
goog.exportSymbol('xpcdemo.initInner', target.initInner);
goog.exportSymbol('xpcdemo.teardown', target.teardown);
goog.exportSymbol('xpcdemo.log', target.log);
goog.exportSymbol('xpcdemo.ping', target.ping);
goog.exportSymbol('xpcdemo.startMousemoveForwarding', target.startMousemoveForwarding);
goog.exportSymbol('xpcdemo.stopMousemoveForwarding', target.stopMousemoveForwarding);
goog.exportSymbol('xpcdemo.sendN', target.sendN);
