/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.parallelclosuretestsuite.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/parallel_closure_test_suite.js).
 * Requires goog.testing.parallelClosureTestSuite and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_parallelClosureTestSuite');

const target = goog.require('goog.testing.parallelClosureTestSuite');

goog.exportSymbol('goog.testing.parallelClosureTestSuite', target);
