/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.memoize.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/memoize/memoize.js).
 * Requires goog.memoize and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_memoize');

const target = goog.require('goog.memoize');

goog.exportSymbol('goog.memoize', target);
goog.exportSymbol('goog.memoize.clearCache', target.clearCache);
goog.exportSymbol('goog.memoize.simpleSerializer', target.simpleSerializer);
