// Generated by corpus/d2/candidates/npm.collect.py for npm:filesize@11.0.25 (BSD-3-Clause).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/filesize@11.0.25/package/dist/filesize.cjs');
globalThis['filesize'] = pkg.filesize;
globalThis['partial'] = pkg.partial;
