// Generated by corpus/d2/candidates/npm.collect.py for npm:web-streams-polyfill@4.3.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/web-streams-polyfill@4.3.0/package/dist/ponyfill.js');
globalThis['web-streams-polyfill'] = pkg;
