// Generated by corpus/d2/candidates/npm.collect.py for npm:@popperjs/core@2.11.8 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/@popperjs/core@2.11.8/package/dist/cjs/popper.js');
globalThis['applyStyles'] = pkg.applyStyles;
globalThis['arrow'] = pkg.arrow;
globalThis['computeStyles'] = pkg.computeStyles;
globalThis['createPopper'] = pkg.createPopper;
globalThis['createPopperLite'] = pkg.createPopperLite;
globalThis['defaultModifiers'] = pkg.defaultModifiers;
globalThis['detectOverflow'] = pkg.detectOverflow;
globalThis['eventListeners'] = pkg.eventListeners;
globalThis['flip'] = pkg.flip;
globalThis['hide'] = pkg.hide;
globalThis['offset'] = pkg.offset;
globalThis['popperGenerator'] = pkg.popperGenerator;
globalThis['popperOffsets'] = pkg.popperOffsets;
globalThis['preventOverflow'] = pkg.preventOverflow;
