/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-moment-2.31.0-pkg-esm:
 * Node.js/AMD globals referenced by npm:moment@2.31.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var module;

/** @type {?} */
var require;
