/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-numeral-2.0.6-pkg-cjs:
 * Node.js/AMD globals referenced by npm:numeral@2.0.6 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
