/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-xstate-5.33.2-pkg-esm:
 * Node.js/AMD globals referenced by npm:xstate@5.33.2 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;
