/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.labs.useragent.browser.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/useragent/browser.js).
 * Requires goog.labs.userAgent.browser and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_labs_userAgent_browser');

const target = goog.require('goog.labs.userAgent.browser');

goog.exportSymbol('goog.labs.userAgent.browser.Brand', target.Brand);
goog.exportSymbol('goog.labs.userAgent.browser.isOpera', target.isOpera);
goog.exportSymbol('goog.labs.userAgent.browser.isIE', target.isIE);
goog.exportSymbol('goog.labs.userAgent.browser.isEdge', target.isEdge);
goog.exportSymbol('goog.labs.userAgent.browser.isEdgeChromium', target.isEdgeChromium);
goog.exportSymbol('goog.labs.userAgent.browser.isOperaChromium', target.isOperaChromium);
goog.exportSymbol('goog.labs.userAgent.browser.isFirefox', target.isFirefox);
goog.exportSymbol('goog.labs.userAgent.browser.isSafari', target.isSafari);
