/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.vec.mat4.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/vec/mat4.js).
 * Requires goog.vec.Mat4 and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_vec_Mat4');

const target = goog.require('goog.vec.Mat4');

goog.exportSymbol('goog.vec.Mat4.createFloat32', target.createFloat32);
goog.exportSymbol('goog.vec.Mat4.createFloat64', target.createFloat64);
goog.exportSymbol('goog.vec.Mat4.createNumber', target.createNumber);
goog.exportSymbol('goog.vec.Mat4.createFloat32Identity', target.createFloat32Identity);
goog.exportSymbol('goog.vec.Mat4.createFloat64Identity', target.createFloat64Identity);
goog.exportSymbol('goog.vec.Mat4.createNumberIdentity', target.createNumberIdentity);
goog.exportSymbol('goog.vec.Mat4.createFloat32FromArray', target.createFloat32FromArray);
goog.exportSymbol('goog.vec.Mat4.createFloat32FromValues', target.createFloat32FromValues);
