// Generated by corpus/d2/candidates/npm.collect.py for npm:dropzone@6.3.5 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Dropzone as e_Dropzone,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/dropzone@6.3.5/package/dist/dropzone.mjs';
globalThis['Dropzone'] = e_Dropzone;
globalThis['default'] = e_default;
