// Generated by corpus/d2/candidates/npm.collect.py for npm:roughjs@4.6.6 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/roughjs@4.6.6/package/bundled/rough.cjs.js');
globalThis['roughjs'] = pkg;
