/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.storage.storage.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/storage/storage.js).
 * Requires goog.storage.Storage and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_storage_Storage');

const target = goog.require('goog.storage.Storage');

goog.exportSymbol('goog.storage.Storage', target);
goog.exportProperty(target.prototype, 'set', target.prototype.set);
goog.exportProperty(target.prototype, 'get', target.prototype.get);
goog.exportProperty(target.prototype, 'remove', target.prototype.remove);
