/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.events.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/events/events.js).
 * Requires goog.testing.events and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_events');

const target = goog.require('goog.testing.events');

goog.exportSymbol('goog.testing.events.Event', target.Event);
goog.exportSymbol('goog.testing.events.fireClickSequence', target.fireClickSequence);
goog.exportSymbol('goog.testing.events.fireDoubleClickSequence', target.fireDoubleClickSequence);
goog.exportSymbol('goog.testing.events.fireKeySequence', target.fireKeySequence);
goog.exportSymbol('goog.testing.events.fireNonAsciiKeySequence', target.fireNonAsciiKeySequence);
goog.exportSymbol('goog.testing.events.fireMouseEnterEvent', target.fireMouseEnterEvent);
goog.exportSymbol('goog.testing.events.fireMouseLeaveEvent', target.fireMouseLeaveEvent);
goog.exportSymbol('goog.testing.events.fireMouseOverEvent', target.fireMouseOverEvent);
