/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/whatwg_file_system.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!FileSystemHandle} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemHandle(obj) {
  return [
    obj.kind,
    obj.name,
    obj.isSameEntry
  ];
}
globalThis['closureSelfUseFileSystemHandle'] = closureSelfUseFileSystemHandle;

/**
 * @param {!FileSystemCreateWritableOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemCreateWritableOptions(obj) {
  return [
    obj.keepExistingData
  ];
}
globalThis['closureSelfUseFileSystemCreateWritableOptions'] = closureSelfUseFileSystemCreateWritableOptions;

/**
 * @param {!FileSystemFileHandle} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemFileHandle(obj) {
  return [
    obj.createWritable,
    obj.createSyncAccessHandle,
    obj.getFile(),
    obj.getUniqueId()
  ];
}
globalThis['closureSelfUseFileSystemFileHandle'] = closureSelfUseFileSystemFileHandle;

/**
 * @param {!FileSystemGetFileOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemGetFileOptions(obj) {
  return [
    obj.create
  ];
}
globalThis['closureSelfUseFileSystemGetFileOptions'] = closureSelfUseFileSystemGetFileOptions;

/**
 * @param {!FileSystemGetDirectoryOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemGetDirectoryOptions(obj) {
  return [
    obj.create
  ];
}
globalThis['closureSelfUseFileSystemGetDirectoryOptions'] = closureSelfUseFileSystemGetDirectoryOptions;

/**
 * @param {!FileSystemRemoveOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemRemoveOptions(obj) {
  return [
    obj.recursive
  ];
}
globalThis['closureSelfUseFileSystemRemoveOptions'] = closureSelfUseFileSystemRemoveOptions;

/**
 * @param {!FileSystemDirectoryHandle} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemDirectoryHandle(obj) {
  return [
    obj.getDirectoryHandle,
    obj.removeEntry,
    obj.resolve,
    obj.entries,
    obj.values,
    obj.getFileHandle('closure-self'),
    obj.keys()
  ];
}
globalThis['closureSelfUseFileSystemDirectoryHandle'] = closureSelfUseFileSystemDirectoryHandle;

/**
 * @param {!WriteParams} obj
 * @return {!Array<*>}
 */
function closureSelfUseWriteParams(obj) {
  return [
    obj.type,
    obj.size,
    obj.position,
    obj.data
  ];
}
globalThis['closureSelfUseWriteParams'] = closureSelfUseWriteParams;

/**
 * @param {!FileSystemWritableFileStream} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemWritableFileStream(obj) {
  return [
    obj.write,
    obj.seek(1),
    obj.truncate(1)
  ];
}
globalThis['closureSelfUseFileSystemWritableFileStream'] = closureSelfUseFileSystemWritableFileStream;

/**
 * @param {!FileSystemReadWriteOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemReadWriteOptions(obj) {
  return [
    obj.at
  ];
}
globalThis['closureSelfUseFileSystemReadWriteOptions'] = closureSelfUseFileSystemReadWriteOptions;

/**
 * @param {!FileSystemSyncAccessHandle} obj
 * @return {!Array<*>}
 */
function closureSelfUseFileSystemSyncAccessHandle(obj) {
  return [
    obj.read,
    obj.write,
    obj.getSize,
    obj.flush,
    obj.truncate(1),
    obj.close()
  ];
}
globalThis['closureSelfUseFileSystemSyncAccessHandle'] = closureSelfUseFileSystemSyncAccessHandle;

/**
 * @param {!StorageManager} obj
 * @return {!Array<*>}
 */
function closureSelfUseStorageManager(obj) {
  return [
    obj.getDirectory()
  ];
}
globalThis['closureSelfUseStorageManager'] = closureSelfUseStorageManager;

/**
 * @param {!FileSystemHandleKind} t0
 * @param {!WriteCommandType} t1
 * @param {!FileSystemWriteChunkType} t2
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2) {
  return [
    t0,
    t1,
    t2
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
