/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.net.createwebchanneltransport.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/net/webchanneltransportfactory.js).
 * Requires goog.net.createWebChannelTransport and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_net_createWebChannelTransport');

const target = goog.require('goog.net.createWebChannelTransport');

goog.exportSymbol('goog.net.createWebChannelTransport', target);
