/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.emoji.popupemojipicker.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/emoji/popupemojipicker.js).
 * Requires goog.ui.emoji.PopupEmojiPicker and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_emoji_PopupEmojiPicker');

const target = goog.require('goog.ui.emoji.PopupEmojiPicker');

goog.exportSymbol('goog.ui.emoji.PopupEmojiPicker', target);
goog.exportProperty(target.prototype, 'addEmojiGroup', target.prototype.addEmojiGroup);
goog.exportProperty(target.prototype, 'setToggleMode', target.prototype.setToggleMode);
goog.exportProperty(target.prototype, 'getToggleMode', target.prototype.getToggleMode);
goog.exportProperty(target.prototype, 'setDelayedLoad', target.prototype.setDelayedLoad);
