/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/es6_typed_array.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Int8Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseInt8Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseInt8Array'] = closureSelfUseInt8Array;

/**
 * @param {!Uint8ClampedArray} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint8ClampedArray(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseUint8ClampedArray'] = closureSelfUseUint8ClampedArray;

/**
 * @param {!Uint16Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint16Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseUint16Array'] = closureSelfUseUint16Array;

/**
 * @param {!Int32Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseInt32Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseInt32Array'] = closureSelfUseInt32Array;

/**
 * @param {!Uint32Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint32Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseUint32Array'] = closureSelfUseUint32Array;

/**
 * @param {!Float32Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseFloat32Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseFloat32Array'] = closureSelfUseFloat32Array;

/**
 * @param {!Float64Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseFloat64Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseFloat64Array'] = closureSelfUseFloat64Array;

/**
 * @param {!Uint8ArrayBase64Options} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint8ArrayBase64Options(obj) {
  return [
    obj.alphabet,
    obj.lastChunkHandling
  ];
}
globalThis['closureSelfUseUint8ArrayBase64Options'] = closureSelfUseUint8ArrayBase64Options;

/**
 * @param {!Uint8ArraySetFromBase64Results} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint8ArraySetFromBase64Results(obj) {
  return [
    obj.read,
    obj.written
  ];
}
globalThis['closureSelfUseUint8ArraySetFromBase64Results'] = closureSelfUseUint8ArraySetFromBase64Results;

/**
 * @param {!Uint8ArrayToBase64Options} obj
 * @return {!Array<*>}
 */
function closureSelfUseUint8ArrayToBase64Options(obj) {
  return [
    obj.alphabet,
    obj.omitPadding
  ];
}
globalThis['closureSelfUseUint8ArrayToBase64Options'] = closureSelfUseUint8ArrayToBase64Options;

/**
 * @param {!BigInt64Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseBigInt64Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseBigInt64Array'] = closureSelfUseBigInt64Array;

/**
 * @param {!BigUint64Array} obj
 * @return {!Array<*>}
 */
function closureSelfUseBigUint64Array(obj) {
  return [
    obj.BYTES_PER_ELEMENT,
    obj.find,
    obj.indexOf,
    obj.reduce,
    obj.sort,
    obj.toLocaleString,
    obj.at(1),
    obj.toString()
  ];
}
globalThis['closureSelfUseBigUint64Array'] = closureSelfUseBigUint64Array;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Int8Array.BYTES_PER_ELEMENT,
    Uint8ClampedArray.from,
    Int16Array.from,
    Int32Array.BYTES_PER_ELEMENT,
    Uint32Array.BYTES_PER_ELEMENT,
    Float16Array.from,
    Float32Array.from,
    Uint8Array.BYTES_PER_ELEMENT,
    BigInt64Array.BYTES_PER_ELEMENT,
    BigUint64Array.from,
    Int8Array.of(),
    Int32Array.of(),
    Uint8Array.of(),
    BigUint64Array.of()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
