/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.structs.linkedmap.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/structs/linkedmap.js).
 * Requires goog.structs.LinkedMap and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_structs_LinkedMap');

const target = goog.require('goog.structs.LinkedMap');

goog.exportSymbol('goog.structs.LinkedMap', target);
goog.exportProperty(target.prototype, 'get', target.prototype.get);
goog.exportProperty(target.prototype, 'peekValue', target.prototype.peekValue);
goog.exportProperty(target.prototype, 'set', target.prototype.set);
goog.exportProperty(target.prototype, 'peek', target.prototype.peek);
