// Generated by corpus/d2/candidates/npm.collect.py for npm:punycode@2.3.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  decode as e_decode,
  default as e_default,
  encode as e_encode,
  toASCII as e_toASCII,
  toUnicode as e_toUnicode,
  ucs2decode as e_ucs2decode,
  ucs2encode as e_ucs2encode,
} from '../../../../corpus-cache/d2/npm/punycode@2.3.1/package/punycode.es6.js';
globalThis['decode'] = e_decode;
globalThis['default'] = e_default;
globalThis['encode'] = e_encode;
globalThis['toASCII'] = e_toASCII;
globalThis['toUnicode'] = e_toUnicode;
globalThis['ucs2decode'] = e_ucs2decode;
globalThis['ucs2encode'] = e_ucs2encode;
