/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/ie_event.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!MSPointerPoint} obj
 * @return {!Array<*>}
 */
function closureSelfUseMSPointerPoint(obj) {
  return [
    obj.pointerId,
    obj.pointerType
  ];
}
globalThis['closureSelfUseMSPointerPoint'] = closureSelfUseMSPointerPoint;

/**
 * @param {!MSPointerEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseMSPointerEvent(obj) {
  return [
    obj.height,
    obj.pointerId,
    obj.pressure,
    obj.tiltY,
    obj.width,
    obj.initPointerEvent
  ];
}
globalThis['closureSelfUseMSPointerEvent'] = closureSelfUseMSPointerEvent;

/**
 * @param {!MSGesture} obj
 * @return {!Array<*>}
 */
function closureSelfUseMSGesture(obj) {
  return [
    obj.target,
    obj.addPointer(1),
    obj.stop()
  ];
}
globalThis['closureSelfUseMSGesture'] = closureSelfUseMSGesture;

/**
 * @param {!MSGestureEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseMSGestureEvent(obj) {
  return [
    obj.expansion,
    obj.hwTimestamp,
    obj.scale,
    obj.velocityAngular,
    obj.velocityX,
    obj.initGestureEvent
  ];
}
globalThis['closureSelfUseMSGestureEvent'] = closureSelfUseMSGestureEvent;

/**
 * @param {!Event} obj
 * @return {!Array<*>}
 */
function closureSelfUseEvent(obj) {
  return [
    obj.Abstract,
    obj.dataFld,
    obj.offsetY,
    obj.returnValue,
    obj.srcFilter,
    obj.y
  ];
}
globalThis['closureSelfUseEvent'] = closureSelfUseEvent;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    MSPointerEvent.MSPOINTER_TYPE_MOUSE,
    MSPointerEvent.MSPOINTER_TYPE_PEN,
    MSPointerEvent.MSPOINTER_TYPE_TOUCH
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
