// Generated by corpus/d2/candidates/npm.collect.py for npm:@msgpack/msgpack@3.1.3 (ISC).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  DecodeError as e_DecodeError,
  Decoder as e_Decoder,
  EXT_TIMESTAMP as e_EXT_TIMESTAMP,
  Encoder as e_Encoder,
  ExtData as e_ExtData,
  ExtensionCodec as e_ExtensionCodec,
  decode as e_decode,
  decodeArrayStream as e_decodeArrayStream,
  decodeAsync as e_decodeAsync,
  decodeMulti as e_decodeMulti,
  decodeMultiStream as e_decodeMultiStream,
  decodeTimestampExtension as e_decodeTimestampExtension,
  decodeTimestampToTimeSpec as e_decodeTimestampToTimeSpec,
  encode as e_encode,
  encodeDateToTimeSpec as e_encodeDateToTimeSpec,
  encodeTimeSpecToTimestamp as e_encodeTimeSpecToTimestamp,
  encodeTimestampExtension as e_encodeTimestampExtension,
} from '../../../../corpus-cache/d2/npm/@msgpack/msgpack@3.1.3/package/dist.esm/index.mjs';
globalThis['DecodeError'] = e_DecodeError;
globalThis['Decoder'] = e_Decoder;
globalThis['EXT_TIMESTAMP'] = e_EXT_TIMESTAMP;
globalThis['Encoder'] = e_Encoder;
globalThis['ExtData'] = e_ExtData;
globalThis['ExtensionCodec'] = e_ExtensionCodec;
globalThis['decode'] = e_decode;
globalThis['decodeArrayStream'] = e_decodeArrayStream;
globalThis['decodeAsync'] = e_decodeAsync;
globalThis['decodeMulti'] = e_decodeMulti;
globalThis['decodeMultiStream'] = e_decodeMultiStream;
globalThis['decodeTimestampExtension'] = e_decodeTimestampExtension;
globalThis['decodeTimestampToTimeSpec'] = e_decodeTimestampToTimeSpec;
globalThis['encode'] = e_encode;
globalThis['encodeDateToTimeSpec'] = e_encodeDateToTimeSpec;
globalThis['encodeTimeSpecToTimestamp'] = e_encodeTimeSpecToTimestamp;
globalThis['encodeTimestampExtension'] = e_encodeTimestampExtension;
