/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/es6.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Iterator} obj
 * @return {!Array<*>}
 */
function closureSelfUseIterator(obj) {
  return [
    obj.map,
    obj.take,
    obj.flatMap,
    obj.reduce,
    obj.some,
    obj.find,
    obj.next(),
    obj.toArray()
  ];
}
globalThis['closureSelfUseIterator'] = closureSelfUseIterator;

/**
 * @param {!ITemplateArray} obj
 * @return {!Array<*>}
 */
function closureSelfUseITemplateArray(obj) {
  return [
    obj.raw
  ];
}
globalThis['closureSelfUseITemplateArray'] = closureSelfUseITemplateArray;

/**
 * @param {!ArrayBufferView} obj
 * @return {!Array<*>}
 */
function closureSelfUseArrayBufferView(obj) {
  return [
    obj.buffer,
    obj.byteOffset,
    obj.byteLength
  ];
}
globalThis['closureSelfUseArrayBufferView'] = closureSelfUseArrayBufferView;

/**
 * @param {!DataView} obj
 * @return {!Array<*>}
 */
function closureSelfUseDataView(obj) {
  return [
    obj.getUint8,
    obj.getUint32,
    obj.getBigInt64,
    obj.setUint8,
    obj.setUint32,
    obj.setBigUint64,
    obj.getInt8(1),
    obj.setFloat64(1, 1)
  ];
}
globalThis['closureSelfUseDataView'] = closureSelfUseDataView;

/**
 * @param {!Promise} obj
 * @return {!Array<*>}
 */
function closureSelfUsePromise(obj) {
  return [
    obj.then,
    obj.catch,
    obj.finally
  ];
}
globalThis['closureSelfUsePromise'] = closureSelfUsePromise;

/**
 * @param {!Promise.PromiseWithResolvers} obj
 * @return {!Array<*>}
 */
function closureSelfUsePromisePromiseWithResolvers(obj) {
  return [
    obj.promise,
    obj.resolve,
    obj.reject
  ];
}
globalThis['closureSelfUsePromisePromiseWithResolvers'] = closureSelfUsePromisePromiseWithResolvers;

/**
 * @param {!AsyncIterator} obj
 * @return {!Array<*>}
 */
function closureSelfUseAsyncIterator(obj) {
  return [
    obj.next
  ];
}
globalThis['closureSelfUseAsyncIterator'] = closureSelfUseAsyncIterator;

/**
 * @param {!WeakRef} obj
 * @return {!Array<*>}
 */
function closureSelfUseWeakRef(obj) {
  return [
    obj.deref()
  ];
}
globalThis['closureSelfUseWeakRef'] = closureSelfUseWeakRef;

/**
 * @param {!SuppressedError} obj
 * @return {!Array<*>}
 */
function closureSelfUseSuppressedError(obj) {
  return [
    obj.error,
    obj.suppressed
  ];
}
globalThis['closureSelfUseSuppressedError'] = closureSelfUseSuppressedError;

/**
 * @param {!AsyncDisposableStack} obj
 * @return {!Array<*>}
 */
function closureSelfUseAsyncDisposableStack(obj) {
  return [
    obj.disposed,
    obj.use,
    obj.adopt,
    obj.defer,
    obj.disposeAsync(),
    obj.move()
  ];
}
globalThis['closureSelfUseAsyncDisposableStack'] = closureSelfUseAsyncDisposableStack;

/**
 * @param {string} obj
 * @return {!Array<*>}
 */
function closureSelfUseString(obj) {
  return [
    obj.at,
    obj.padStart,
    obj.normalize,
    obj.endsWith,
    obj.trimStart,
    obj.matchAll,
    obj.codePointAt(1),
    obj.isWellFormed()
  ];
}
globalThis['closureSelfUseString'] = closureSelfUseString;

/**
 * @param {!ReadonlyArray} obj
 * @return {!Array<*>}
 */
function closureSelfUseReadonlyArray(obj) {
  return [
    obj.keys,
    obj.find,
    obj.findLastIndex,
    obj.includes,
    obj.toReversed,
    obj.with
  ];
}
globalThis['closureSelfUseReadonlyArray'] = closureSelfUseReadonlyArray;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    Iterator.from,
    Promise.allSettled,
    Object.setPrototypeOf,
    Object.assign,
    Object.groupBy,
    Reflect.getOwnPropertyDescriptor,
    Reflect.set,
    Atomics.exchange,
    Atomics.wait,
    Symbol.asyncDispose,
    Math.log10(1),
    Math.atanh(1),
    Object.is(0, 0),
    Atomics.isLockFree(1)
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!ArrayIterator} t0
 * @param {!SetIterator} t1
 * @param {!BufferSource} t2
 * @param {!Thenable} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
