/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.fx.draglistgrouptest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/fx/draglistgroup_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_fx_DragListGroupTest');

goog.require('goog.fx.DragListGroupTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.fx.draglistgrouptest');
