#!/usr/bin/env python3
"""Regenerates crates/resources/data/, src/jar_contents.rs and tests/fixtures/jar_manifest.tsv.

Usage:
    python3 crates/resources/tools/sync_from_jar.py <closure-compiler.jar> <reference/closure-compiler>

The resources are taken from the reference jar, in the jar's (and the nested externs.zip's) entry
order, which is the order Java's ZipInputStream / class loader sees:
  - externs.zip (Bazel `pkg_zip(name = "externs_zip", srcs = glob(["externs/**/*.js"]),
    strip_prefix = "externs")`), every entry including directory entries;
  - com/google/javascript/jscomp/js/** except .class files (runtime libraries, polyfills.txt,
    transpilation_libs.txt);
  - runtime_libs.typedast.
Every extern and runtime .js file is also checked byte for byte against the reference source tree.
The output is deterministic: running the script twice gives no diff. It writes only inside the
crate it belongs to (this checkout).

src/jar_contents.rs keeps the license header it carries (written by scripts/license_headers.py
--apply); the script checks that header against the one LICENSES/headers.tsv records for the file,
so `python3 scripts/license_headers.py --check` passes right after a sync.
"""

import hashlib
import io
import os
import subprocess
import sys
import zipfile

CRATE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(CRATE))
RS_PATH = os.path.join(CRATE, "src", "jar_contents.rs")
RS_REL = os.path.relpath(RS_PATH, REPO).replace(os.sep, "/")
LICENSE_MANIFEST = os.path.join(REPO, "LICENSES", "headers.tsv")
GENERATED_MARK = "// Generated by crates/resources/tools/sync_from_jar.py"
DATA = os.path.join(CRATE, "data")
RUNTIME_PREFIX = "com/google/javascript/jscomp/js/"
TYPEDAST = "runtime_libs.typedast"
EXTERNS_ZIP = "externs.zip"
EMPTY_SHA = hashlib.sha256(b"").hexdigest()


def die(msg):
    sys.stderr.write("sync_from_jar.py: " + msg + "\n")
    sys.exit(1)


def rust_str(s):
    if any(c in s for c in '"\\') or any(ord(c) < 0x20 or ord(c) > 0x7E for c in s):
        die("unexpected character in entry name: %r" % s)
    return '"' + s + '"'


def license_header():
    """The license header of src/jar_contents.rs: the text before GENERATED_MARK in the current
    file, which must hash (first 16 hex digits of its SHA-256, LF line endings) to the digest
    LICENSES/headers.tsv records for the file, as `license_headers.py --check` compares it."""
    digest = None
    with open(LICENSE_MANIFEST, encoding="utf-8") as f:
        for line in f:
            cols = line.rstrip("\n").split("\t")
            if not line.startswith("#") and cols[0] == RS_REL:
                digest = cols[1]
    if digest is None:
        die("%s is not listed in %s" % (RS_REL, LICENSE_MANIFEST))
    header = ""
    if os.path.exists(RS_PATH):
        with open(RS_PATH, encoding="utf-8", newline="") as f:
            text = f.read().replace("\r\n", "\n")
        if GENERATED_MARK in text:
            header = text[: text.index(GENERATED_MARK)]
    if hashlib.sha256(header.encode("utf-8")).hexdigest()[:16] != digest:
        die(
            "the license header of %s is not the one LICENSES/headers.tsv records; "
            "restore it (git checkout or python3 scripts/license_headers.py --apply) "
            "and sync again" % RS_REL
        )
    return header


def main():
    if len(sys.argv) != 3:
        die("usage: sync_from_jar.py <closure-compiler.jar> <reference/closure-compiler dir>")
    jar_path, ref_dir = sys.argv[1], sys.argv[2]
    header = license_header()

    jar = zipfile.ZipFile(jar_path)
    # (name, is_dir, bytes or None) in jar order.
    jar_entries = []
    externs_bytes = None
    for info in jar.infolist():
        name = info.filename
        if name == EXTERNS_ZIP:
            externs_bytes = jar.read(info)
            jar_entries.append((name, "zip", None))
        elif name == TYPEDAST:
            jar_entries.append((name, "file", jar.read(info)))
        elif name.startswith(RUNTIME_PREFIX) or name + "/" == RUNTIME_PREFIX:
            if name.endswith(".class"):
                continue
            if info.is_dir():
                jar_entries.append((name, "dir", None))
            else:
                jar_entries.append((name, "file", jar.read(info)))
    if externs_bytes is None:
        die("no externs.zip in " + jar_path)

    externs = zipfile.ZipFile(io.BytesIO(externs_bytes))
    externs_entries = []
    for info in externs.infolist():
        if info.is_dir():
            externs_entries.append((info.filename, "dir", None))
        else:
            externs_entries.append((info.filename, "file", externs.read(info)))

    # Byte-identity with the reference sources.
    for name, kind, data in externs_entries:
        if kind == "file":
            src = os.path.join(ref_dir, "externs", name)
            with open(src, "rb") as f:
                if f.read() != data:
                    die("externs.zip entry differs from " + src)
    for name, kind, data in jar_entries:
        if kind == "file" and name.endswith(".js"):
            src = os.path.join(ref_dir, "src", name)
            with open(src, "rb") as f:
                if f.read() != data:
                    die("jar entry differs from " + src)

    # data/
    wanted = {}
    for name, kind, data in externs_entries:
        if kind == "file":
            wanted[os.path.join("externs", name)] = data
    for name, kind, data in jar_entries:
        if kind == "file":
            wanted[name] = data
    for rel, data in wanted.items():
        path = os.path.join(DATA, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        old = None
        if os.path.exists(path):
            with open(path, "rb") as f:
                old = f.read()
        if old != data:
            with open(path, "wb") as f:
                f.write(data)
    keep = set(wanted) | {"README"}
    for root, dirs, files in os.walk(DATA, topdown=False):
        for fn in files:
            rel = os.path.relpath(os.path.join(root, fn), DATA)
            if rel not in keep:
                os.remove(os.path.join(root, fn))
        if root != DATA and not os.listdir(root):
            os.rmdir(root)

    # src/jar_contents.rs
    out = []
    out.append(
        "// Generated by crates/resources/tools/sync_from_jar.py from the reference\n"
        "// closure-compiler.jar. Do not edit; regenerate with:\n"
        "//   python3 crates/resources/tools/sync_from_jar.py <closure-compiler.jar> "
        "<reference/closure-compiler>\n"
        "\n"
        "//! The resources of closure-compiler.jar that the compiler loads, in jar order, and the\n"
        "//! entries of the nested `externs.zip`, in zip order (directory entries included).\n"
        "\n"
        "/// One entry of a zip/jar archive, in archive order.\n"
        "#[derive(Debug)]\n"
        "pub struct ArchiveEntry {\n"
        "    pub name: &'static str,\n"
        "    pub content: EntryContent,\n"
        "}\n"
        "\n"
        "/// The content of an [`ArchiveEntry`].\n"
        "#[derive(Debug)]\n"
        "pub enum EntryContent {\n"
        "    /// A directory entry (`name` ends with '/').\n"
        "    Directory,\n"
        "    /// A stored file.\n"
        "    File(&'static [u8]),\n"
        "    /// A nested zip stored pre-expanded (only `externs.zip`): its entries in zip order.\n"
        "    Zip(&'static [ArchiveEntry]),\n"
        "}\n"
        "\n"
    )

    def emit_table(doc, ident, entries, data_prefix):
        out.append(doc)
        out.append("pub static %s: &[ArchiveEntry] = &[\n" % ident)
        for name, kind, _ in entries:
            out.append("    ArchiveEntry {\n")
            out.append("        name: %s,\n" % rust_str(name))
            if kind == "dir":
                out.append("        content: EntryContent::Directory,\n")
            elif kind == "zip":
                out.append("        content: EntryContent::Zip(EXTERNS_ZIP_ENTRIES),\n")
            else:
                out.append(
                    "        content: EntryContent::File(include_bytes!(%s)),\n"
                    % rust_str("../data/" + data_prefix + name)
                )
            out.append("    },\n")
        out.append("];\n")

    emit_table(
        "/// Entries of closure-compiler.jar that the compiler loads as resources.\n",
        "JAR_ENTRIES",
        jar_entries,
        "",
    )
    out.append("\n")
    emit_table(
        "/// Entries of externs.zip (inside the jar), including the `browser/` directory entry.\n",
        "EXTERNS_ZIP_ENTRIES",
        externs_entries,
        "externs/",
    )
    with open(RS_PATH, "w", newline="\n") as f:
        f.write("".join(out))
    # Format it exactly as `cargo fmt` would, so the checked-in file is stable under `cargo fmt`.
    subprocess.run(["rustfmt", "--edition", "2024", RS_PATH], check=True)
    with open(RS_PATH, encoding="utf-8", newline="") as f:
        formatted = f.read()
    with open(RS_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(header + formatted)

    # tests/fixtures/jar_manifest.tsv
    lines = ["# archive\tindex\tname\tsize\tsha256  (generated by tools/sync_from_jar.py)\n"]
    for archive, entries in (("jar", jar_entries), ("externs.zip", externs_entries)):
        for i, (name, kind, data) in enumerate(entries):
            if kind == "zip":
                size, sha = "-", "-"
            elif kind == "dir":
                size, sha = "0", EMPTY_SHA
            else:
                size, sha = str(len(data)), hashlib.sha256(data).hexdigest()
            lines.append("%s\t%d\t%s\t%s\t%s\n" % (archive, i, name, size, sha))
    fixtures = os.path.join(CRATE, "tests", "fixtures")
    os.makedirs(fixtures, exist_ok=True)
    with open(os.path.join(fixtures, "jar_manifest.tsv"), "w", newline="\n") as f:
        f.write("".join(lines))


if __name__ == "__main__":
    main()
