/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.cssom.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/cssom/cssom.js).
 * Requires goog.cssom and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_cssom');

const target = goog.require('goog.cssom');

goog.exportSymbol('goog.cssom.CssRuleType', target.CssRuleType);
goog.exportSymbol('goog.cssom.getAllCssText', target.getAllCssText);
goog.exportSymbol('goog.cssom.getAllCssStyleRules', target.getAllCssStyleRules);
goog.exportSymbol('goog.cssom.getCssRulesFromStyleSheet', target.getCssRulesFromStyleSheet);
goog.exportSymbol('goog.cssom.getAllCssStyleSheets', target.getAllCssStyleSheets);
goog.exportSymbol('goog.cssom.getCssTextFromCssRule', target.getCssTextFromCssRule);
goog.exportSymbol('goog.cssom.getCssRuleIndexInParentStyleSheet', target.getCssRuleIndexInParentStyleSheet);
goog.exportSymbol('goog.cssom.getParentStyleSheet', target.getParentStyleSheet);
