/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.debug.error.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/debug/error.js).
 * Requires goog.debug.Error and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_debug_Error');

const target = goog.require('goog.debug.Error');

goog.exportSymbol('goog.debug.Error', target);
