/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-heap-js-2.7.1-pkg-cjs:
 * Node.js/AMD globals referenced by npm:heap-js@2.7.1 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
