/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.useragent.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/useragent/useragent.js).
 * Requires goog.userAgent and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_userAgent');

const target = goog.require('goog.userAgent');

goog.exportSymbol('goog.userAgent.getUserAgentString', target.getUserAgentString);
goog.exportSymbol('goog.userAgent.getNavigatorTyped', target.getNavigatorTyped);
goog.exportSymbol('goog.userAgent.getNavigator', target.getNavigator);
goog.exportSymbol('goog.userAgent.OPERA', target.OPERA);
goog.exportSymbol('goog.userAgent.IE', target.IE);
goog.exportSymbol('goog.userAgent.EDGE', target.EDGE);
goog.exportSymbol('goog.userAgent.EDGE_OR_IE', target.EDGE_OR_IE);
goog.exportSymbol('goog.userAgent.GECKO', target.GECKO);
