/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.fx.dragdrop.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/fx/dragdrop.js).
 * Requires goog.fx.DragDrop and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_fx_DragDrop');

const target = goog.require('goog.fx.DragDrop');

goog.exportSymbol('goog.fx.DragDrop', target);
goog.exportProperty(target.prototype, 'setDragClass', target.prototype.setDragClass);
goog.exportProperty(target.prototype, 'setSourceClass', target.prototype.setSourceClass);
goog.exportProperty(target.prototype, 'setTargetClass', target.prototype.setTargetClass);
goog.exportProperty(target.prototype, 'isInitialized', target.prototype.isInitialized);
