// Generated by corpus/d2/candidates/npm.collect.py for npm:kefir@3.8.8 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/kefir@3.8.8/package/dist/kefir.js');
globalThis['dissableDeprecationWarnings'] = pkg.dissableDeprecationWarnings;
globalThis['Kefir'] = pkg.Kefir;
globalThis['Observable'] = pkg.Observable;
globalThis['Stream'] = pkg.Stream;
globalThis['Property'] = pkg.Property;
globalThis['never'] = pkg.never;
globalThis['later'] = pkg.later;
globalThis['interval'] = pkg.interval;
globalThis['sequentially'] = pkg.sequentially;
globalThis['fromPoll'] = pkg.fromPoll;
globalThis['withInterval'] = pkg.withInterval;
globalThis['fromCallback'] = pkg.fromCallback;
globalThis['fromNodeCallback'] = pkg.fromNodeCallback;
globalThis['fromEvents'] = pkg.fromEvents;
globalThis['stream'] = pkg.stream;
globalThis['constant'] = pkg.constant;
globalThis['constantError'] = pkg.constantError;
globalThis['fromPromise'] = pkg.fromPromise;
globalThis['fromESObservable'] = pkg.fromESObservable;
globalThis['combine'] = pkg.combine;
globalThis['zip'] = pkg.zip;
globalThis['merge'] = pkg.merge;
globalThis['concat'] = pkg.concat;
globalThis['Pool'] = pkg.Pool;
globalThis['pool'] = pkg.pool;
globalThis['repeat'] = pkg.repeat;
globalThis['staticLand'] = pkg.staticLand;
globalThis['default'] = pkg.default;
