/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-classnames-2.5.1-pkg-cjs:
 * Node.js/AMD globals referenced by npm:classnames@2.5.1 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
