// Generated by corpus/d2/candidates/npm.collect.py for npm:reselect@5.3.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  createSelector as e_createSelector,
  createSelectorCreator as e_createSelectorCreator,
  createStructuredSelector as e_createStructuredSelector,
  lruMemoize as e_lruMemoize,
  referenceEqualityCheck as e_referenceEqualityCheck,
  setGlobalDevModeChecks as e_setGlobalDevModeChecks,
  weakMapMemoize as e_weakMapMemoize,
} from '../../../../corpus-cache/d2/npm/reselect@5.3.0/package/dist/reselect.mjs';
globalThis['createSelector'] = e_createSelector;
globalThis['createSelectorCreator'] = e_createSelectorCreator;
globalThis['createStructuredSelector'] = e_createStructuredSelector;
globalThis['lruMemoize'] = e_lruMemoize;
globalThis['referenceEqualityCheck'] = e_referenceEqualityCheck;
globalThis['setGlobalDevModeChecks'] = e_setGlobalDevModeChecks;
globalThis['weakMapMemoize'] = e_weakMapMemoize;
