// Generated by corpus/d2/candidates/npm.collect.py for npm:fast-xml-parser@5.11.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/fast-xml-parser@5.11.2/package/lib/fxp.cjs');
globalThis['fast-xml-parser'] = pkg;
