// Generated by corpus/d2/candidates/npm.collect.py for npm:@babel/parser@7.29.9 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/@babel/parser@7.29.9/package/lib/index.js');
globalThis['parse'] = pkg.parse;
globalThis['parseExpression'] = pkg.parseExpression;
globalThis['tokTypes'] = pkg.tokTypes;
