/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-decimal.js-10.6.0-pkg-cjs:
 * Node.js/AMD globals referenced by npm:decimal.js@10.6.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var define;
