/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.log.logbuffertest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/log/logbuffer_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_log_LogBufferTest');

goog.require('goog.log.LogBufferTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.log.logbuffertest');
