// closure-rs D2 whole-program case whole-program-punycode-2.3.1: runs the own test suite of
// punycode@2.3.1 (mathiasbynens/punycode.js @ 9e1b2cda98d2) against a compiled output.
//   node corpus/d2/shims/whole-program-punycode-2.3.1/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-punycode-2.3.1/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-punycode-2.3.1",
  "global": "punycode",
  "testDir": "corpus-cache/d2/whole-program/punycode@2.3.1/repo",
  "framework": "mocha",
  "files": [
    "tests/tests.js"
  ],
  "modules": {
    "../punycode.js": {
      "path": []
    }
  },
  "expectTests": 139
});
