// Generated by corpus/d2/candidates/npm.collect.py for npm:nouislider@15.8.1 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/nouislider@15.8.1/package/dist/nouislider.js');
globalThis['PipsMode'] = pkg.PipsMode;
globalThis['PipsType'] = pkg.PipsType;
globalThis['create'] = pkg.create;
globalThis['cssClasses'] = pkg.cssClasses;
globalThis['default'] = pkg.default;
