/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.ac.richremote.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/ac/richremote.js).
 * Requires goog.ui.ac.RichRemote and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_ac_RichRemote');

const target = goog.require('goog.ui.ac.RichRemote');

goog.exportSymbol('goog.ui.ac.RichRemote', target);
goog.exportProperty(target.prototype, 'setRowFilter', target.prototype.setRowFilter);
goog.exportProperty(target.prototype, 'setRowBuilder', target.prototype.setRowBuilder);
