/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.object.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/object/object.js).
 * Requires goog.object and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_object');

const target = goog.require('goog.object');

goog.exportSymbol('goog.object.add', target.add);
goog.exportSymbol('goog.object.clear', target.clear);
goog.exportSymbol('goog.object.clone', target.clone);
goog.exportSymbol('goog.object.contains', target.contains);
goog.exportSymbol('goog.object.containsKey', target.containsKey);
goog.exportSymbol('goog.object.containsValue', target.containsValue);
goog.exportSymbol('goog.object.create', target.create);
goog.exportSymbol('goog.object.createImmutableView', target.createImmutableView);
