/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.locale.countries.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/locale/countries.js).
 * Requires goog.locale.countries and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_locale_countries');

const target = goog.require('goog.locale.countries');

goog.exportSymbol('goog.locale.countries', target);
