// Generated by corpus/d2/candidates/npm.collect.py for npm:detect-browser@5.3.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/detect-browser@5.3.0/package/index.js');
globalThis['getNodeVersion'] = pkg.getNodeVersion;
globalThis['detectOS'] = pkg.detectOS;
globalThis['parseUserAgent'] = pkg.parseUserAgent;
globalThis['browserName'] = pkg.browserName;
globalThis['detect'] = pkg.detect;
globalThis['ReactNativeInfo'] = pkg.ReactNativeInfo;
globalThis['BotInfo'] = pkg.BotInfo;
globalThis['SearchBotDeviceInfo'] = pkg.SearchBotDeviceInfo;
globalThis['NodeInfo'] = pkg.NodeInfo;
globalThis['BrowserInfo'] = pkg.BrowserInfo;
