// closure-rs D2 whole-program case whole-program-ieee754-1.2.1: runs the own test suite of
// ieee754@1.2.1 (feross/ieee754 @ b60d148be9ca) against a compiled output.
//   node corpus/d2/shims/whole-program-ieee754-1.2.1/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-ieee754-1.2.1/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-ieee754-1.2.1",
  "global": "ieee754",
  "testDir": "corpus-cache/d2/whole-program/ieee754@1.2.1/repo",
  "framework": "tape",
  "tapeMajor": 5,
  "files": [
    "test/basic.js"
  ],
  "modules": {
    "../": {
      "path": []
    }
  },
  "expectTests": 4
});
