/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.proto2.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/proto2/proto2.js).
 * Requires goog.testing.proto2 and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_proto2');

const target = goog.require('goog.testing.proto2');

goog.exportSymbol('goog.testing.proto2.assertEquals', target.assertEquals);
goog.exportSymbol('goog.testing.proto2.fromObject', target.fromObject);
