/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.mockclock.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/mockclock.js).
 * Requires goog.testing.MockClock and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_MockClock');

const target = goog.require('goog.testing.MockClock');

goog.exportSymbol('goog.testing.MockClock', target);
goog.exportSymbol('goog.testing.MockClock.REQUEST_ANIMATION_FRAME_TIMEOUT', target.REQUEST_ANIMATION_FRAME_TIMEOUT);
goog.exportSymbol('goog.testing.MockClock.nextId', target.nextId);
goog.exportSymbol('goog.testing.MockClock.createAsyncMockClock', target.createAsyncMockClock);
goog.exportProperty(target.prototype, 'install', target.prototype.install);
goog.exportProperty(target.prototype, 'uninstall', target.prototype.uninstall);
goog.exportProperty(target.prototype, 'disposeInternal', target.prototype.disposeInternal);
goog.exportProperty(target.prototype, 'reset', target.prototype.reset);
