// closure-rs D2 whole-program case whole-program-ms-2.1.3: runs the own test suite of
// ms@2.1.3 (vercel/ms @ 1c6264b79549) against a compiled output.
//   node corpus/d2/shims/whole-program-ms-2.1.3/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-ms-2.1.3/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-ms-2.1.3",
  "global": "ms",
  "testDir": "corpus-cache/d2/whole-program/ms@2.1.3/repo",
  "framework": "mocha",
  "adapters": [
    "expect.js"
  ],
  "files": [
    "tests.js"
  ],
  "modules": {
    "./": {
      "path": []
    }
  },
  "expectTests": 49
});
