/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.fx.css3.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/fx/css3/fx.js).
 * Requires goog.fx.css3 and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_fx_css3');

const target = goog.require('goog.fx.css3');

goog.exportSymbol('goog.fx.css3.fade', target.fade);
goog.exportSymbol('goog.fx.css3.fadeIn', target.fadeIn);
goog.exportSymbol('goog.fx.css3.fadeOut', target.fadeOut);
