// Generated by corpus/d2/candidates/npm.collect.py for npm:redux@5.0.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  __DO_NOT_USE__ActionTypes as e___DO_NOT_USE__ActionTypes,
  applyMiddleware as e_applyMiddleware,
  bindActionCreators as e_bindActionCreators,
  combineReducers as e_combineReducers,
  compose as e_compose,
  createStore as e_createStore,
  isAction as e_isAction,
  isPlainObject as e_isPlainObject,
  legacy_createStore as e_legacy_createStore,
} from '../../../../corpus-cache/d2/npm/redux@5.0.1/package/dist/redux.mjs';
globalThis['__DO_NOT_USE__ActionTypes'] = e___DO_NOT_USE__ActionTypes;
globalThis['applyMiddleware'] = e_applyMiddleware;
globalThis['bindActionCreators'] = e_bindActionCreators;
globalThis['combineReducers'] = e_combineReducers;
globalThis['compose'] = e_compose;
globalThis['createStore'] = e_createStore;
globalThis['isAction'] = e_isAction;
globalThis['isPlainObject'] = e_isPlainObject;
globalThis['legacy_createStore'] = e_legacy_createStore;
