/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.i18n.collation.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/i18n/collation.js).
 * Requires goog.i18n.collation and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_i18n_collation');

const target = goog.require('goog.i18n.collation');

goog.exportSymbol('goog.i18n.collation.createComparator', target.createComparator);
goog.exportSymbol('goog.i18n.collation.hasNativeComparator', target.hasNativeComparator);
