/**
 * @fileoverview Externs for the closure-rs D2 whole-program case whole-program-acorn-8.19.0.
 *
 * The library's own tests run uncompiled against the compiled acorn@8.19.0, so property
 * names that cross that boundary must keep their names under ADVANCED optimizations. Listed
 * here: every name the library uses in property position (accesses, object-literal keys,
 * methods) that also occurs in its test files. Declaring them on
 * Object.prototype excludes them from property renaming and ambiguation (externed names) and
 * from property disambiguation (Object.prototype has the invalidating top-object color).
 * Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
 * @externs
 */

/** @type {?} */
Object.prototype._var;
/** @type {?} */
Object.prototype.acorn;
/** @type {?} */
Object.prototype.allowAwaitOutsideFunction;
/** @type {?} */
Object.prototype.allowHashBang;
/** @type {?} */
Object.prototype.allowImportExportEverywhere;
/** @type {?} */
Object.prototype.allowReserved;
/** @type {?} */
Object.prototype.allowReturnOutsideFunction;
/** @type {?} */
Object.prototype.allowSuperOutsideMethod;
/** @type {?} */
Object.prototype.alternate;
/** @type {?} */
Object.prototype.argument;
/** @type {?} */
Object.prototype.arguments;
/** @type {?} */
Object.prototype.assign;
/** @type {?} */
Object.prototype.async;
/** @type {?} */
Object.prototype.attributes;
/** @type {?} */
Object.prototype.await;
/** @type {?} */
Object.prototype.bigint;
/** @type {?} */
Object.prototype.block;
/** @type {?} */
Object.prototype.body;
/** @type {?} */
Object.prototype.callee;
/** @type {?} */
Object.prototype.cases;
/** @type {?} */
Object.prototype.charAt;
/** @type {?} */
Object.prototype.column;
/** @type {?} */
Object.prototype.computed;
/** @type {?} */
Object.prototype.consequent;
/** @type {?} */
Object.prototype.cooked;
/** @type {?} */
Object.prototype.declaration;
/** @type {?} */
Object.prototype.declarations;
/** @type {?} */
Object.prototype.delegate;
/** @type {?} */
Object.prototype.directive;
/** @type {?} */
Object.prototype.discriminant;
/** @type {?} */
Object.prototype.done;
/** @type {?} */
Object.prototype.ecmaVersion;
/** @type {?} */
Object.prototype.elements;
/** @type {?} */
Object.prototype.end;
/** @type {?} */
Object.prototype.eof;
/** @type {?} */
Object.prototype.eq;
/** @type {?} */
Object.prototype.exec;
/** @type {?} */
Object.prototype.exported;
/** @type {?} */
Object.prototype.expression;
/** @type {?} */
Object.prototype.expressions;
/** @type {?} */
Object.prototype.finalizer;
/** @type {?} */
Object.prototype.flags;
/** @type {?} */
Object.prototype.fromCharCode;
/** @type {?} */
Object.prototype.generator;
/** @type {?} */
Object.prototype.get;
/** @type {?} */
Object.prototype.handler;
/** @type {?} */
Object.prototype.id;
/** @type {?} */
Object.prototype.imported;
/** @type {?} */
Object.prototype.indexOf;
/** @type {?} */
Object.prototype.init;
/** @type {?} */
Object.prototype.key;
/** @type {?} */
Object.prototype.kind;
/** @type {?} */
Object.prototype.label;
/** @type {?} */
Object.prototype.left;
/** @type {?} */
Object.prototype.length;
/** @type {?} */
Object.prototype.line;
/** @type {?} */
Object.prototype.loc;
/** @type {?} */
Object.prototype.local;
/** @type {?} */
Object.prototype.locations;
/** @type {?} */
Object.prototype.message;
/** @type {?} */
Object.prototype.meta;
/** @type {?} */
Object.prototype.method;
/** @type {?} */
Object.prototype.name;
/** @type {?} */
Object.prototype.num;
/** @type {?} */
Object.prototype.object;
/** @type {?} */
Object.prototype.onComment;
/** @type {?} */
Object.prototype.onInsertedSemicolon;
/** @type {?} */
Object.prototype.onToken;
/** @type {?} */
Object.prototype.onTrailingComma;
/** @type {?} */
Object.prototype.operator;
/** @type {?} */
Object.prototype.optional;
/** @type {?} */
Object.prototype.options;
/** @type {?} */
Object.prototype.param;
/** @type {?} */
Object.prototype.params;
/** @type {?} */
Object.prototype.parenL;
/** @type {?} */
Object.prototype.parenR;
/** @type {?} */
Object.prototype.parse;
/** @type {?} */
Object.prototype.pattern;
/** @type {?} */
Object.prototype.plusMin;
/** @type {?} */
Object.prototype.pos;
/** @type {?} */
Object.prototype.prefix;
/** @type {?} */
Object.prototype.preserveParens;
/** @type {?} */
Object.prototype.properties;
/** @type {?} */
Object.prototype.property;
/** @type {?} */
Object.prototype.push;
/** @type {?} */
Object.prototype.quasi;
/** @type {?} */
Object.prototype.quasis;
/** @type {?} */
Object.prototype.range;
/** @type {?} */
Object.prototype.ranges;
/** @type {?} */
Object.prototype.raw;
/** @type {?} */
Object.prototype.regex;
/** @type {?} */
Object.prototype.replace;
/** @type {?} */
Object.prototype.right;
/** @type {?} */
Object.prototype.set;
/** @type {?} */
Object.prototype.shorthand;
/** @type {?} */
Object.prototype.slice;
/** @type {?} */
Object.prototype.source;
/** @type {?} */
Object.prototype.sourceFile;
/** @type {?} */
Object.prototype.sourceType;
/** @type {?} */
Object.prototype.specifiers;
/** @type {?} */
Object.prototype.start;
/** @type {?} */
Object.prototype.static;
/** @type {?} */
Object.prototype.superClass;
/** @type {?} */
Object.prototype.tag;
/** @type {?} */
Object.prototype.tail;
/** @type {?} */
Object.prototype.template;
/** @type {?} */
Object.prototype.test;
/** @type {?} */
Object.prototype.tokTypes;
/** @type {?} */
Object.prototype.type;
/** @type {?} */
Object.prototype.update;
/** @type {?} */
Object.prototype.value;
/** @type {?} */
Object.prototype.var;
