// closure-rs D2 whole-program case whole-program-acorn-8.19.0: runs the own test suite of
// acorn@8.19.0 (acornjs/acorn @ 0e0ece7cc720) against a compiled output.
//   node corpus/d2/shims/whole-program-acorn-8.19.0/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-acorn-8.19.0/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

const EXPECT_CASES = {"Normal":3578,"Normal with sourceType: commonjs":3306};

await runCase(import.meta.url, {
  "id": "whole-program-acorn-8.19.0",
  "global": "acorn",
  "testDir": "corpus-cache/d2/whole-program/acorn@8.19.0/repo",
  "framework": "custom",
  "modules": {
    "../acorn": {
      "path": []
    }
  },
  "expectTests": 2,
  register(h) {
    // Upstream test/run.js: load the driver, then the test files it requires (same order, parsed
    // from it), then run every registered case under each parser mode. The two "Loose" modes need
    // the separate acorn-loose package and are not part of this case.
    const driver = h.require('test/driver.js');
    for (const m of h.read('test/run.js').matchAll(/require\("\.\/(tests[^"]*)\.js"\)/g)) h.require(`test/${m[1]}.js`);
    const acorn = globalThis.acorn;
    // Mode configurations copied from upstream test/run.js (MIT, acornjs/acorn).
    const modes = {
      Normal: {
        config: {
          parse: acorn.parse
        }
      },
      'Normal with sourceType: commonjs': {
        config: {
          parse: (code, option) => acorn.parse(code, Object.assign({}, option, { sourceType: 'commonjs' })),
          filter: function (test) {
            var opts = test.options || {};
            return opts.commonjs !== false && !opts.allowAwaitOutsideFunction && (!opts.sourceType || opts.sourceType === 'script');
          }
        }
      }
    };
    for (const [name, mode] of Object.entries(modes)) {
      h.test(name, () => {
        const stats = { testsRun: 0, failed: 0 };
        const failures = [];
        driver.runTests(mode.config, (state, code, message) => {
          if (state !== 'ok') {
            ++stats.failed;
            failures.push(code + ' ' + message);
          }
          ++stats.testsRun;
        });
        if (stats.failed) throw new Error(`${stats.failed} of ${stats.testsRun} failed:\n` + failures.slice(0, 40).join('\n'));
        if (stats.testsRun !== EXPECT_CASES[name]) throw new Error(`ran ${stats.testsRun} cases, expected ${EXPECT_CASES[name]}`);
      });
    }
  },
});
