// Generated by corpus/d2/candidates/npm.collect.py for npm:petite-vue@0.4.1 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  createApp as e_createApp,
  nextTick as e_nextTick,
  reactive as e_reactive,
} from '../../../../corpus-cache/d2/npm/petite-vue@0.4.1/package/dist/petite-vue.es.js';
globalThis['createApp'] = e_createApp;
globalThis['nextTick'] = e_nextTick;
globalThis['reactive'] = e_reactive;
