/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.format.jsonprettyprintertest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/format/jsonprettyprinter_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_format_JsonPrettyPrinterTest');

goog.require('goog.format.JsonPrettyPrinterTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.format.jsonprettyprintertest');
