// Generated by corpus/d2/candidates/npm.collect.py for npm:luxon@3.7.2 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/luxon@3.7.2/package/build/node/luxon.js');
globalThis['DateTime'] = pkg.DateTime;
globalThis['Duration'] = pkg.Duration;
globalThis['FixedOffsetZone'] = pkg.FixedOffsetZone;
globalThis['IANAZone'] = pkg.IANAZone;
globalThis['Info'] = pkg.Info;
globalThis['Interval'] = pkg.Interval;
globalThis['InvalidZone'] = pkg.InvalidZone;
globalThis['Settings'] = pkg.Settings;
globalThis['SystemZone'] = pkg.SystemZone;
globalThis['VERSION'] = pkg.VERSION;
globalThis['Zone'] = pkg.Zone;
