/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.a11y.aria.announcertest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/a11y/aria/announcer_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_a11y_aria_AnnouncerTest');

goog.require('goog.a11y.aria.AnnouncerTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.a11y.aria.announcertest');
