/*
 * Copyright 2004 The Closure Compiler Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Ported from Closure Compiler (https://github.com/google/closure-compiler), commit 48f4107:
//   src/com/google/javascript/jscomp/MessageBundle.java.

//! Port of `com.google.javascript.jscomp.MessageBundle`.

use std::sync::Arc;

use closure_rhino::js_string::JsString;

use crate::js_message::{IdGenerator, JsMessage};

/// An interface for providing alternative values for user-visible messages in JavaScript code.
pub trait MessageBundle: std::any::Any + Send + Sync {
    /// Gets the message ID generator to use to compute message IDs for this type of bundle.
    ///
    /// Returns `None` if we do not want to use any custom id generation. In that case the caller
    /// should decide how to create the id by itself; in most cases using the message key is
    /// enough.
    // port: MessageBundle#idGenerator
    fn id_generator(&self) -> Option<Arc<dyn IdGenerator>>;

    /// Gets a message replacement.
    ///
    /// `id` is the id of the message being replaced, generated by `JsMessage.IdGenerator`.
    /// Returns the message replacement, which may be `None`.
    // port: MessageBundle#getMessage
    fn get_message(&self, id: &JsString) -> Option<&JsMessage>;

    /// Returns all messages from this bundle.
    // port: MessageBundle#getAllMessages
    fn get_all_messages(&self) -> Vec<&JsMessage>;
}
