/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.net.xpc.nativemessagingtransport.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/net/xpc/nativemessagingtransport.js).
 * Requires goog.net.xpc.NativeMessagingTransport and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_net_xpc_NativeMessagingTransport');

const target = goog.require('goog.net.xpc.NativeMessagingTransport');

goog.exportSymbol('goog.net.xpc.NativeMessagingTransport', target);
goog.exportProperty(target.prototype, 'transportType', target.prototype.transportType);
goog.exportProperty(target.prototype, 'transportServiceHandler', target.prototype.transportServiceHandler);
goog.exportProperty(target.prototype, 'connect', target.prototype.connect);
goog.exportProperty(target.prototype, 'send', target.prototype.send);
