/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-jquery-4.0.0-pkg-cjs:
 * Node.js/AMD globals referenced by npm:jquery@4.0.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;

/** @type {?} */
var global;

/** @type {?} */
var define;
