/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.streams.lite.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/streams/lite.js).
 * Requires goog.streams.lite and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_streams_lite');

const target = goog.require('goog.streams.lite');

goog.exportSymbol('goog.streams.lite.ReadableStream', target.ReadableStream);
goog.exportSymbol('goog.streams.lite.ReadableStreamDefaultController', target.ReadableStreamDefaultController);
goog.exportSymbol('goog.streams.lite.ReadableStreamDefaultReader', target.ReadableStreamDefaultReader);
goog.exportSymbol('goog.streams.lite.ReadableStreamUnderlyingSource', target.ReadableStreamUnderlyingSource);
goog.exportSymbol('goog.streams.lite.newReadableStream', target.newReadableStream);
