/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.ui.dialog.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/ui/dialog.js).
 * Requires goog.ui.Dialog and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_ui_Dialog');

const target = goog.require('goog.ui.Dialog');

goog.exportSymbol('goog.ui.Dialog', target);
goog.exportSymbol('goog.ui.Dialog.Event', target.Event);
goog.exportSymbol('goog.ui.Dialog.EventType', target.EventType);
goog.exportSymbol('goog.ui.Dialog.ButtonSet', target.ButtonSet);
goog.exportSymbol('goog.ui.Dialog.DefaultButtonKeys', target.DefaultButtonKeys);
goog.exportSymbol('goog.ui.Dialog.DefaultButtonCaptions', target.DefaultButtonCaptions);
goog.exportProperty(target.prototype, 'getCssClass', target.prototype.getCssClass);
goog.exportProperty(target.prototype, 'setTitle', target.prototype.setTitle);
goog.exportProperty(target.prototype, 'getTitle', target.prototype.getTitle);
goog.exportProperty(target.prototype, 'setTextContent', target.prototype.setTextContent);
