#!/usr/bin/env bash
# Reproduces the project-local toolchain (DECISIONS.md D-003) under tools/:
#   tools/bin/bazelisk   bazelisk release binary (linux-amd64)
#   tools/jdk-21         Eclipse Temurin JDK 21 (linux x64)
#   tools/env.sh         source-able environment (JAVA_HOME, PATH, BAZELISK_HOME)
# Everything is pinned by version and sha256. Nothing is installed system-wide.
# Idempotent: already-installed, verified components are left alone.
#
# Usage: scripts/setup_tools.sh            # install into <repo>/tools
#        TOOLS_DIR=/some/dir scripts/setup_tools.sh   # install elsewhere (testing)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TOOLS="${TOOLS_DIR:-$ROOT/tools}"

# --- pins ---------------------------------------------------------------------
# bazelisk: https://github.com/bazelbuild/bazelisk/releases/tag/v1.29.0
# sha256 = the release's bazelisk-linux-amd64.sha256 asset (== GitHub asset digest).
BAZELISK_VERSION=v1.29.0
BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-amd64"
BAZELISK_SHA256=5a408715e932c0250d28bd84555f12edbf70117de42f9181691c736eacc4a992

# Temurin JDK 21 GA, from api.adoptium.net/v3/assets/latest/21/hotspot (2026-10-06).
# sha256 = Adoptium's published checksum (API "checksum" == the release's .sha256.txt).
JDK_RELEASE='jdk-21.0.12.1+1'
JDK_FILE=OpenJDK21U-jdk_x64_linux_hotspot_21.0.12.1_1.tar.gz
JDK_URL="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/${JDK_FILE}"
JDK_SHA256=ce79869e1307ed8ee1e2baa86a412b1eb5b75d10a01006d788a6f968bcfaee94
JDK_JAVA_VERSION=21.0.12.1   # JAVA_VERSION in tools/jdk-21/release

# --- helpers ------------------------------------------------------------------
die() { echo "setup_tools: $*" >&2; exit 1; }
sha_of() { sha256sum "$1" | cut -d' ' -f1; }

# fetch URL DEST SHA256: download (unless a verified copy exists) and verify.
fetch() {
  local url="$1" dest="$2" want="$3"
  if [ -f "$dest" ] && [ "$(sha_of "$dest")" = "$want" ]; then
    echo "cached:   $(basename "$dest")"
    return
  fi
  echo "download: $url"
  curl -fL --retry 3 --proto '=https' --tlsv1.2 -sS -o "$dest.part" "$url"
  local got; got="$(sha_of "$dest.part")"
  [ "$got" = "$want" ] || { rm -f "$dest.part"; die "sha256 mismatch for $url: got $got want $want"; }
  mv "$dest.part" "$dest"
  echo "verified: $(basename "$dest") sha256=$want"
}

mkdir -p "$TOOLS/bin" "$TOOLS/downloads"
DL="$TOOLS/downloads"

# --- bazelisk -----------------------------------------------------------------
fetch "$BAZELISK_URL" "$DL/bazelisk-linux-amd64-$BAZELISK_VERSION" "$BAZELISK_SHA256"
if [ ! -x "$TOOLS/bin/bazelisk" ] || [ "$(sha_of "$TOOLS/bin/bazelisk")" != "$BAZELISK_SHA256" ]; then
  install -m 0755 "$DL/bazelisk-linux-amd64-$BAZELISK_VERSION" "$TOOLS/bin/bazelisk"
fi
echo "bazelisk: $TOOLS/bin/bazelisk ($BAZELISK_VERSION)"

# --- JDK 21 -------------------------------------------------------------------
fetch "$JDK_URL" "$DL/$JDK_FILE" "$JDK_SHA256"
jdk_ok() { [ -x "$TOOLS/jdk-21/bin/javac" ] && grep -qx "JAVA_VERSION=\"$JDK_JAVA_VERSION\"" "$TOOLS/jdk-21/release"; }
if ! jdk_ok; then
  rm -rf "$TOOLS/jdk-21.tmp"
  mkdir -p "$TOOLS/jdk-21.tmp"
  tar -xzf "$DL/$JDK_FILE" -C "$TOOLS/jdk-21.tmp" --strip-components=1
  rm -rf "$TOOLS/jdk-21"
  mv "$TOOLS/jdk-21.tmp" "$TOOLS/jdk-21"
  jdk_ok || die "JDK install check failed"
fi
echo "jdk:      $TOOLS/jdk-21 ($JDK_RELEASE)"

# --- env.sh -------------------------------------------------------------------
cat > "$TOOLS/env.sh" <<'EOF'
# Generated by scripts/setup_tools.sh -- do not edit; re-run the script instead.
# Source it (bash/zsh/sh):  . /path/to/closure-rs/tools/env.sh
# Idempotent: sourcing it repeatedly leaves PATH with one copy of each entry, at the front.
if [ -n "${BASH_VERSION:-}" ]; then
  eval 'CLOSURE_RS_TOOLS="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"'
else
  CLOSURE_RS_TOOLS="@TOOLS@"
fi
export CLOSURE_RS_TOOLS
export JAVA_HOME="$CLOSURE_RS_TOOLS/jdk-21"
# bazelisk downloads Bazel itself (version from the workspace's .bazelversion) here,
# instead of ~/.cache/bazelisk.
export BAZELISK_HOME="$CLOSURE_RS_TOOLS/bazelisk-home"
_crs_path_prepend() {
  _crs_p=":$PATH:"
  while case "$_crs_p" in *":$1:"*) true ;; *) false ;; esac; do
    _crs_p="${_crs_p%%:"$1":*}:${_crs_p#*:"$1":}"
  done
  _crs_p="${_crs_p#:}"; _crs_p="${_crs_p%:}"
  if [ -n "$_crs_p" ]; then PATH="$1:$_crs_p"; else PATH="$1"; fi
  unset _crs_p
}
_crs_path_prepend "$JAVA_HOME/bin"
_crs_path_prepend "$CLOSURE_RS_TOOLS/bin"
unset -f _crs_path_prepend
export PATH
EOF
# Embed the absolute tools path for non-bash shells.
sed -i "s|@TOOLS@|$TOOLS|" "$TOOLS/env.sh"
echo "env:      $TOOLS/env.sh"

# --- self-check ---------------------------------------------------------------
(
  # shellcheck disable=SC1091
  . "$TOOLS/env.sh"
  [ "$(command -v java)" = "$TOOLS/jdk-21/bin/java" ] || die "java on PATH is not tools/jdk-21"
  [ "$(command -v bazelisk)" = "$TOOLS/bin/bazelisk" ] || die "bazelisk on PATH is not tools/bin"
  java -version 2>&1 | head -1
)
echo "setup_tools: OK"
