#!/usr/bin/env python3
"""Builds corpus/unit/RUST_UNIT_TESTS.md from corpus/unit/rust_unit_tests/*.md (D-015).

Fragments: `_non_harness.md` (every in-scope non-harness test class, gate 0.2 (c)) first, then one
`<Class>.md` per record-bearing class whose post-call-assertion methods are classified
`rust_unit_test` in corpus/unit/postcall/<Class>.json (lines `- <Class>#<method>: <what it checks>`).
`--check` exits 1 when the committed file differs from what the fragments generate.
"""
import os
import sys

from paths import ROOT  # the main checkout (scripts/paths.py)
FRAG = f"{ROOT}/corpus/unit/rust_unit_tests"
OUT = f"{ROOT}/corpus/unit/RUST_UNIT_TESTS.md"


def build():
    names = sorted(n for n in os.listdir(FRAG) if n.endswith(".md"))
    names.sort(key=lambda n: (n != "_non_harness.md", n))
    parts = ["# Rust unit tests (docs/PORTING.md §4.2, gate 0.2 (a) and (c); D-015)\n\n",
             "Generated by `scripts/unit_rust_unit_tests.py` from `corpus/unit/rust_unit_tests/`. "
             "Do not edit by hand.\n\n"]
    for n in names:
        with open(os.path.join(FRAG, n), encoding="utf-8") as f:
            body = f.read().rstrip("\n")
        if not body.lstrip().startswith("#"):
            parts.append(f"## {n[:-3]}\n\n")
        parts.append(body + "\n\n")
    return "".join(parts).rstrip("\n") + "\n"


if __name__ == "__main__":
    text = build()
    if "--check" in sys.argv:
        cur = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else None
        if cur != text:
            print("RUST_UNIT_TESTS.md is stale; run scripts/unit_rust_unit_tests.py")
            sys.exit(1)
        print("RUST_UNIT_TESTS.md is fresh")
    else:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"wrote {OUT}")
