// Generated by corpus/d2/candidates/npm.collect.py for npm:fraction.js@5.3.4 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/fraction.js@5.3.4/package/dist/fraction.js');
globalThis['fraction.js'] = pkg;
