/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.labs.events.touch.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/events/touch.js).
 * Requires goog.labs.events.touch and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_labs_events_touch');

const target = goog.require('goog.labs.events.touch');

goog.exportSymbol('goog.labs.events.touch.getTouchData', target.getTouchData);
