/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.json.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/json/json.js).
 * Requires goog.json and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_json');

const target = goog.require('goog.json');

goog.exportSymbol('goog.json.isValid', target.isValid);
goog.exportSymbol('goog.json.setErrorLogger', target.setErrorLogger);
goog.exportSymbol('goog.json.serialize', target.serialize);
goog.exportSymbol('goog.json.Serializer', target.Serializer);
