/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.i18n.numberformat.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/i18n/numberformat.js).
 * Requires goog.i18n.NumberFormat and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_i18n_NumberFormat');

const target = goog.require('goog.i18n.NumberFormat');

goog.exportSymbol('goog.i18n.NumberFormat', target);
goog.exportSymbol('goog.i18n.NumberFormat.USE_ECMASCRIPT_I18N_NUMFORMAT', target.USE_ECMASCRIPT_I18N_NUMFORMAT);
goog.exportSymbol('goog.i18n.NumberFormat.Format', target.Format);
goog.exportSymbol('goog.i18n.NumberFormat.CurrencyStyle', target.CurrencyStyle);
goog.exportSymbol('goog.i18n.NumberFormat.CompactStyle', target.CompactStyle);
goog.exportSymbol('goog.i18n.NumberFormat.setEnforceAsciiDigits', target.setEnforceAsciiDigits);
goog.exportSymbol('goog.i18n.NumberFormat.isEnforceAsciiDigits', target.isEnforceAsciiDigits);
goog.exportProperty(target.prototype, 'setMinimumFractionDigits', target.prototype.setMinimumFractionDigits);
goog.exportProperty(target.prototype, 'getMinimumFractionDigits', target.prototype.getMinimumFractionDigits);
goog.exportProperty(target.prototype, 'setMaximumFractionDigits', target.prototype.setMaximumFractionDigits);
goog.exportProperty(target.prototype, 'getMaximumFractionDigits', target.prototype.getMaximumFractionDigits);
