/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.html.safehtml.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/html/safehtml.js).
 * Requires goog.html.SafeHtml and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_html_SafeHtml');

const target = goog.require('goog.html.SafeHtml');

goog.exportSymbol('goog.html.SafeHtml', target);
goog.exportSymbol('goog.html.SafeHtml.DOCTYPE_HTML', target.DOCTYPE_HTML);
goog.exportSymbol('goog.html.SafeHtml.EMPTY', target.EMPTY);
goog.exportSymbol('goog.html.SafeHtml.BR', target.BR);
goog.exportProperty(target.prototype, 'getTypedStringValue', target.prototype.getTypedStringValue);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
