/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.labs.net.webchannel.webchannelbase.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/net/webchannel/webchannelbase.js).
 * Requires goog.labs.net.webChannel.WebChannelBase and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_labs_net_webChannel_WebChannelBase');

const target = goog.require('goog.labs.net.webChannel.WebChannelBase');

goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase', target);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.State', target.State);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.FORWARD_CHANNEL_RETRY_TIMEOUT', target.FORWARD_CHANNEL_RETRY_TIMEOUT);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.BACK_CHANNEL_MAX_RETRIES', target.BACK_CHANNEL_MAX_RETRIES);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.RTT_ESTIMATE', target.RTT_ESTIMATE);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.INACTIVE_CHANNEL_RETRY_FACTOR', target.INACTIVE_CHANNEL_RETRY_FACTOR);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.Error', target.Error);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.OUTSTANDING_DATA_BACKCHANNEL_RETRY_CUTOFF', target.OUTSTANDING_DATA_BACKCHANNEL_RETRY_CUTOFF);
goog.exportSymbol('goog.labs.net.webChannel.WebChannelBase.Handler', target.Handler);
goog.exportProperty(target.prototype, 'getServerVersion', target.prototype.getServerVersion);
goog.exportProperty(target.prototype, 'getForwardChannelRequestPool', target.prototype.getForwardChannelRequestPool);
goog.exportProperty(target.prototype, 'getWireCodec', target.prototype.getWireCodec);
goog.exportProperty(target.prototype, 'getChannelDebug', target.prototype.getChannelDebug);
