/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/webstorage.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!Storage} obj
 * @return {!Array<*>}
 */
function closureSelfUseStorage(obj) {
  return [
    obj.length,
    obj.getItem,
    obj.setItem,
    obj.removeItem,
    obj.key(1),
    obj.clear()
  ];
}
globalThis['closureSelfUseStorage'] = closureSelfUseStorage;

/**
 * @param {!WindowSessionStorage} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindowSessionStorage(obj) {
  return [
    obj.sessionStorage
  ];
}
globalThis['closureSelfUseWindowSessionStorage'] = closureSelfUseWindowSessionStorage;

/**
 * @param {!WindowLocalStorage} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindowLocalStorage(obj) {
  return [
    obj.localStorage
  ];
}
globalThis['closureSelfUseWindowLocalStorage'] = closureSelfUseWindowLocalStorage;

/**
 * @param {!StorageEventInit} obj
 * @return {!Array<*>}
 */
function closureSelfUseStorageEventInit(obj) {
  return [
    obj.key,
    obj.oldValue,
    obj.newValue,
    obj.url,
    obj.storageArea
  ];
}
globalThis['closureSelfUseStorageEventInit'] = closureSelfUseStorageEventInit;

/**
 * @param {!StorageEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseStorageEvent(obj) {
  return [
    obj.key,
    obj.oldValue,
    obj.newValue,
    obj.url,
    obj.storageArea,
    obj.initStorageEvent
  ];
}
globalThis['closureSelfUseStorageEvent'] = closureSelfUseStorageEvent;

/**
 * @param {!Window} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindow(obj) {
  return [
    obj.sessionStorage,
    obj.localStorage
  ];
}
globalThis['closureSelfUseWindow'] = closureSelfUseWindow;
