// Generated by corpus/d2/candidates/npm.collect.py for npm:kdbush@4.1.0 (ISC).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/kdbush@4.1.0/package/index.js';
globalThis['default'] = e_default;
