// Generated by corpus/d2/candidates/npm.collect.py for npm:@dagrejs/graphlib@4.0.5 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Graph as e_Graph,
  alg as e_alg,
  json as e_json,
  version as e_version,
} from '../../../../corpus-cache/d2/npm/@dagrejs/graphlib@4.0.5/package/dist/graphlib.esm.js';
globalThis['Graph'] = e_Graph;
globalThis['alg'] = e_alg;
globalThis['json'] = e_json;
globalThis['version'] = e_version;
