// Generated by corpus/d2/candidates/npm.collect.py for npm:medium-zoom@1.1.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/medium-zoom@1.1.0/package/dist/medium-zoom.min.js');
globalThis['medium-zoom'] = pkg;
