// Generated by corpus/d2/candidates/npm.collect.py for npm:colord@2.10.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Colord as e_Colord,
  colord as e_colord,
  extend as e_extend,
  getFormat as e_getFormat,
  random as e_random,
} from '../../../../corpus-cache/d2/npm/colord@2.10.0/package/index.mjs';
globalThis['Colord'] = e_Colord;
globalThis['colord'] = e_colord;
globalThis['extend'] = e_extend;
globalThis['getFormat'] = e_getFormat;
globalThis['random'] = e_random;
