/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.fx.animation.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/fx/animation.js).
 * Requires goog.fx.Animation and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_fx_Animation');

const target = goog.require('goog.fx.Animation');

goog.exportSymbol('goog.fx.Animation', target);
goog.exportSymbol('goog.fx.Animation.EventType', target.EventType);
goog.exportProperty(target.prototype, 'getDuration', target.prototype.getDuration);
goog.exportProperty(target.prototype, 'enableRightPositioningForRtl', target.prototype.enableRightPositioningForRtl);
goog.exportProperty(target.prototype, 'isRightPositioningForRtlEnabled', target.prototype.isRightPositioningForRtlEnabled);
goog.exportProperty(target.prototype, 'play', target.prototype.play);
