// Generated by corpus/d2/candidates/npm.collect.py for npm:js-sha3@0.13.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/js-sha3@0.13.0/package/src/sha3.js');
globalThis['js-sha3'] = pkg;
