/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-js-sha3-0.13.0-pkg-cjs:
 * Node.js/AMD globals referenced by npm:js-sha3@0.13.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;

/** @type {?} */
var global;

/** @type {?} */
var define;
