/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.editor.field.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/editor/field.js).
 * Requires goog.editor.Field and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_editor_Field');

const target = goog.require('goog.editor.Field');

goog.exportSymbol('goog.editor.Field', target);
goog.exportSymbol('goog.editor.Field.EventType', target.EventType);
goog.exportSymbol('goog.editor.Field.setActiveFieldId', target.setActiveFieldId);
goog.exportSymbol('goog.editor.Field.getActiveFieldId', target.getActiveFieldId);
goog.exportSymbol('goog.editor.Field.CHANGE_FREQUENCY', target.CHANGE_FREQUENCY);
goog.exportSymbol('goog.editor.Field.DELAYED_CHANGE_FREQUENCY', target.DELAYED_CHANGE_FREQUENCY);
goog.exportSymbol('goog.editor.Field.SELECTION_CHANGE_KEYCODES', target.SELECTION_CHANGE_KEYCODES);
goog.exportProperty(target.prototype, 'field', target.prototype.field);
goog.exportProperty(target.prototype, 'setUseWindowMouseUp', target.prototype.setUseWindowMouseUp);
goog.exportProperty(target.prototype, 'inModalMode', target.prototype.inModalMode);
goog.exportProperty(target.prototype, 'setModalMode', target.prototype.setModalMode);
