// Generated by corpus/d2/candidates/npm.collect.py for npm:escape-html@1.0.3 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/escape-html@1.0.3/package/index.js');
globalThis['escape-html'] = pkg;
