/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.async.runtest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/async/run_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_async_runTest');

goog.require('goog.async.runTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.async.runtest');
