// Generated by corpus/d2/candidates/npm.collect.py for npm:acorn@8.19.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/acorn@8.19.0/package/dist/acorn.js');
globalThis['Node'] = pkg.Node;
globalThis['Parser'] = pkg.Parser;
globalThis['Position'] = pkg.Position;
globalThis['SourceLocation'] = pkg.SourceLocation;
globalThis['TokContext'] = pkg.TokContext;
globalThis['Token'] = pkg.Token;
globalThis['TokenType'] = pkg.TokenType;
globalThis['defaultOptions'] = pkg.defaultOptions;
globalThis['getLineInfo'] = pkg.getLineInfo;
globalThis['isIdentifierChar'] = pkg.isIdentifierChar;
globalThis['isIdentifierStart'] = pkg.isIdentifierStart;
globalThis['isNewLine'] = pkg.isNewLine;
globalThis['keywordTypes'] = pkg.keywordTypes;
globalThis['lineBreak'] = pkg.lineBreak;
globalThis['lineBreakG'] = pkg.lineBreakG;
globalThis['nonASCIIwhitespace'] = pkg.nonASCIIwhitespace;
globalThis['parse'] = pkg.parse;
globalThis['parseExpressionAt'] = pkg.parseExpressionAt;
globalThis['tokContexts'] = pkg.tokContexts;
globalThis['tokTypes'] = pkg.tokTypes;
globalThis['tokenizer'] = pkg.tokenizer;
globalThis['version'] = pkg.version;
