// Generated by corpus/d2/candidates/npm.collect.py for npm:dompurify@3.4.16 (Apache-2.0).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
} from '../../../../corpus-cache/d2/npm/dompurify@3.4.16/package/dist/purify.es.mjs';
globalThis['default'] = e_default;
