/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-resize-observer-polyfill-1.5.1-pkg-esm:
 * Node.js/AMD globals referenced by npm:resize-observer-polyfill@1.5.1 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;
