// Generated by corpus/d2/candidates/npm.collect.py for npm:@msgpack/msgpack@3.1.3 (ISC).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/@msgpack/msgpack@3.1.3/package/dist.cjs/index.cjs');
globalThis['decodeTimestampExtension'] = pkg.decodeTimestampExtension;
globalThis['encodeTimestampExtension'] = pkg.encodeTimestampExtension;
globalThis['decodeTimestampToTimeSpec'] = pkg.decodeTimestampToTimeSpec;
globalThis['encodeTimeSpecToTimestamp'] = pkg.encodeTimeSpecToTimestamp;
globalThis['encodeDateToTimeSpec'] = pkg.encodeDateToTimeSpec;
globalThis['EXT_TIMESTAMP'] = pkg.EXT_TIMESTAMP;
globalThis['ExtData'] = pkg.ExtData;
globalThis['ExtensionCodec'] = pkg.ExtensionCodec;
globalThis['Encoder'] = pkg.Encoder;
globalThis['DecodeError'] = pkg.DecodeError;
globalThis['Decoder'] = pkg.Decoder;
globalThis['decodeMultiStream'] = pkg.decodeMultiStream;
globalThis['decodeArrayStream'] = pkg.decodeArrayStream;
globalThis['decodeAsync'] = pkg.decodeAsync;
globalThis['decodeMulti'] = pkg.decodeMulti;
globalThis['decode'] = pkg.decode;
globalThis['encode'] = pkg.encode;
