/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.date.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/date/date.js).
 * Requires goog.date and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_date');

const target = goog.require('goog.date');

goog.exportSymbol('goog.date.weekDay', target.weekDay);
goog.exportSymbol('goog.date.month', target.month);
goog.exportSymbol('goog.date.MS_PER_DAY', target.MS_PER_DAY);
goog.exportSymbol('goog.date.isLeapYear', target.isLeapYear);
goog.exportSymbol('goog.date.isLongIsoYear', target.isLongIsoYear);
goog.exportSymbol('goog.date.getNumberOfDaysInMonth', target.getNumberOfDaysInMonth);
goog.exportSymbol('goog.date.isSameDay', target.isSameDay);
goog.exportSymbol('goog.date.isSameMonth', target.isSameMonth);
