/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.uri.utils.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/uri/utils.js).
 * Requires goog.uri.utils and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_uri_utils');

const target = goog.require('goog.uri.utils');

goog.exportSymbol('goog.uri.utils.buildFromEncodedParts', target.buildFromEncodedParts);
goog.exportSymbol('goog.uri.utils.ComponentIndex', target.ComponentIndex);
goog.exportSymbol('goog.uri.utils.setUrlPackageSupportLoggingHandler', target.setUrlPackageSupportLoggingHandler);
goog.exportSymbol('goog.uri.utils.split', target.split);
goog.exportSymbol('goog.uri.utils.getScheme', target.getScheme);
goog.exportSymbol('goog.uri.utils.getEffectiveScheme', target.getEffectiveScheme);
goog.exportSymbol('goog.uri.utils.getUserInfoEncoded', target.getUserInfoEncoded);
goog.exportSymbol('goog.uri.utils.getUserInfo', target.getUserInfo);
