/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.html.sanitizer.htmlsanitizer.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/html/sanitizer/htmlsanitizer.js).
 * Requires goog.html.sanitizer.HtmlSanitizer and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_html_sanitizer_HtmlSanitizer');

const target = goog.require('goog.html.sanitizer.HtmlSanitizer');

goog.exportSymbol('goog.html.sanitizer.HtmlSanitizer', target);
goog.exportSymbol('goog.html.sanitizer.HtmlSanitizer.Builder', target.Builder);
goog.exportSymbol('goog.html.sanitizer.HtmlSanitizer.sanitize', target.sanitize);
goog.exportProperty(target.prototype, 'sanitize', target.prototype.sanitize);
goog.exportProperty(target.prototype, 'sanitizeToDomNode', target.prototype.sanitizeToDomNode);
goog.exportProperty(target.prototype, 'processRoot', target.prototype.processRoot);
goog.exportProperty(target.prototype, 'preProcessHtml', target.prototype.preProcessHtml);
