/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.events.eventtarget.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/events/eventtarget.js).
 * Requires goog.events.EventTarget and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_events_EventTarget');

const target = goog.require('goog.events.EventTarget');

goog.exportSymbol('goog.events.EventTarget', target);
goog.exportProperty(target.prototype, 'getParentEventTarget', target.prototype.getParentEventTarget);
goog.exportProperty(target.prototype, 'setParentEventTarget', target.prototype.setParentEventTarget);
goog.exportProperty(target.prototype, 'dispatchEvent', target.prototype.dispatchEvent);
goog.exportProperty(target.prototype, 'listen', target.prototype.listen);
