/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/deprecated.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!XSLTProcessor} obj
 * @return {!Array<*>}
 */
function closureSelfUseXSLTProcessor(obj) {
  return [
    obj.setParameter,
    obj.clearParameters()
  ];
}
globalThis['closureSelfUseXSLTProcessor'] = closureSelfUseXSLTProcessor;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    opera.postError,
    opera.version()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
