/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/whatwg_encoding.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!TextDecoder} obj
 * @return {!Array<*>}
 */
function closureSelfUseTextDecoder(obj) {
  return [
    obj.encoding,
    obj.fatal,
    obj.ignoreBOM,
    obj.decode()
  ];
}
globalThis['closureSelfUseTextDecoder'] = closureSelfUseTextDecoder;

/**
 * @param {!TextEncoder} obj
 * @return {!Array<*>}
 */
function closureSelfUseTextEncoder(obj) {
  return [
    obj.encoding,
    obj.encodeInto,
    obj.encode()
  ];
}
globalThis['closureSelfUseTextEncoder'] = closureSelfUseTextEncoder;

/**
 * @param {!TextDecoderStream} obj
 * @return {!Array<*>}
 */
function closureSelfUseTextDecoderStream(obj) {
  return [
    obj.encoding,
    obj.fatal,
    obj.ignoreBOM,
    obj.readable,
    obj.writable
  ];
}
globalThis['closureSelfUseTextDecoderStream'] = closureSelfUseTextDecoderStream;

/**
 * @param {!TextEncoderStream} obj
 * @return {!Array<*>}
 */
function closureSelfUseTextEncoderStream(obj) {
  return [
    obj.encoding,
    obj.readable,
    obj.writable
  ];
}
globalThis['closureSelfUseTextEncoderStream'] = closureSelfUseTextEncoderStream;
