/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.labs.pubsub.broadcastpubsub.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/pubsub/broadcastpubsub.js).
 * Requires goog.labs.pubsub.BroadcastPubSub and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_labs_pubsub_BroadcastPubSub');

const target = goog.require('goog.labs.pubsub.BroadcastPubSub');

goog.exportSymbol('goog.labs.pubsub.BroadcastPubSub', target);
goog.exportProperty(target.prototype, 'publish', target.prototype.publish);
goog.exportProperty(target.prototype, 'unsubscribe', target.prototype.unsubscribe);
goog.exportProperty(target.prototype, 'unsubscribeByKey', target.prototype.unsubscribeByKey);
goog.exportProperty(target.prototype, 'subscribe', target.prototype.subscribe);
