/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.asserts.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/asserts.js).
 * Requires goog.testing.asserts and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_asserts');

const target = goog.require('goog.testing.asserts');

goog.exportSymbol('goog.testing.asserts.fail', target.fail);
goog.exportSymbol('goog.testing.asserts.assert', target.assert);
goog.exportSymbol('goog.testing.asserts.assertThrows', target.assertThrows);
goog.exportSymbol('goog.testing.asserts.assertNotThrows', target.assertNotThrows);
goog.exportSymbol('goog.testing.asserts.assertThrowsJsUnitException', target.assertThrowsJsUnitException);
goog.exportSymbol('goog.testing.asserts.assertRejects', target.assertRejects);
goog.exportSymbol('goog.testing.asserts.assertTrue', target.assertTrue);
goog.exportSymbol('goog.testing.asserts.assertFalse', target.assertFalse);
