/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-zrender-6.1.0-pkg-cjs:
 * Node.js/AMD globals referenced by npm:zrender@6.1.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var Buffer;

/** @type {?} */
var global;

/** @type {?} */
var define;
