/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.net.webchannel.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/labs/net/webchannel.js).
 * Requires goog.net.WebChannel and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_net_WebChannel');

const target = goog.require('goog.net.WebChannel');

goog.exportSymbol('goog.net.WebChannel.EventType', target.EventType);
goog.exportSymbol('goog.net.WebChannel.MessageEvent', target.MessageEvent);
goog.exportSymbol('goog.net.WebChannel.ErrorStatus', target.ErrorStatus);
goog.exportSymbol('goog.net.WebChannel.ErrorEvent', target.ErrorEvent);
goog.exportSymbol('goog.net.WebChannel.X_CLIENT_PROTOCOL', target.X_CLIENT_PROTOCOL);
goog.exportSymbol('goog.net.WebChannel.X_CLIENT_PROTOCOL_WEB_CHANNEL', target.X_CLIENT_PROTOCOL_WEB_CHANNEL);
goog.exportSymbol('goog.net.WebChannel.X_CLIENT_WIRE_PROTOCOL', target.X_CLIENT_WIRE_PROTOCOL);
goog.exportSymbol('goog.net.WebChannel.X_HTTP_SESSION_ID', target.X_HTTP_SESSION_ID);
