/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-async-3.2.6-pkg-cjs:
 * Node.js/AMD globals referenced by npm:async@3.2.6 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var process;

/** @type {?} */
var global;

/** @type {?} */
var define;
