/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/flash.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!HTMLObjectElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLObjectElement(obj) {
  return [
    obj.GetVariable,
    obj.Pan,
    obj.SetZoomRect,
    obj.TCallFrame,
    obj.TGetPropertyAsNumber,
    obj.TSetProperty,
    obj.CallFunction('closure-self'),
    obj.TStopPlay(1)
  ];
}
globalThis['closureSelfUseHTMLObjectElement'] = closureSelfUseHTMLObjectElement;
