/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.dom.tagname.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/dom/tagname.js).
 * Requires goog.dom.TagName and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_dom_TagName');

const target = goog.require('goog.dom.TagName');

goog.exportSymbol('goog.dom.TagName.A', target.A);
goog.exportSymbol('goog.dom.TagName.ABBR', target.ABBR);
goog.exportSymbol('goog.dom.TagName.ACRONYM', target.ACRONYM);
goog.exportSymbol('goog.dom.TagName.ADDRESS', target.ADDRESS);
goog.exportSymbol('goog.dom.TagName.APPLET', target.APPLET);
goog.exportSymbol('goog.dom.TagName.AREA', target.AREA);
goog.exportSymbol('goog.dom.TagName.ARTICLE', target.ARTICLE);
goog.exportSymbol('goog.dom.TagName.ASIDE', target.ASIDE);
