/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.cspviolationobserver.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/cspviolationobserver.js).
 * Requires goog.testing.CspViolationObserver and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_CspViolationObserver');

const target = goog.require('goog.testing.CspViolationObserver');

goog.exportSymbol('goog.testing.CspViolationObserver', target);
goog.exportSymbol('goog.testing.CspViolationObserver.getBufferedReports', target.getBufferedReports);
goog.exportSymbol('goog.testing.CspViolationObserver.formatReports', target.formatReports);
goog.exportProperty(target.prototype, 'start', target.prototype.start);
goog.exportProperty(target.prototype, 'stop', target.prototype.stop);
goog.exportProperty(target.prototype, 'setEnabled', target.prototype.setEnabled);
