// Generated by corpus/d2/candidates/npm.collect.py for npm:vanilla-lazyload@19.1.3 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/vanilla-lazyload@19.1.3/package/dist/lazyload.min.js');
globalThis['vanilla-lazyload'] = pkg;
