/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.color.alpha.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/color/alpha.js).
 * Requires goog.color.alpha and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_color_alpha');

const target = goog.require('goog.color.alpha');

goog.exportSymbol('goog.color.alpha.parse', target.parse);
goog.exportSymbol('goog.color.alpha.hexToRgbaStyle', target.hexToRgbaStyle);
goog.exportSymbol('goog.color.alpha.extractHexColor', target.extractHexColor);
goog.exportSymbol('goog.color.alpha.extractAlpha', target.extractAlpha);
goog.exportSymbol('goog.color.alpha.hexToRgba', target.hexToRgba);
goog.exportSymbol('goog.color.alpha.rgbaToHex', target.rgbaToHex);
goog.exportSymbol('goog.color.alpha.hslaToHex', target.hslaToHex);
goog.exportSymbol('goog.color.alpha.rgbaArrayToHex', target.rgbaArrayToHex);
