// Generated by corpus/d2/candidates/npm.collect.py for npm:jssha@3.3.2 (BSD-3-Clause).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/jssha@3.3.2/package/dist/sha.js');
globalThis['jssha'] = pkg;
