// Generated by corpus/d2/candidates/npm.collect.py for npm:bignumber.js@11.1.5 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  BigNumber as e_BigNumber,
  default as e_default,
} from '../../../../corpus-cache/d2/npm/bignumber.js@11.1.5/package/dist/bignumber.mjs';
globalThis['BigNumber'] = e_BigNumber;
globalThis['default'] = e_default;
