/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/ie_dom.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!XMLDOMDocument} obj
 * @return {!Array<*>}
 */
function closureSelfUseXMLDOMDocument(obj) {
  return [
    obj.async,
    obj.onreadystatechange,
    obj.preserveWhiteSpace,
    obj.resolveExternals,
    obj.abort,
    obj.loadXML,
    obj.setProperty('closure-self', 0),
    obj.nodeFromID('closure-self')
  ];
}
globalThis['closureSelfUseXMLDOMDocument'] = closureSelfUseXMLDOMDocument;

/**
 * @param {!ControlRange} obj
 * @return {!Array<*>}
 */
function closureSelfUseControlRange(obj) {
  return [
    obj.add,
    obj.execCommand,
    obj.queryCommandEnabled,
    obj.queryCommandSupported,
    obj.remove,
    obj.select
  ];
}
globalThis['closureSelfUseControlRange'] = closureSelfUseControlRange;

/**
 * @param {!HTMLFiltersCollection} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLFiltersCollection(obj) {
  return [
    obj.length
  ];
}
globalThis['closureSelfUseHTMLFiltersCollection'] = closureSelfUseHTMLFiltersCollection;

/**
 * @param {!AlphaFilter} obj
 * @return {!Array<*>}
 */
function closureSelfUseAlphaFilter(obj) {
  return [
    obj.Opacity
  ];
}
globalThis['closureSelfUseAlphaFilter'] = closureSelfUseAlphaFilter;

/**
 * @param {!XDomainRequest} obj
 * @return {!Array<*>}
 */
function closureSelfUseXDomainRequest(obj) {
  return [
    obj.open,
    obj.onerror,
    obj.onprogress,
    obj.ontimeout,
    obj.timeout,
    obj.contentType,
    obj.abort(),
    obj.send()
  ];
}
globalThis['closureSelfUseXDomainRequest'] = closureSelfUseXDomainRequest;

/**
 * @param {!Window} obj
 * @return {!Array<*>}
 */
function closureSelfUseWindow(obj) {
  return [
    obj.clipboardData,
    obj.dialogWidth,
    obj.offscreenBuffering,
    obj.createPopup,
    obj.setActive,
    obj.msCrypto
  ];
}
globalThis['closureSelfUseWindow'] = closureSelfUseWindow;

/**
 * @param {!HTMLIFrameElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLIFrameElement(obj) {
  return [
    obj.allowTransparency,
    obj.readyState
  ];
}
globalThis['closureSelfUseHTMLIFrameElement'] = closureSelfUseHTMLIFrameElement;

/**
 * @param {!HTMLScriptElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLScriptElement(obj) {
  return [
    obj.readyState
  ];
}
globalThis['closureSelfUseHTMLScriptElement'] = closureSelfUseHTMLScriptElement;

/**
 * @param {!HTMLObjectElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLObjectElement(obj) {
  return [
    obj.readyState
  ];
}
globalThis['closureSelfUseHTMLObjectElement'] = closureSelfUseHTMLObjectElement;

/**
 * @param {!HTMLDocument} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLDocument(obj) {
  return [
    obj.readyState
  ];
}
globalThis['closureSelfUseHTMLDocument'] = closureSelfUseHTMLDocument;

/**
 * @param {!HTMLStyleElement} obj
 * @return {!Array<*>}
 */
function closureSelfUseHTMLStyleElement(obj) {
  return [
    obj.styleSheet
  ];
}
globalThis['closureSelfUseHTMLStyleElement'] = closureSelfUseHTMLStyleElement;

/**
 * @param {!Screen} obj
 * @return {!Array<*>}
 */
function closureSelfUseScreen(obj) {
  return [
    obj.deviceXDPI,
    obj.logicalXDPI,
    obj.logicalYDPI
  ];
}
globalThis['closureSelfUseScreen'] = closureSelfUseScreen;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    RuntimeObject()
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
