/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.proto.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/proto/proto.js).
 * Requires goog.proto and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_proto');

const target = goog.require('goog.proto');

goog.exportSymbol('goog.proto.serialize', target.serialize);
