/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.html.safeurl.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/html/safeurl.js).
 * Requires goog.html.SafeUrl and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_html_SafeUrl');

const target = goog.require('goog.html.SafeUrl');

goog.exportSymbol('goog.html.SafeUrl', target);
goog.exportSymbol('goog.html.SafeUrl.INNOCUOUS_STRING', target.INNOCUOUS_STRING);
goog.exportSymbol('goog.html.SafeUrl.unwrap', target.unwrap);
goog.exportSymbol('goog.html.SafeUrl.fromConstant', target.fromConstant);
goog.exportSymbol('goog.html.SafeUrl.isSafeMimeType', target.isSafeMimeType);
goog.exportSymbol('goog.html.SafeUrl.fromBlob', target.fromBlob);
goog.exportSymbol('goog.html.SafeUrl.revokeObjectUrl', target.revokeObjectUrl);
goog.exportSymbol('goog.html.SafeUrl.fromMediaSource', target.fromMediaSource);
goog.exportSymbol('goog.html.SafeUrl.tryFromDataUrl', target.tryFromDataUrl);
goog.exportProperty(target.prototype, 'toString', target.prototype.toString);
goog.exportProperty(target.prototype, 'implementsGoogStringTypedString', target.prototype.implementsGoogStringTypedString);
goog.exportProperty(target.prototype, 'getTypedStringValue', target.prototype.getTypedStringValue);
