// Generated by corpus/d2/candidates/npm.collect.py for npm:tslib@2.8.1 (0BSD).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/tslib@2.8.1/package/tslib.js');
globalThis['tslib'] = pkg;
