/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.mock.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/mock.js).
 * Requires goog.testing.Mock and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_Mock');

const target = goog.require('goog.testing.Mock');

goog.exportSymbol('goog.testing.Mock', target);
goog.exportSymbol('goog.testing.Mock.LOOSE', target.LOOSE);
goog.exportSymbol('goog.testing.Mock.STRICT', target.STRICT);
goog.exportSymbol('goog.testing.Mock.record', target.record);
goog.exportProperty(target.prototype, '$proxy', target.prototype.$proxy);
goog.exportProperty(target.prototype, '$registerArgumentListVerifier', target.prototype.$registerArgumentListVerifier);
goog.exportProperty(target.prototype, '$mockMethod', target.prototype.$mockMethod);
goog.exportProperty(target.prototype, '$maybeThrow', target.prototype.$maybeThrow);
