/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/webgl2_compute.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!WebGL2ComputeRenderingContext} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGL2ComputeRenderingContext(obj) {
  return [
    obj.COMPUTE_SHADER,
    obj.ATOMIC_COUNTER_BUFFER_INDEX,
    obj.TEXTURE_UPDATE_BARRIER_BIT,
    obj.MAX_SAMPLE_MASK_WORDS,
    obj.getProgramResourceName,
    obj.vertexAttribBinding,
    obj.dispatchCompute(1, 1, 1),
    obj.vertexBindingDivisor(1, 1)
  ];
}
globalThis['closureSelfUseWebGL2ComputeRenderingContext'] = closureSelfUseWebGL2ComputeRenderingContext;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    WebGL2ComputeRenderingContext.COMPUTE_SHADER,
    WebGL2ComputeRenderingContext.FRAMEBUFFER_DEFAULT_WIDTH,
    WebGL2ComputeRenderingContext.TYPE,
    WebGL2ComputeRenderingContext.VERTEX_SHADER_BIT,
    WebGL2ComputeRenderingContext.MAX_COMBINED_IMAGE_UNIFORMS,
    WebGL2ComputeRenderingContext.SHADER_STORAGE_BARRIER_BIT,
    WebGL2ComputeRenderingContext.READ_WRITE,
    WebGL2ComputeRenderingContext.SAMPLE_MASK,
    WebGL2ComputeRenderingContext.TEXTURE_STENCIL_SIZE,
    WebGL2ComputeRenderingContext.MAX_VERTEX_ATTRIB_STRIDE
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
