// Generated by corpus/d2/candidates/npm.collect.py for npm:uuid@14.0.2 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  MAX as e_MAX,
  NIL as e_NIL,
  parse as e_parse,
  stringify as e_stringify,
  v1 as e_v1,
  v1ToV6 as e_v1ToV6,
  v3 as e_v3,
  v4 as e_v4,
  v5 as e_v5,
  v6 as e_v6,
  v6ToV1 as e_v6ToV1,
  v7 as e_v7,
  validate as e_validate,
  version as e_version,
} from '../../../../corpus-cache/d2/npm/uuid@14.0.2/package/dist/index.js';
globalThis['MAX'] = e_MAX;
globalThis['NIL'] = e_NIL;
globalThis['parse'] = e_parse;
globalThis['stringify'] = e_stringify;
globalThis['v1'] = e_v1;
globalThis['v1ToV6'] = e_v1ToV6;
globalThis['v3'] = e_v3;
globalThis['v4'] = e_v4;
globalThis['v5'] = e_v5;
globalThis['v6'] = e_v6;
globalThis['v6ToV1'] = e_v6ToV1;
globalThis['v7'] = e_v7;
globalThis['validate'] = e_validate;
globalThis['version'] = e_version;
