// Generated by corpus/d2/candidates/npm.collect.py for npm:riot@10.1.6 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  __ as e___,
  component as e_component,
  createPureComponent as e_createPureComponent,
  install as e_install,
  mount as e_mount,
  pure as e_pure,
  register as e_register,
  uninstall as e_uninstall,
  unmount as e_unmount,
  unregister as e_unregister,
  version as e_version,
  withTypes as e_withTypes,
} from '../../../../corpus-cache/d2/npm/riot@10.1.6/package/esm/riot.js';
globalThis['__'] = e___;
globalThis['component'] = e_component;
globalThis['createPureComponent'] = e_createPureComponent;
globalThis['install'] = e_install;
globalThis['mount'] = e_mount;
globalThis['pure'] = e_pure;
globalThis['register'] = e_register;
globalThis['uninstall'] = e_uninstall;
globalThis['unmount'] = e_unmount;
globalThis['unregister'] = e_unregister;
globalThis['version'] = e_version;
globalThis['withTypes'] = e_withTypes;
