/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-riot-10.1.6-pkg-esm:
 * Node.js/AMD globals referenced by npm:riot@10.1.6 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var exports;
