/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-test-goog.tweak.registrytest.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/tweak/registry_test.js).
 * Loads the test suite; its registration side effects keep the output live.
 */
goog.module('closure_library_shim.goog_tweak_RegistryTest');

goog.require('goog.tweak.RegistryTest');

goog.exportSymbol('closureLibraryCase', 'closure-library-test-goog.tweak.registrytest');
