/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.loader.activemodulemanager.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/loader/activemodulemanager.js).
 * Requires goog.loader.activeModuleManager and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_loader_activeModuleManager');

const target = goog.require('goog.loader.activeModuleManager');

goog.exportSymbol('goog.loader.activeModuleManager.get', target.get);
goog.exportSymbol('goog.loader.activeModuleManager.set', target.set);
goog.exportSymbol('goog.loader.activeModuleManager.setDefault', target.setDefault);
goog.exportSymbol('goog.loader.activeModuleManager.beforeLoadModuleCode', target.beforeLoadModuleCode);
goog.exportSymbol('goog.loader.activeModuleManager.setLoaded', target.setLoaded);
goog.exportSymbol('goog.loader.activeModuleManager.maybeInitialize', target.maybeInitialize);
goog.exportSymbol('goog.loader.activeModuleManager.reset', target.reset);
goog.exportSymbol('goog.loader.activeModuleManager.configure', target.configure);
