// Generated by corpus/d2/candidates/npm.collect.py for npm:@tweenjs/tween.js@25.0.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  Easing as e_Easing,
  Group as e_Group,
  Interpolation as e_Interpolation,
  Sequence as e_Sequence,
  Tween as e_Tween,
  VERSION as e_VERSION,
  add as e_add,
  default as e_default,
  getAll as e_getAll,
  nextId as e_nextId,
  now as e_now,
  remove as e_remove,
  removeAll as e_removeAll,
  update as e_update,
} from '../../../../corpus-cache/d2/npm/@tweenjs/tween.js@25.0.0/package/dist/tween.esm.js';
globalThis['Easing'] = e_Easing;
globalThis['Group'] = e_Group;
globalThis['Interpolation'] = e_Interpolation;
globalThis['Sequence'] = e_Sequence;
globalThis['Tween'] = e_Tween;
globalThis['VERSION'] = e_VERSION;
globalThis['add'] = e_add;
globalThis['default'] = e_default;
globalThis['getAll'] = e_getAll;
globalThis['nextId'] = e_nextId;
globalThis['now'] = e_now;
globalThis['remove'] = e_remove;
globalThis['removeAll'] = e_removeAll;
globalThis['update'] = e_update;
