/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-tweenjs__tween.js-25.0.0-pkg-esm:
 * Node.js/AMD globals referenced by npm:@tweenjs/tween.js@25.0.0 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var exports;
