/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/webassembly.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!WebAssembly.WebAssemblyCompileOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyWebAssemblyCompileOptions(obj) {
  return [
    obj.builtins,
    obj.importedStringConstants
  ];
}
globalThis['closureSelfUseWebAssemblyWebAssemblyCompileOptions'] = closureSelfUseWebAssemblyWebAssemblyCompileOptions;

/**
 * @param {!WebAssembly.WebAssemblyInstantiatedSource} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyWebAssemblyInstantiatedSource(obj) {
  return [
    obj.instance,
    obj.module
  ];
}
globalThis['closureSelfUseWebAssemblyWebAssemblyInstantiatedSource'] = closureSelfUseWebAssemblyWebAssemblyInstantiatedSource;

/**
 * @param {!WebAssembly.Module} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyModule(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebAssemblyModule'] = closureSelfUseWebAssemblyModule;

/**
 * @param {!WebAssembly.Instance} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyInstance(obj) {
  return [
    obj.exports
  ];
}
globalThis['closureSelfUseWebAssemblyInstance'] = closureSelfUseWebAssemblyInstance;

/**
 * @param {!WebAssembly.MemoryDescriptor} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyMemoryDescriptor(obj) {
  return [
    obj.address,
    obj.initial,
    obj.maximum,
    obj.shared
  ];
}
globalThis['closureSelfUseWebAssemblyMemoryDescriptor'] = closureSelfUseWebAssemblyMemoryDescriptor;

/**
 * @param {!WebAssembly.Memory} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyMemory(obj) {
  return [
    obj.toFixedLengthBuffer,
    obj.buffer,
    obj.grow(1),
    obj.toResizableBuffer()
  ];
}
globalThis['closureSelfUseWebAssemblyMemory'] = closureSelfUseWebAssemblyMemory;

/**
 * @param {!WebAssembly.TableDescriptor} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyTableDescriptor(obj) {
  return [
    obj.address,
    obj.element,
    obj.initial,
    obj.maximum
  ];
}
globalThis['closureSelfUseWebAssemblyTableDescriptor'] = closureSelfUseWebAssemblyTableDescriptor;

/**
 * @param {!WebAssembly.Table} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyTable(obj) {
  return [
    obj.grow,
    obj.length,
    obj.set,
    obj.get(1)
  ];
}
globalThis['closureSelfUseWebAssemblyTable'] = closureSelfUseWebAssemblyTable;

/**
 * @param {!WebAssembly.TagType} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyTagType(obj) {
  return [
    obj.parameters
  ];
}
globalThis['closureSelfUseWebAssemblyTagType'] = closureSelfUseWebAssemblyTagType;

/**
 * @param {!WebAssemblyExceptionOptions} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyExceptionOptions(obj) {
  return [
    obj.traceStack
  ];
}
globalThis['closureSelfUseWebAssemblyExceptionOptions'] = closureSelfUseWebAssemblyExceptionOptions;

/**
 * @param {!WebAssembly.Exception} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyException(obj) {
  return [
    obj.stack,
    obj.getArg,
    obj.is
  ];
}
globalThis['closureSelfUseWebAssemblyException'] = closureSelfUseWebAssemblyException;

/**
 * @param {!WebAssembly.Global} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebAssemblyGlobal(obj) {
  return [
    obj.value
  ];
}
globalThis['closureSelfUseWebAssemblyGlobal'] = closureSelfUseWebAssemblyGlobal;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    WebAssembly.JSTag,
    WebAssembly.instantiate,
    WebAssembly.instantiateStreaming,
    WebAssembly.compile,
    WebAssembly.compileStreaming,
    WebAssembly.validate,
    WebAssembly.Module.exports,
    WebAssembly.Module.imports,
    WebAssembly.Module.customSections
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!TableFunction} t0
 * @param {!WebAssembly.ValueTypeMap} t1
 * @param {!WebAssembly.ExportValue} t2
 * @param {!WebAssembly.ModuleImports} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
