/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.style.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/style/style.js).
 * Requires goog.testing.style and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_style');

const target = goog.require('goog.testing.style');

goog.exportSymbol('goog.testing.style.intersects', target.intersects);
goog.exportSymbol('goog.testing.style.hasVisibleDimensions', target.hasVisibleDimensions);
goog.exportSymbol('goog.testing.style.isVisible', target.isVisible);
goog.exportSymbol('goog.testing.style.isOnScreen', target.isOnScreen);
