/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.editor.fieldmock.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/editor/fieldmock.js).
 * Requires goog.testing.editor.FieldMock and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_editor_FieldMock');

const target = goog.require('goog.testing.editor.FieldMock');

goog.exportSymbol('goog.testing.editor.FieldMock', target);
goog.exportProperty(target.prototype, '$setIgnoreUnexpectedCalls', target.prototype.$setIgnoreUnexpectedCalls);
goog.exportProperty(target.prototype, '$recordExpectation', target.prototype.$recordExpectation);
goog.exportProperty(target.prototype, '$recordCall', target.prototype.$recordCall);
goog.exportProperty(target.prototype, '$reset', target.prototype.$reset);
