/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.useragent.keyboard.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/useragent/keyboard.js).
 * Requires goog.userAgent.keyboard and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_userAgent_keyboard');

const target = goog.require('goog.userAgent.keyboard');

goog.exportSymbol('goog.userAgent.keyboard.MAC_KEYBOARD', target.MAC_KEYBOARD);
