/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/nonstandard_audio.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!webkitAudioContext} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebkitAudioContext(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebkitAudioContext'] = closureSelfUseWebkitAudioContext;

/**
 * @param {!webkitOfflineAudioContext} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebkitOfflineAudioContext(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebkitOfflineAudioContext'] = closureSelfUseWebkitOfflineAudioContext;

/**
 * @param {!webkitAudioPannerNode} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebkitAudioPannerNode(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebkitAudioPannerNode'] = closureSelfUseWebkitAudioPannerNode;

/**
 * @param {!webkitPannerNode} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebkitPannerNode(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebkitPannerNode'] = closureSelfUseWebkitPannerNode;

/**
 * @param {!Audio} obj
 * @return {!Array<*>}
 */
function closureSelfUseAudio(obj) {
  return [
    obj.mozWriteAudio,
    obj.mozSetup(1, 1),
    obj.mozCurrentSampleOffset()
  ];
}
globalThis['closureSelfUseAudio'] = closureSelfUseAudio;
