// Generated by corpus/d2/candidates/npm.collect.py for npm:@ungap/structured-clone@1.4.0 (ISC).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  default as e_default,
  deserialize as e_deserialize,
  serialize as e_serialize,
} from '../../../../corpus-cache/d2/npm/@ungap/structured-clone@1.4.0/package/esm/index.js';
globalThis['default'] = e_default;
globalThis['deserialize'] = e_deserialize;
globalThis['serialize'] = e_serialize;
