// closure-rs D2 whole-program case whole-program-dequal-2.0.3: runs the own test suite of
// dequal@2.0.3 (lukeed/dequal @ 37d4f27de03f) against a compiled output.
//   node corpus/d2/shims/whole-program-dequal-2.0.3/run.mjs <compiled.js>   (the case's test_command)
//   node corpus/d2/shims/whole-program-dequal-2.0.3/run.mjs --original      (same tests, original sources)
// Generated by corpus/d2/candidates/whole-program.gen.mjs; do not edit.
import { runCase } from './harness.mjs';

await runCase(import.meta.url, {
  "id": "whole-program-dequal-2.0.3",
  "global": "dequal",
  "testDir": "corpus-cache/d2/whole-program/dequal@2.0.3/repo",
  "framework": "uvu",
  "files": [
    "test/index.js",
    "test/lite.js"
  ],
  "modules": {
    "../src": {
      "path": [
        "src"
      ],
      "namespace": true
    },
    "../src/lite": {
      "path": [
        "lite"
      ],
      "namespace": true
    }
  },
  "expectTests": 44
});
