// Generated by corpus/d2/candidates/npm.collect.py for npm:web-streams-polyfill@4.3.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  ByteLengthQueuingStrategy as e_ByteLengthQueuingStrategy,
  CountQueuingStrategy as e_CountQueuingStrategy,
  ReadableByteStreamController as e_ReadableByteStreamController,
  ReadableStream as e_ReadableStream,
  ReadableStreamBYOBReader as e_ReadableStreamBYOBReader,
  ReadableStreamBYOBRequest as e_ReadableStreamBYOBRequest,
  ReadableStreamDefaultController as e_ReadableStreamDefaultController,
  ReadableStreamDefaultReader as e_ReadableStreamDefaultReader,
  TransformStream as e_TransformStream,
  TransformStreamDefaultController as e_TransformStreamDefaultController,
  WritableStream as e_WritableStream,
  WritableStreamDefaultController as e_WritableStreamDefaultController,
  WritableStreamDefaultWriter as e_WritableStreamDefaultWriter,
} from '../../../../corpus-cache/d2/npm/web-streams-polyfill@4.3.0/package/dist/ponyfill.mjs';
globalThis['ByteLengthQueuingStrategy'] = e_ByteLengthQueuingStrategy;
globalThis['CountQueuingStrategy'] = e_CountQueuingStrategy;
globalThis['ReadableByteStreamController'] = e_ReadableByteStreamController;
globalThis['ReadableStream'] = e_ReadableStream;
globalThis['ReadableStreamBYOBReader'] = e_ReadableStreamBYOBReader;
globalThis['ReadableStreamBYOBRequest'] = e_ReadableStreamBYOBRequest;
globalThis['ReadableStreamDefaultController'] = e_ReadableStreamDefaultController;
globalThis['ReadableStreamDefaultReader'] = e_ReadableStreamDefaultReader;
globalThis['TransformStream'] = e_TransformStream;
globalThis['TransformStreamDefaultController'] = e_TransformStreamDefaultController;
globalThis['WritableStream'] = e_WritableStream;
globalThis['WritableStreamDefaultController'] = e_WritableStreamDefaultController;
globalThis['WritableStreamDefaultWriter'] = e_WritableStreamDefaultWriter;
