/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.graphics.affinetransform.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/graphics/affinetransform.js).
 * Requires goog.graphics.AffineTransform and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_graphics_AffineTransform');

const target = goog.require('goog.graphics.AffineTransform');

goog.exportSymbol('goog.graphics.AffineTransform', target);
goog.exportSymbol('goog.graphics.AffineTransform.getScaleInstance', target.getScaleInstance);
goog.exportSymbol('goog.graphics.AffineTransform.getTranslateInstance', target.getTranslateInstance);
goog.exportSymbol('goog.graphics.AffineTransform.getShearInstance', target.getShearInstance);
goog.exportSymbol('goog.graphics.AffineTransform.getRotateInstance', target.getRotateInstance);
goog.exportProperty(target.prototype, 'isIdentity', target.prototype.isIdentity);
goog.exportProperty(target.prototype, 'clone', target.prototype.clone);
goog.exportProperty(target.prototype, 'setTransform', target.prototype.setTransform);
goog.exportProperty(target.prototype, 'copyFrom', target.prototype.copyFrom);
