/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/webgl.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!WebGLRenderingContext} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLRenderingContext(obj) {
  return [
    obj.DEPTH_BUFFER_BIT,
    obj.STENCIL_BACK_VALUE_MASK,
    obj.LINEAR_MIPMAP_LINEAR,
    obj.STENCIL_INDEX,
    obj.disableVertexAttribArray,
    obj.vertexAttribPointer,
    obj.getContextAttributes(),
    obj.viewport(1, 1, 1, 1)
  ];
}
globalThis['closureSelfUseWebGLRenderingContext'] = closureSelfUseWebGLRenderingContext;

/**
 * @param {!WebGLContextEvent} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLContextEvent(obj) {
  return [
    obj.statusMessage
  ];
}
globalThis['closureSelfUseWebGLContextEvent'] = closureSelfUseWebGLContextEvent;

/**
 * @param {!WebGLShaderPrecisionFormat} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLShaderPrecisionFormat(obj) {
  return [
    obj.rangeMin,
    obj.rangeMax,
    obj.precision
  ];
}
globalThis['closureSelfUseWebGLShaderPrecisionFormat'] = closureSelfUseWebGLShaderPrecisionFormat;

/**
 * @param {!OES_texture_half_float} obj
 * @return {!Array<*>}
 */
function closureSelfUseOES_texture_half_float(obj) {
  return [
    obj.HALF_FLOAT_OES
  ];
}
globalThis['closureSelfUseOES_texture_half_float'] = closureSelfUseOES_texture_half_float;

/**
 * @param {!OES_standard_derivatives} obj
 * @return {!Array<*>}
 */
function closureSelfUseOES_standard_derivatives(obj) {
  return [
    obj.FRAGMENT_SHADER_DERIVATIVE_HINT_OES
  ];
}
globalThis['closureSelfUseOES_standard_derivatives'] = closureSelfUseOES_standard_derivatives;

/**
 * @param {!OES_vertex_array_object} obj
 * @return {!Array<*>}
 */
function closureSelfUseOES_vertex_array_object(obj) {
  return [
    obj.VERTEX_ARRAY_BINDING_OES,
    obj.deleteVertexArrayOES,
    obj.isVertexArrayOES,
    obj.bindVertexArrayOES,
    obj.createVertexArrayOES()
  ];
}
globalThis['closureSelfUseOES_vertex_array_object'] = closureSelfUseOES_vertex_array_object;

/**
 * @param {!WEBGL_debug_shaders} obj
 * @return {!Array<*>}
 */
function closureSelfUseWEBGL_debug_shaders(obj) {
  return [
    obj.getTranslatedShaderSource
  ];
}
globalThis['closureSelfUseWEBGL_debug_shaders'] = closureSelfUseWEBGL_debug_shaders;

/**
 * @param {!WEBGL_compressed_texture_s3tc} obj
 * @return {!Array<*>}
 */
function closureSelfUseWEBGL_compressed_texture_s3tc(obj) {
  return [
    obj.COMPRESSED_RGB_S3TC_DXT1_EXT,
    obj.COMPRESSED_RGBA_S3TC_DXT1_EXT,
    obj.COMPRESSED_RGBA_S3TC_DXT3_EXT,
    obj.COMPRESSED_RGBA_S3TC_DXT5_EXT
  ];
}
globalThis['closureSelfUseWEBGL_compressed_texture_s3tc'] = closureSelfUseWEBGL_compressed_texture_s3tc;

/**
 * @param {!WEBGL_draw_buffers} obj
 * @return {!Array<*>}
 */
function closureSelfUseWEBGL_draw_buffers(obj) {
  return [
    obj.COLOR_ATTACHMENT0_WEBGL,
    obj.COLOR_ATTACHMENT7_WEBGL,
    obj.COLOR_ATTACHMENT14_WEBGL,
    obj.DRAW_BUFFER4_WEBGL,
    obj.DRAW_BUFFER11_WEBGL,
    obj.drawBuffersWEBGL
  ];
}
globalThis['closureSelfUseWEBGL_draw_buffers'] = closureSelfUseWEBGL_draw_buffers;

/**
 * @param {!ANGLE_instanced_arrays} obj
 * @return {!Array<*>}
 */
function closureSelfUseANGLE_instanced_arrays(obj) {
  return [
    obj.VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE,
    obj.drawElementsInstancedANGLE,
    obj.drawArraysInstancedANGLE(1, 1, 1, 1),
    obj.vertexAttribDivisorANGLE(1, 1)
  ];
}
globalThis['closureSelfUseANGLE_instanced_arrays'] = closureSelfUseANGLE_instanced_arrays;

/**
 * @param {!EXT_color_buffer_half_float} obj
 * @return {!Array<*>}
 */
function closureSelfUseEXT_color_buffer_half_float(obj) {
  return [
    obj.FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT,
    obj.RGB16F_EXT,
    obj.RGBA16F_EXT,
    obj.UNSIGNED_NORMALIZED_EXT
  ];
}
globalThis['closureSelfUseEXT_color_buffer_half_float'] = closureSelfUseEXT_color_buffer_half_float;

/**
 * @param {!WEBGL_compressed_texture_etc1} obj
 * @return {!Array<*>}
 */
function closureSelfUseWEBGL_compressed_texture_etc1(obj) {
  return [
    obj.COMPRESSED_RGB_ETC1_WEBGL
  ];
}
globalThis['closureSelfUseWEBGL_compressed_texture_etc1'] = closureSelfUseWEBGL_compressed_texture_etc1;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    WebGLRenderingContext.DEPTH_BUFFER_BIT,
    WebGLRenderingContext.CONSTANT_ALPHA,
    WebGLRenderingContext.ALIASED_POINT_SIZE_RANGE,
    WebGLRenderingContext.RED_BITS,
    WebGLRenderingContext.UNSIGNED_SHORT_5_6_5,
    WebGLRenderingContext.DECR_WRAP,
    WebGLRenderingContext.TEXTURE8,
    WebGLRenderingContext.INT_VEC3,
    WebGLRenderingContext.STENCIL_INDEX8,
    WebGLRenderingContext.BROWSER_DEFAULT_WEBGL
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;

/**
 * @param {!TexImageSource} t0
 * @param {!EXT_blend_minmax} t1
 * @param {!OVR_multiview2} t2
 * @param {!WEBGL_compressed_texture_s3tc_srgb} t3
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0, t1, t2, t3) {
  return [
    t0,
    t1,
    t2,
    t3
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
