// Generated by corpus/d2/candidates/npm.collect.py for npm:is-plain-object@5.1.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  isPlainObject as e_isPlainObject,
} from '../../../../corpus-cache/d2/npm/is-plain-object@5.1.0/package/dist/is-plain-object.mjs';
globalThis['isPlainObject'] = e_isPlainObject;
