/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.history.event.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/history/event.js).
 * Requires goog.history.Event and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_history_Event');

const target = goog.require('goog.history.Event');

goog.exportSymbol('goog.history.Event', target);
goog.exportProperty(target.prototype, 'hasPropagationStopped', target.prototype.hasPropagationStopped);
goog.exportProperty(target.prototype, 'stopPropagation', target.prototype.stopPropagation);
goog.exportProperty(target.prototype, 'preventDefault', target.prototype.preventDefault);
