/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-engine.io-parser-5.2.3-pkg-cjs:
 * Node.js/AMD globals referenced by npm:engine.io-parser@5.2.3 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var Buffer;
