/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.messaging.mockmessageevent.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/messaging/mockmessageevent.js).
 * Requires goog.testing.messaging.MockMessageEvent and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_messaging_MockMessageEvent');

const target = goog.require('goog.testing.messaging.MockMessageEvent');

goog.exportSymbol('goog.testing.messaging.MockMessageEvent', target);
goog.exportSymbol('goog.testing.messaging.MockMessageEvent.wrap', target.wrap);
goog.exportProperty(target.prototype, 'defaultPrevented', target.prototype.defaultPrevented);
goog.exportProperty(target.prototype, 'stopPropagation', target.prototype.stopPropagation);
goog.exportProperty(target.prototype, 'preventDefault', target.prototype.preventDefault);
