/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.html.sanitizer.attributeallowlists.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/html/sanitizer/attributeallowlists.js).
 * Requires goog.html.sanitizer.attributeallowlists and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_html_sanitizer_attributeallowlists');

const target = goog.require('goog.html.sanitizer.attributeallowlists');

goog.exportSymbol('goog.html.sanitizer.attributeallowlists.AllowedAttributes', target.AllowedAttributes);
goog.exportSymbol('goog.html.sanitizer.attributeallowlists.SanitizedAttributeAllowlist', target.SanitizedAttributeAllowlist);
