/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.log.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/log/log.js).
 * Requires goog.log and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_log');

const target = goog.require('goog.log');

goog.exportSymbol('goog.log.ROOT_LOGGER_NAME', target.ROOT_LOGGER_NAME);
goog.exportSymbol('goog.log.Level', target.Level);
goog.exportSymbol('goog.log.LogBuffer', target.LogBuffer);
goog.exportSymbol('goog.log.LogRecord', target.LogRecord);
goog.exportSymbol('goog.log.getLogger', target.getLogger);
goog.exportSymbol('goog.log.getRootLogger', target.getRootLogger);
goog.exportSymbol('goog.log.addHandler', target.addHandler);
goog.exportSymbol('goog.log.removeHandler', target.removeHandler);
