/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.dom.forms.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/dom/forms.js).
 * Requires goog.dom.forms and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_dom_forms');

const target = goog.require('goog.dom.forms');

goog.exportSymbol('goog.dom.forms.submitFormInNewWindow', target.submitFormInNewWindow);
goog.exportSymbol('goog.dom.forms.submitFormDataInNewWindow', target.submitFormDataInNewWindow);
goog.exportSymbol('goog.dom.forms.getFormDataMap', target.getFormDataMap);
goog.exportSymbol('goog.dom.forms.getFormDataString', target.getFormDataString);
goog.exportSymbol('goog.dom.forms.hasFileInput', target.hasFileInput);
goog.exportSymbol('goog.dom.forms.setDisabled', target.setDisabled);
goog.exportSymbol('goog.dom.forms.focusAndSelect', target.focusAndSelect);
goog.exportSymbol('goog.dom.forms.hasValue', target.hasValue);
