// Generated by corpus/d2/candidates/npm.collect.py for npm:goober@2.1.19 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  css as e_css,
  extractCss as e_extractCss,
  glob as e_glob,
  keyframes as e_keyframes,
  setup as e_setup,
  styled as e_styled,
} from '../../../../corpus-cache/d2/npm/goober@2.1.19/package/dist/goober.modern.js';
globalThis['css'] = e_css;
globalThis['extractCss'] = e_extractCss;
globalThis['glob'] = e_glob;
globalThis['keyframes'] = e_keyframes;
globalThis['setup'] = e_setup;
globalThis['styled'] = e_styled;
