/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.testing.i18n.asserts.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/testing/i18n/asserts.js).
 * Requires goog.testing.i18n.asserts and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_testing_i18n_asserts');

const target = goog.require('goog.testing.i18n.asserts');

goog.exportSymbol('goog.testing.i18n.asserts.assertI18nEquals', target.assertI18nEquals);
goog.exportSymbol('goog.testing.i18n.asserts.assertI18nContains', target.assertI18nContains);
goog.exportSymbol('goog.testing.i18n.asserts.addI18nMapping', target.addI18nMapping);
