// Generated by corpus/d2/candidates/npm.collect.py for npm:redux-thunk@3.1.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  thunk as e_thunk,
  withExtraArgument as e_withExtraArgument,
} from '../../../../corpus-cache/d2/npm/redux-thunk@3.1.0/package/dist/redux-thunk.mjs';
globalThis['thunk'] = e_thunk;
globalThis['withExtraArgument'] = e_withExtraArgument;
