// Generated by corpus/d2/candidates/npm.collect.py for npm:colord@2.10.0 (MIT).
// Requires the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
var pkg = require('../../../../corpus-cache/d2/npm/colord@2.10.0/package/index.js');
globalThis['Colord'] = pkg.Colord;
globalThis['colord'] = pkg.colord;
globalThis['extend'] = pkg.extend;
globalThis['getFormat'] = pkg.getFormat;
globalThis['random'] = pkg.random;
