/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/nonstandard_console.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!MemoryInfo} obj
 * @return {!Array<*>}
 */
function closureSelfUseMemoryInfo(obj) {
  return [
    obj.totalJSHeapSize,
    obj.usedJSHeapSize,
    obj.jsHeapSizeLimit
  ];
}
globalThis['closureSelfUseMemoryInfo'] = closureSelfUseMemoryInfo;

/**
 * @param {!Console} obj
 * @return {!Array<*>}
 */
function closureSelfUseConsole(obj) {
  return [
    obj.profile,
    obj.profiles,
    obj.profileEnd,
    obj.timeStamp,
    obj.memory,
    obj.markTimeline(0),
    obj.createTask('closure-self')
  ];
}
globalThis['closureSelfUseConsole'] = closureSelfUseConsole;
