/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/page_visibility.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!VisibilityState} t0
 * @return {!Array<*>}
 */
function closureSelfUseTypedefs(t0) {
  return [
    t0
  ];
}
globalThis['closureSelfUseTypedefs'] = closureSelfUseTypedefs;
