/**
 * @fileoverview Generated D2 entry shim for closure-rs case closure-library-prune-goog.promise.
 * Generated by corpus/d2/candidates/closure-library.gen.py from Closure Library
 * v20230802 (closure/goog/promise/promise.js).
 * Requires goog.Promise and exports part of its public API so that the
 * ADVANCED output stays non-trivial.
 */
goog.module('closure_library_shim.goog_Promise');

const target = goog.require('goog.Promise');

goog.exportSymbol('goog.Promise', target);
goog.exportSymbol('goog.Promise.resolve', target.resolve);
goog.exportSymbol('goog.Promise.reject', target.reject);
goog.exportSymbol('goog.Promise.race', target.race);
goog.exportSymbol('goog.Promise.all', target.all);
goog.exportSymbol('goog.Promise.allSettled', target.allSettled);
goog.exportSymbol('goog.Promise.firstFulfilled', target.firstFulfilled);
goog.exportSymbol('goog.Promise.withResolver', target.withResolver);
goog.exportSymbol('goog.Promise.setUnhandledRejectionHandler', target.setUnhandledRejectionHandler);
goog.exportProperty(target.prototype, 'then', target.prototype.then);
goog.exportProperty(target.prototype, 'thenAlways', target.prototype.thenAlways);
goog.exportProperty(target.prototype, 'thenCatch', target.prototype.thenCatch);
goog.exportProperty(target.prototype, 'catch', target.prototype.catch);
