/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/webgl2.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!WebGL2RenderingContext} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGL2RenderingContext(obj) {
  return [
    obj.READ_BUFFER,
    obj.SRGB,
    obj.DEPTH_STENCIL_ATTACHMENT,
    obj.UNIFORM_SIZE,
    obj.uniform4fv,
    obj.bindVertexArray,
    obj.copyBufferSubData(1, 1, 1, 1, 1),
    obj.createVertexArray()
  ];
}
globalThis['closureSelfUseWebGL2RenderingContext'] = closureSelfUseWebGL2RenderingContext;

/**
 * @param {!WebGLQuery} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLQuery(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebGLQuery'] = closureSelfUseWebGLQuery;

/**
 * @param {!WebGLSampler} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLSampler(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebGLSampler'] = closureSelfUseWebGLSampler;

/**
 * @param {!WebGLSync} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLSync(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebGLSync'] = closureSelfUseWebGLSync;

/**
 * @param {!WebGLTransformFeedback} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLTransformFeedback(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebGLTransformFeedback'] = closureSelfUseWebGLTransformFeedback;

/**
 * @param {!WebGLVertexArrayObject} obj
 * @return {!Array<*>}
 */
function closureSelfUseWebGLVertexArrayObject(obj) {
  return [
    obj
  ];
}
globalThis['closureSelfUseWebGLVertexArrayObject'] = closureSelfUseWebGLVertexArrayObject;

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    WebGL2RenderingContext.READ_BUFFER,
    WebGL2RenderingContext.DEPTH_COMPONENT24,
    WebGL2RenderingContext.MAX_FRAGMENT_UNIFORM_COMPONENTS,
    WebGL2RenderingContext.TEXTURE_BINDING_2D_ARRAY,
    WebGL2RenderingContext.RGB8I,
    WebGL2RenderingContext.DEPTH_STENCIL_ATTACHMENT,
    WebGL2RenderingContext.HALF_FLOAT,
    WebGL2RenderingContext.COPY_READ_BUFFER_BINDING,
    WebGL2RenderingContext.MAX_FRAGMENT_INPUT_COMPONENTS,
    WebGL2RenderingContext.MAX_CLIENT_WAIT_TIMEOUT_WEBGL
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
