// Generated by corpus/d2/candidates/npm.collect.py for npm:web-vitals@6.2.3 (Apache-2.0).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  CLSThresholds as e_CLSThresholds,
  FCPThresholds as e_FCPThresholds,
  INPThresholds as e_INPThresholds,
  LCPThresholds as e_LCPThresholds,
  TTFBThresholds as e_TTFBThresholds,
  onCLS as e_onCLS,
  onFCP as e_onFCP,
  onINP as e_onINP,
  onLCP as e_onLCP,
  onTTFB as e_onTTFB,
} from '../../../../corpus-cache/d2/npm/web-vitals@6.2.3/package/dist/web-vitals.js';
globalThis['CLSThresholds'] = e_CLSThresholds;
globalThis['FCPThresholds'] = e_FCPThresholds;
globalThis['INPThresholds'] = e_INPThresholds;
globalThis['LCPThresholds'] = e_LCPThresholds;
globalThis['TTFBThresholds'] = e_TTFBThresholds;
globalThis['onCLS'] = e_onCLS;
globalThis['onFCP'] = e_onFCP;
globalThis['onINP'] = e_onINP;
globalThis['onLCP'] = e_onLCP;
globalThis['onTTFB'] = e_onTTFB;
