// Generated by corpus/d2/candidates/npm.collect.py for npm:jquery@4.0.0 (MIT).
// Imports the package's public API and publishes every export on globalThis so that
// ADVANCED_OPTIMIZATIONS output keeps the package code alive. Do not edit by hand.
import {
  $ as e_$,
  default as e_default,
  jQuery as e_jQuery,
} from '../../../../corpus-cache/d2/npm/jquery@4.0.0/package/dist-module/jquery.module.js';
globalThis['$'] = e_$;
globalThis['default'] = e_default;
globalThis['jQuery'] = e_jQuery;
