/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/gecko_css.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @param {!CSSStyleProperties} obj
 * @return {!Array<*>}
 */
function closureSelfUseCSSStyleProperties(obj) {
  return [
    obj.MozAppearance,
    obj.MozBorderRadiusTopright,
    obj.MozBoxPack,
    obj.MozMarginEnd,
    obj.MozPaddingStart,
    obj.MozWindowShadow
  ];
}
globalThis['closureSelfUseCSSStyleProperties'] = closureSelfUseCSSStyleProperties;

/**
 * @param {!Screen} obj
 * @return {!Array<*>}
 */
function closureSelfUseScreen(obj) {
  return [
    obj.availTop,
    obj.availLeft,
    obj.left,
    obj.top
  ];
}
globalThis['closureSelfUseScreen'] = closureSelfUseScreen;
