/**
 * @fileoverview closure-rs D2 corpus shim (collector closure-self). Exercises the
 *     declarations of externs/browser/window.js under type checking.
 *     Generated by corpus/d2/candidates/closure-self.gen.py from
 *     google/closure-compiler@bb8c8e7. Do not edit.
 */

/**
 * @return {!Array<*>}
 */
function closureSelfUseGlobals() {
  return [
    top,
    document,
    location,
    self,
    window,
    visualViewport,
    clearInterval,
    setImmediate,
    setInterval,
    queueMicrotask,
    alert(0),
    confirm(0),
    prompt('closure-self'),
    reportError(0)
  ];
}
globalThis['closureSelfUseGlobals'] = closureSelfUseGlobals;
