/**
 * @fileoverview Generated by corpus/d2/candidates/npm.collect.py for npm-commonmark-0.31.2-pkg-cjs:
 * Node.js/AMD globals referenced by npm:commonmark@0.31.2 that Closure's default
 * externs do not declare. Do not edit by hand.
 * @externs
 */

/** @type {?} */
var global;

/** @type {?} */
var define;
